### ISSUE TITLE
`odo component list` does not work for Devfile's

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#2989] opened 2020-04-24 17:59 UTC
/kind bug

## What versions of software are you using?

**Operating System:** Linux

**Output of `odo version`:** N/A

## How did you run odo exactly?

I deployed a devfile application

```sh
git clone https://github.com/odo-devfiles/springboot-ex
cd springboot-ex
odo create java-spring-boot myspring
odo push
odo list # does not work
```

## Actual behavior

```sh
~/openshift/springboot-ex  master ✗                                                                                                                                        99d ⚑ ◒  ⍉
▶ ls -lah
total 60K
drwxr-xr-x  6 wikus wikus 4.0K Apr 24 11:55 .
drwxr-xr-x 10 wikus wikus 4.0K Apr 24 11:53 ..
drwxr-xr-x  3 wikus wikus 4.0K Apr 24 11:53 chart
-rw-r--r--  1 wikus wikus  213 Apr 24 11:53 .cw-settings
-rw-r--r--  1 wikus wikus 1.2K Apr 24 11:55 devfile.yaml
-rw-r--r--  1 wikus wikus  237 Apr 24 11:53 Dockerfile
-rw-r--r--  1 wikus wikus 2.4K Apr 24 11:53 Dockerfile-build
-rw-r--r--  1 wikus wikus  325 Apr 24 11:53 Dockerfile-tools
drwxr-xr-x  8 wikus wikus 4.0K Apr 24 13:58 .git
-rw-r--r--  1 wikus wikus   65 Apr 24 13:39 .gitignore
-rw-r--r--  1 wikus wikus   97 Apr 24 11:53 Jenkinsfile
drwxr-x---  3 wikus wikus 4.0K Apr 24 13:39 .odo
-rw-r--r--  1 wikus wikus 3.0K Apr 24 11:53 pom.xml
-rw-r--r--  1 wikus wikus 1.8K Apr 24 11:53 README.md
drwxr-xr-x  4 wikus wikus 4.0K Apr 24 11:53 src

~/openshift/springboot-ex  master ✗                                                                                                                                         99d ⚑ ◒  
▶ odo list
 ✗  Please specify the application name and project name
Or use the command from inside a directory containing an odo component.
```

Despite having a devfile, `odo list` does not work

## Expected behavior

For `odo list` to work

## Any logs, error output, etc?

See above :)

**Comment by girishramnani** [comment] 2020-05-11 07:48
duplicate of https://github.com/openshift/odo/issues/2835
closing

**Closed by girishramnani** 2020-05-11 07:48 UTC
Labels: area/devfile, kind/bug, priority/Medium
