### ISSUE TITLE
Project delete explicitly looking for service catalog instances

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#3336] opened 2020-06-10 10:22 UTC
/kind bug

## What versions of software are you using?

**Operating System:**
Not a specific OS issue
**Output of `odo version`:**
master
## How did you run odo exactly?
Login as kubeadmin
```
$ odo login -u kubeadmin -p ***** https://****:6443
[...]
Using project "default".

$ odo project create test123 -v 4 
✓  Project 'test123' is ready for use
 ✓  New project created and now using project: test123
[...]

$ odo project delete test123 -f -v 4


I0610 15:25:42.325920   25789 application.go:49] Unable to list Service Catalog instances: unable 
to list ServiceInstances: the server could not find the requested resource (get 
serviceinstances.servicecatalog.k8s.io)

 
✓  Deleted project : test123
 [...]
```
Login as developer
```
$ odo login -u developer -p **** https://****:6443
Connecting to the OpenShift cluster
Login successful.
[...]

$ odo project create test123 -v 4
 ✓  Project 'test123' is ready for use
 ✓  New project created and now using project: test123
[...]

$ odo project delete test123 -f -v 4


I0610 15:07:24.963914   25586 application.go:49] Unable to list Service Catalog instances: unable to
 list ServiceInstances: serviceinstances.servicecatalog.k8s.io is forbidden: User "developer" cannot 
list resource "serviceinstances" in API group "servicecatalog.k8s.io" in the namespace "test123"
 

✓  Deleted project : test123
 [...]
```
## Actual behavior
As mentioned in the steps

## Expected behavior
@dharmit @girishramnani Is the expected behaviour as observed in the steps ?

**Comment by dharmit** [comment] 2020-06-18 10:32
IMO this is not expected behaviour. I'm seeing this showing up a LOT in CI (probably because of the numerous `odo project delete` calls). I think this needs to be fixed.

**Comment by dharmit** [comment] 2020-11-25 13:37
We're not seeing this behaviour any longer. Closing. Feel free to re-open if it pops up again.

/close

**Closed** 2020-11-25 13:37 UTC
Labels: kind/bug, lifecycle/rotten
