### ISSUE TITLE
odo create should not ask if i want a starter when it cant create one

### ISSUE THREAD

**Issue by maxandersen** [openshift/odo#4476] opened 2021-03-03 10:38 UTC
/kind bug

i run odo create in an already existing quarkus project and the following happens 👍 
```
❯ odo create
? Which devfile component type do you wish to create java-quarkus
? What do you wish to name the new devfile component java-quarkus
? What project do you want the devfile component to be created in manderse-dev
Validation
 ✓  Checking devfile existence [83135ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [99919ns]
 ✓  Validating devfile component [133463ns]
? Do you want to download a starter project Yes
 ✗  Folder /Users/max/code/personal/demo/my-project is not empty. It can only contain the devfile used.
```

if odo cant create a starter when files exists why even ask the user ?

could it just skip that question for this case?

**Comment by valaparthvi** [comment] 2021-07-06 06:57
Looks like this bug has been fixed.
```shell
➜  ~ mkcd /tmp/backend
➜  backend odo version
odo v2.2.2 (a9e19ae6b)
➜  backend odo create nodejs backend 
Devfile Object Validation
 ✓  Checking devfile existence [19125ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [27269ns]
Validation
 ✓  Validating if devfile name is correct [23786ns]

Please use `odo push` command to create the component with source deployed
➜  backend odo create 
 ✗  this directory already contains a component
```
@maxandersen Feel free to reopen this issue if it bothers again. I'll be closing it for now.

**Closed by valaparthvi** 2021-07-06 06:57 UTC
Labels: area/UX, kind/bug, priority/Medium

**Comment by dharmit** [comment] 2021-07-06 07:47
> Looks like this bug has been fixed.

What I'm seeing in Max's output is that he's used interactive mode to create the component, whereas you've passed the component type and component name to the `odo create` command.

Can you try reproducing the issue using interactive mode (only do `odo create` on CLI).

**Comment by valaparthvi** [comment] 2021-07-06 07:59
>What I'm seeing in Max's output is that he's used interactive mode to create the component, whereas you've passed the component type and component name to the odo create command.

I created the first `odo create` with component type and name to do the setup. Max mentioned he is running `odo create` from an existing quarkus project. 
```shell
➜  ~ mkcd /tmp/backend
➜  backend odo create nodejs backend 
Devfile Object Validation
 ✓  Checking devfile existence [19125ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [27269ns]
Validation
 ✓  Validating if devfile name is correct [23786ns]

Please use `odo push` command to create the component with source deployed
```
The second `odo create` I ran is supposed to be in the interactive mode.
```
➜  backend odo create 
 ✗  this directory already contains a component
```

I also checked the code which seems to be checking the existence of config files and devfile as an early check.
See - https://github.com/openshift/odo/blob/main/pkg/odo/cli/component/create.go#L372

Let me know if I missed something.

**Comment by dharmit** [comment] 2021-07-06 09:17
> The second `odo create` I ran is supposed to be in the interactive mode.

My bad. I didn't see the second one.
