### ISSUE TITLE
"odo push" doesn't delete OpenShift objects when component name is changed

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2172] opened 2019-09-25 07:16 UTC
[kind/bug]

## What versions of software are you using?
- Operating System: all
- Output of `odo version`: master

## How did you run odo exactly?
1. Created a component and pushed it.
2. Changed the name of the component by doing `odo config set name fancy-name` and pushed it using `odo push --config`.
3. OpenShift objects created in step 1 don't get deleted.

## Actual behavior
OpenShift objects from component with old name don't get deleted

## Expected behavior
Shouldn't these objects get deleted? Otherwise, how exactly will these orphaned objects be deleted? By orphaned, I mean that objects that have no corresponding odo component.

**Comment by dharmit** [comment] 2019-09-26 04:50
Besides changing the component name, the behaviour is ditto same when we change the project of the component using `odo config set project <some-project`. The OpenShift objects are untouched in the project to which the component belonged earlier.

**Comment by girishramnani** [comment] 2019-10-12 13:36
I feel this is expected behaviour and if we want to have a cleanup process in place, we should ask `You are changing the project/ component name, this would create an entirely new component, Do you want to delete the current component?`

**Comment by dharmit** [comment] 2019-10-14 08:41
> I feel this is expected behaviour and if we want to have a cleanup process in place, we should ask `You are changing the project/ component name, this would create an entirely new component, Do you want to delete the current component?`

+1. Makes sense to me.

> In my opinion the orphaned objects shouldn't be deleted without consent

And along the same lines, orphaned objects shouldn't be allowed to linger around without consent. That's what prompted me to open this issue. :wink:

**Comment by kadel** [comment] 2019-10-15 15:02
> > I feel this is expected behaviour and if we want to have a cleanup process in place, we should ask `You are changing the project/ component name, this would create an entirely new component, Do you want to delete the current component?`
> 
> +1. Makes sense to me.

But how would you detect that the name was changed?
The only command that can display this message is `odo config`, we could add it there. But that won't prevent someone from changing the name  the localConfig directly without using `odo config` command.
But I guess that we could say that in that case, it is the user's problem what he is doing there.
In this case, we need to explain in the documentation that editing localConfig directly might be dangerous.


> > In my opinion the orphaned objects shouldn't be deleted without consent
> 
> And along the same lines, orphaned objects shouldn't be allowed to linger around without consent. That's what prompted me to open this issue. 😉

Problem is that we can't detect if that the component was orphaned due to name or project change.




First, we need to make a list of the configuration options that can't be easily changed without side effects.

- component name
- project



Then we have two options
1) show a warning when `odo config set` is executed. Each config option will have to have a different message explaining what is going to happen.
2) make the config options unchangeable `odo config set` will complain that user can't change this value.

**Comment by mik-dass** [comment] 2019-10-23 07:25
I think we should warn the user when a project or component name change is initiated and then if he proceeds with the name change, then we should delete the old component and create a new one. @kadel @cdrage WDYT?

**Comment by mik-dass** [comment] 2019-10-25 07:03
> How do we make the last thing happen, i.e., odo config set will complain that user can't change this value? Do we compel it such that whenever user executes something like odo config --set project newproject, it fails with a message? thinking
You mean the user should delete the old component while we already create a new one when they do odo push?

Yes. Whenever the user triggers `odo config --set project newproject` or `odo config --set name newcomponent` we will display a warning that this action will delete the old component and create a new one. If the user presses `y`, we will, in a parallel manner, create the new component and delete the old one. @dharmit @kadel @cdrage @girishramnani WDYT?

**Comment by cdrage** [comment] 2019-10-25 18:07
IMO since the user has already changed the name, I don't think we should prompt for confirmation. If you change the name of your component, you know what you're doing.

I don't think we should even warn the user, maybe in verbose output, but that's it. If changed by config, we should at least confirm that we are going to be changing the component when using `odo push` (confirm the component exists, it has the correct labels, etc.)

**Comment by mik-dass** [comment] 2019-10-29 06:39
> IMO since the user has already changed the name, I don't think we should prompt for confirmation. If you change the name of your component, you know what you're doing.

@cdrage So you mean no confirmation message prompt, just delete the old component and create the new one after triggering the `odo config set` command?

**Comment by cdrage** [comment] 2019-10-31 13:51
@mik-dass Yes, that's correct, deleting the old component and re-creating it.

**Comment by mik-dass** [comment] 2019-11-04 05:42
@kadel WDYT?

**Comment by dharmit** [comment] 2019-11-06 11:10
> IMO since the user has already changed the name, I don't think we should prompt for confirmation. If you change the name of your component, you know what you're doing.
> I don't think we should even warn the user

I believe, it would be helpful to have at least a prompt or a warning message. We're talking about the users who are not really aware of OpenShift. A warning message would be helpful, IMO.

**Comment by kadel** [comment] 2019-11-27 11:23
Let's start asking the user to confirm when  `odo config set name` is executed without `-f`
Something like this.

`You are changing the component name. This action might result in the creation of a duplicate component. If your component is already pushed, please delete the  <old_component_name> after you apply changes (odo component delete <old_component_name> --app <app> --project <project>)`


Of course, the `<something>` placeholders should be released with right values

**Closed** 2019-12-17 09:53 UTC
Labels: kind/bug, points/3, priority/High, state/In Analysis
