### ISSUE TITLE
`odo url create` shouldn't require a port if only one port exists in the devfile

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#3923] opened 2020-09-09 17:43 UTC
/kind bug
/area devfile

## What versions of software are you using?

**Operating System:**
macOS

**Output of `odo version`:**
master

## How did you run odo exactly?
`odo url create --host <ingress-domain>`

## Actual behavior
`odo url create --host <ingress-domain>` without the `--port` flag fails:
```
Johns-MacBook-Pro-3:dev2 johncollier$ odo create --devfile devfile.yaml 
Experimental mode is enabled, use at your own risk

Validation
 ✓  Creating a devfile component from devfile path: /Users/johncollier/ododev/dev2/devfile.yaml [106576ns]
 ✓  Validating devfile component [206951ns]

Please use `odo push` command to create the component with source deployed
Johns-MacBook-Pro-3:dev2 johncollier$ odo url create --host johncollier.ca
 ✗  port must be provided to create an endpoint entry in devfile
```

## Expected behavior
odo detects that there's only one port in the devfile and saves me from manually having to look up the port in the devfile. I believe this was the behaviour in past odo versions.

## Any logs, error output, etc?
Sample devfile:
```
schemaVersion: 2.0.0
metadata:
  name: nodejs
  version: 1.0.0
  alpha.build-dockerfile: "https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/nodejs/build/Dockerfile"
  alpha.deployment-manifest: "https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/nodejs/deploy/deployment-manifest.yaml"
starterProjects:
  - name: nodejs-starter
    git:
      remotes:
        origin: "https://github.com/odo-devfiles/nodejs-ex.git"
components:
  - container:
      name: runtime
      image: registry.access.redhat.com/ubi8/nodejs-12:1-45
      memoryLimit: 1024Mi
      mountSources: true
      sourceMapping: /project
      endpoints:
        - name: http-3000
          targetPort: 3000
commands:
  - exec:
      id: install
      component: runtime
      commandLine: npm install
      workingDir: /project
      group:
        kind: build
        isDefault: true
  - exec:
      id: run
      component: runtime
      commandLine: npm start
      workingDir: /project
      group:
        kind: run
        isDefault: true
  - exec:
      id: debug
      component: runtime
      commandLine: npm run debug
      workingDir: /project
      group:
        kind: debug
        isDefault: true
  - exec:
      id: test
      component: runtime
      commandLine: npm test
      workingDir: /project
      group:
        kind: test
        isDefault: true
```

**Comment by maysunfaisal** [comment] 2020-09-09 19:35
Yeah I found this weird too. But if you dont want to use an ingress, you can just do odo push, and you will have a route that you can use from the default single port in the devfile.

**Comment by johnmcollier** [comment] 2020-09-09 20:05
@maysunfaisal I was on generic Kube, so had to use an ingress 😉

**Comment by elsony** [comment] 2020-09-09 22:08
Even if you are using ingress, the user shouldn't need to specify a port if there is only one exposed port. It sounds like a regression since we used to be able to do that in the past.

**Comment by elsony** [comment] 2020-09-11 21:10
While I am playing around with the beta1 driver, I find the previous behaviour that don't require a port to be specified is much easier to use. Currently, someone new to the devfile support will need to know where to look for the port number in the devfile.yaml even for starter applications.  Our out of the box experience shouldn't require the user to understand the devfile.yaml on day 1 operation.  I think we should fix this so marking this as high priority.

**Comment by johnmcollier** [comment] 2020-09-14 13:24
So, this is actually a worse bug than I thought, it seems exposing an app is entirely broken on Kube.

This is because when running `odo url create` for a port that's already in the devfile, causes a second entry for that port to be added, rather than the existing entry being modified.

Before:
```
components:
  - name: runtime
    container:
      image: registry.access.redhat.com/ubi8/nodejs-12:1-45
      memoryLimit: 1024Mi
      mountSources: true
      sourceMapping: /project
      endpoints:
        - name: http-3000
          targetPort: 3000
```

After:
```
components:
- name: runtime
  container:
    endpoints:
    - name: http-3000
      targetPort: 3000
    - exposure: public
      path: /
      name: nodejs-3000
      targetPort: 3000
      protocol: http
    image: registry.access.redhat.com/ubi8/nodejs-12:1-45
    memoryLimit: 1024Mi
    mountSources: true
    sourceMapping: /project
```

This causes two bad side effects:
1) The pod always gets restarted on the subsequent `odo push` because a second, duplicate port entry gets added to the deployment
2) (Worse) Because the port is now exposed twice, the ingress creation gets messed up and you can't access the application at all over the created URL.

**Comment by scottkurz** [comment] 2020-09-15 12:36
It seems like @johnmcollier made the same point I was going to make, that the **components[0].container.endpoints[0]**
should be updated to add the "exposure: public" pair, etc., rather than adding a new endpoint.   (I'm just restating since the original problem seemed a little different).

As one more point, let me note that the command:  `odo url create --port 9080` deletes the two entries (which John also had in his original example): 

>   alpha.build-dockerfile: "https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/nodejs/build/Dockerfile"
>   alpha.deployment-manifest: "https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/nodejs/deploy/deployment-manifest.yaml"

(I'm running v2.0.0-beta-1 ).

**Comment by yangcao77** [comment] 2020-09-15 19:25
> It seems like @johnmcollier made the same point I was going to make, that the components[0].container.endpoints[0]
should be updated to add the "exposure: public" pair, etc., rather than adding a new endpoint. (I'm just restating since the original problem description seemed a little different).

I don't think this is a valid approach. We use the endpoint name as the URL name, which is suppose to be unique. Creating a new url with a new name should not affect any existing URLs, even they are using the same port under same container. 

> As one more point, let me note that the command: odo url create --port 9080 deletes the two entries (which John also had in his original example):

> > alpha.build-dockerfile: "https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/nodejs/build/Dockerfile"
    alpha.deployment-manifest: "https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/nodejs/deploy/deployment-manifest.yaml"

I have noticed that as well, but this is not a specific issue with url. `odo config set` also has the same issue. The reason is we do not actually "update" the devfile. Instead, we overwrite the devfile with a new devfile data, in which we do not have those metadata saved.

**Comment by johnmcollier** [comment] 2020-09-15 20:06
>>  It seems like @johnmcollier made the same point I was going to make, that the components[0].container.endpoints[0]
    should be updated to add the "exposure: public" pair, etc., rather than adding a new endpoint. (I'm just restating since the original problem description seemed a little different).

> I don't think this is a valid approach. We use the endpoint name as the URL name, which is suppose to be unique. Creating a new url with a new name should not affect any existing URLs, even they are using the same port under same container.

So, I understand the reasoning for this approach (being able to expose both secure and non-secure URLs on the same port), but if we `odo url create` or `odo url create --port <port>` for a port that's already in the devfile, I'd rather we update the existing one by default, rather than adding a duplicate entry. And we would only create a new entry for when a new URL/endpoint name is specified in `odo url create <name> ... --port <port>`

I think it'll be confusing to users on Kube looking over their devfiles to see them modified to have two duplicate endpoints over the same port, but only one URL created.

**Comment by yangcao77** [comment] 2020-09-16 00:36
> So, I understand the reasoning for this approach (being able to expose both secure and non-secure URLs on the same port), but if we odo url create or odo url create --port <port> for a port that's already in the devfile, I'd rather we update the existing endpoint by default, rather than adding a duplicate entry. And we would only create a new entry for the same port when a new URL/endpoint name is specified in odo url create <name> --port <port>

My question is, what if there are multiple existing endpoint using the same port already? Then which one should I update when there is no url name specified?


> I think it'll be confusing to users on Kube looking over their devfiles to see them modified to have two duplicate endpoints over the same port, but only one URL created.

> Additionally, as-is today, the following warning message is shown on every odo push for users on Kube, because we didn't update the existing endpoint when running odo url create, but created a duplicate entry:

> > Creating Kubernetes resources for component nodejs
 ✓  Waiting for component to start [10ms]
 ⚠  Unable to create ingress, missing host information for Endpoint http-3000, please check instructions on URL creation (refer `odo url create --help`)

You are seeing two endpoint sharing the same port only creates one single URL, is because your cluster is not openshift,  `http-3000` cannot be created is because if no host defined for that url, it is assumed to be a route; on a non-openshift cluster it cannot be created, that's why you are seeing that warning message, which is an expected behavior.

**Comment by johnmcollier** [comment] 2020-09-16 02:56
> My question is, what if there are multiple existing endpoints using the same port already? Then which one should I update when there is no url name specified?

If no URL name is specified and there's multiple endpoints in a devfiles using the same port, then I think we should just throw an error.


> You are seeing two endpoint sharing the same port only creates one single URL, is because your cluster is not openshift, http-3000 cannot be created is because if no host defined for that url, it is assumed to be a route; on a non-openshift cluster it cannot be created, that's why you are seeing that warning message, which is an expected behaviout

But I think that's the problem here. By not updating the existing endpoint entry when we try to create a URL for that port, we're creating a scenario that's confusing to users on Kube. It makes it seem like URL creation failed on successive pushes and that the app isn't properly exposed. (At least that's the impression that I got when I saw that warning message)

**Closed** 2020-09-19 09:27 UTC
Labels: area/devfile, area/regression, kind/bug, priority/High
