### ISSUE TITLE
flaky test (failing odo push)

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1628] opened 2019-04-16 11:23 UTC
```
•Running command: odo url create myurl --port 8080
 ✓  URL created for component: nodejs

To create URL on the OpenShift cluster, please run `odo push`
Result: 
 stdout:  ✓  URL created for component: nodejs

To create URL on the OpenShift cluster, please run `odo push`

 stderr: 
 exitcode: 0 
Running command: odo push -v 4
I0416 09:42:45.745489   16663 config.go:587] Git source type detected, not correcting SourcePath location
I0416 09:42:45.748787   16663 preference.go:116] The configFile is /tmp/artifacts/.odo/config.yaml
I0416 09:42:45.748929   16663 occlient.go:445] Trying to connect to server api.ci-op-71467ypl-5186a.origin-ci-int-aws.dev.rhcloud.com:6443
I0416 09:42:45.765117   16663 occlient.go:452] Server https://api.ci-op-71467ypl-5186a.origin-ci-int-aws.dev.rhcloud.com:6443 is up
I0416 09:42:45.831439   16663 occlient.go:375] isLoggedIn err:  <nil> 
 output: "developer"
I0416 09:42:45.831673   16663 context.go:339] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: project
I0416 09:42:45.831701   16663 context.go:339] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: app
I0416 09:42:45.831706   16663 context.go:339] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: project
I0416 09:42:45.848583   16663 context.go:339] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: app
I0416 09:42:45.848622   16663 context.go:339] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: output
I0416 09:42:45.848628   16663 context.go:339] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: component
 •  Checking component  ...
I0416 09:42:46.063294   16663 catalog.go:222] Found builder images: [{dotnet openshift [1.0 1.1 2.0 2.1 2.2 latest] [1.0 1.1 2.1 2.2 latest]} {eap-cd-openshift openshift [12 12.0 13 13.0 14 14.0 15 15.0 latest] []} {fis-java-openshift openshift [1.0 2.0] []} {fis-karaf-openshift openshift [1.0 2.0] []} {fuse7-eap-openshift openshift [1.0 1.1 1.2] []} {fuse7-java-openshift openshift [1.0 1.1 1.2] []} {fuse7-karaf-openshift openshift [1.0 1.1 1.2] []} {httpd openshift [2.4 latest] [2.4 latest]} {java openshift [8 latest] [8 latest]} {jboss-decisionserver64-openshift openshift [1.0 1.1 1.2 1.3 1.4 1.5] []} {jboss-eap64-openshift openshift [1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 latest] []} {jboss-eap70-openshift openshift [1.3 1.4 1.5 1.6 1.7] []} {jboss-eap71-openshift openshift [1.1 1.2 1.3 1.4 latest] []} {jboss-eap72-openshift openshift [1.0 latest] []} {jboss-fuse70-eap-openshift openshift [1.0] []} {jboss-fuse70-java-openshift openshift [1.0] []} {jboss-fuse70-karaf-openshift openshift [1.0] []} {jboss-processserver64-openshift openshift [1.0 1.1 1.2 1.3 1.4 1.5] []} {jboss-webserver30-tomcat7-openshift openshift [1.1 1.2 1.3] []} {jboss-webserver30-tomcat8-openshift openshift [1.1 1.2 1.3] []} {jboss-webserver31-tomcat7-openshift openshift [1.0 1.1 1.2] []} {jboss-webserver31-tomcat8-openshift openshift [1.0 1.1 1.2] []} {nginx openshift [1.10 1.12 1.8 latest] [1.10 1.12 1.8 latest]} {nodejs openshift [0.10 10 4 6 8 8-RHOAR latest] [10 6 8 8-RHOAR latest]} {perl openshift [5.16 5.20 5.24 5.26 latest] [5.24 5.26 latest]} {php openshift [5.5 5.6 7.0 7.1 7.2 latest] [7.0 7.1 7.2 latest]} {python openshift [2.7 3.3 3.4 3.5 3.6 latest] [2.7 3.5 3.6 latest]} {redhat-openjdk18-openshift openshift [1.0 1.1 1.2 1.3 1.4 1.5] []} {ruby openshift [2.0 2.2 2.3 2.4 2.5 latest] [2.3 2.4 2.5 latest]} {wildfly openshift [10.0 10.1 11.0 12.0 13.0 14.0 15.0 16.0 8.1 9.0 latest] [10.0 10.1 11.0 12.0 13.0 14.0 15.0 16.0 8.1 9.0 latest]}]
 ✓  Checking component
 •  Checking component version  ...
 ✓  Checking component version
I0416 09:42:46.194514   16663 catalog.go:222] Found builder images: [{dotnet openshift [1.0 1.1 2.0 2.1 2.2 latest] [1.0 1.1 2.1 2.2 latest]} {eap-cd-openshift openshift [12 12.0 13 13.0 14 14.0 15 15.0 latest] []} {fis-java-openshift openshift [1.0 2.0] []} {fis-karaf-openshift openshift [1.0 2.0] []} {fuse7-eap-openshift openshift [1.0 1.1 1.2] []} {fuse7-java-openshift openshift [1.0 1.1 1.2] []} {fuse7-karaf-openshift openshift [1.0 1.1 1.2] []} {httpd openshift [2.4 latest] [2.4 latest]} {java openshift [8 latest] [8 latest]} {jboss-decisionserver64-openshift openshift [1.0 1.1 1.2 1.3 1.4 1.5] []} {jboss-eap64-openshift openshift [1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 latest] []} {jboss-eap70-openshift openshift [1.3 1.4 1.5 1.6 1.7] []} {jboss-eap71-openshift openshift [1.1 1.2 1.3 1.4 latest] []} {jboss-eap72-openshift openshift [1.0 latest] []} {jboss-fuse70-eap-openshift openshift [1.0] []} {jboss-fuse70-java-openshift openshift [1.0] []} {jboss-fuse70-karaf-openshift openshift [1.0] []} {jboss-processserver64-openshift openshift [1.0 1.1 1.2 1.3 1.4 1.5] []} {jboss-webserver30-tomcat7-openshift openshift [1.1 1.2 1.3] []} {jboss-webserver30-tomcat8-openshift openshift [1.1 1.2 1.3] []} {jboss-webserver31-tomcat7-openshift openshift [1.0 1.1 1.2] []} {jboss-webserver31-tomcat8-openshift openshift [1.0 1.1 1.2] []} {nginx openshift [1.10 1.12 1.8 latest] [1.10 1.12 1.8 latest]} {nodejs openshift [0.10 10 4 6 8 8-RHOAR latest] [10 6 8 8-RHOAR latest]} {perl openshift [5.16 5.20 5.24 5.26 latest] [5.24 5.26 latest]} {php openshift [5.5 5.6 7.0 7.1 7.2 latest] [7.0 7.1 7.2 latest]} {python openshift [2.7 3.3 3.4 3.5 3.6 latest] [2.7 3.5 3.6 latest]} {redhat-openjdk18-openshift openshift [1.0 1.1 1.2 1.3 1.4 1.5] []} {ruby openshift [2.0 2.2 2.3 2.4 2.5 latest] [2.3 2.4 2.5 latest]} {wildfly openshift [10.0 10.1 11.0 12.0 13.0 14.0 15.0 16.0 8.1 9.0 latest] [10.0 10.1 11.0 12.0 13.0 14.0 15.0 16.0 8.1 9.0 latest]}]
I0416 09:42:46.240422   16663 occlient.go:2699] Getting DeploymentConfig: nodejs-myapp
I0416 09:42:46.263635   16663 component.go:866] Source for component nodejs is https://github.com/openshift/nodejs-ex (git)
I0416 09:42:46.263693   16663 url.go:78] Listing routes with label selector: app.kubernetes.io/name=myapp,app.kubernetes.io/component-name=nodejs
I0416 09:42:46.318564   16663 occlient.go:2699] Getting DeploymentConfig: nodejs-myapp
I0416 09:42:46.390046   16663 occlient.go:2699] Getting DeploymentConfig: nodejs-myapp
I0416 09:42:46.407611   16663 component.go:866] Source for component nodejs is https://github.com/openshift/nodejs-ex (git)
I0416 09:42:46.407651   16663 url.go:78] Listing routes with label selector: app.kubernetes.io/name=myapp,app.kubernetes.io/component-name=nodejs
I0416 09:42:46.462623   16663 occlient.go:2699] Getting DeploymentConfig: nodejs-myapp
I0416 09:42:46.595180   16663 request.go:485] Throttling request took 115.396138ms, request: GET:https://api.ci-op-71467ypl-5186a.origin-ci-int-aws.dev.rhcloud.com:6443/apis/apps.openshift.io/v1/namespaces/json-test/deploymentconfigs?labelSelector=app.kubernetes.io%2Fname%3Dmyapp%2Capp.kubernetes.io%2Fcomponent-name%3Dnodejs
I0416 09:42:46.612983   16663 occlient.go:2699] Getting DeploymentConfig: nodejs-myapp
 ✓  Applying component settings to component: nodejs
I0416 09:42:46.795166   16663 request.go:485] Throttling request took 182.085932ms, request: GET:https://api.ci-op-71467ypl-5186a.origin-ci-int-aws.dev.rhcloud.com:6443/apis/apps.openshift.io/v1/namespaces/json-test/deploymentconfigs/nodejs-myapp
I0416 09:42:46.812593   16663 component.go:866] Source for component nodejs is https://github.com/openshift/nodejs-ex (git)
I0416 09:42:46.812741   16663 occlient.go:2699] Getting DeploymentConfig: nodejs-myapp
I0416 09:42:46.995078   16663 request.go:485] Throttling request took 182.261292ms, request: GET:https://api.ci-op-71467ypl-5186a.origin-ci-int-aws.dev.rhcloud.com:6443/apis/apps.openshift.io/v1/namespaces/json-test/deploymentconfigs/nodejs-myapp
I0416 09:42:47.012273   16663 component.go:977] Updating component nodejs, from git to https://github.com/openshift/nodejs-ex (git).
I0416 09:42:47.012366   16663 occlient.go:2083] Getting BuildConfig: nodejs-myapp
I0416 09:42:47.057427   16663 occlient.go:2083] Getting BuildConfig: nodejs-myapp
I0416 09:42:47.078766   16663 component.go:1057] Updating the DeploymentConfig nodejs-myapp image to nodejs-myapp:latest
I0416 09:42:47.195031   16663 request.go:485] Throttling request took 114.829796ms, request: PUT:https://api.ci-op-71467ypl-5186a.origin-ci-int-aws.dev.rhcloud.com:6443/apis/apps.openshift.io/v1/namespaces/json-test/deploymentconfigs/nodejs-myapp
I0416 09:42:47.344911   16663 utils.go:52] Desired revision (3) is different from the running revision (2)
I0416 09:42:47.442821   16663 utils.go:52] Desired revision (3) is different from the running revision (2)
I0416 09:42:52.842803   16663 utils.go:52] Desired revision (3) is different from the running revision (2)
I0416 09:42:54.842771   16663 utils.go:52] Desired revision (3) is different from the running revision (2)
I0416 09:42:55.042758   16663 utils.go:52] Desired revision (3) is different from the running revision (2)
I0416 09:43:04.443273   16663 utils.go:52] Desired revision (3) is different from the running revision (2)
I0416 09:43:05.442725   16663 utils.go:52] Desired revision (3) is different from the running revision (2)
I0416 09:47:47.344801   16663 cmdutils.go:23] Error:
unable to update DeploymentConfig image for nodejs component: unable to update the current DeploymentConfig nodejs-myapp: unable to wait for DeploymentConfig nodejs-myapp to update: Timed out waiting for annotation to update
 ✗  Failed to update config to component deployed

```

**Comment by amitkrout** [comment] 2019-04-16 11:25
```
$ oc get dc -o yaml
apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      app.kubernetes.io/component-source-type: git
      app.kubernetes.io/url: https://github.com/openshift/nodejs-ex
    creationTimestamp: 2019-04-16T11:04:12Z
    generation: 5
    labels:
      app: myapp
      app.kubernetes.io/component-name: nodejs
      app.kubernetes.io/component-type: nodejs
      app.kubernetes.io/component-version: latest
      app.kubernetes.io/name: myapp
    name: nodejs-myapp
    namespace: json-test
    resourceVersion: "204273"
    selfLink: /apis/apps.openshift.io/v1/namespaces/json-test/deploymentconfigs/nodejs-myapp
    uid: 5e112358-6037-11e9-b9da-0a580a800041
  spec:
    replicas: 1
    selector:
      deploymentconfig: nodejs-myapp
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: nodejs-myapp
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/json-test/nodejs-myapp@sha256:c91495338896114cdc9b039028df41243ea084262ceb62194867765f1ebc7a8a
          imagePullPolicy: Always
          name: nodejs-myapp
          ports:
          - containerPort: 8080
            name: 8080-tcp
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - nodejs-myapp
        from:
          kind: ImageStreamTag
          name: nodejs-myapp:latest
          namespace: json-test
        lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/json-test/nodejs-myapp@sha256:c91495338896114cdc9b039028df41243ea084262ceb62194867765f1ebc7a8a
      type: ImageChange
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2019-04-16T11:07:46Z
      lastUpdateTime: 2019-04-16T11:07:46Z
      message: Deployment config has minimum availability.
      status: "True"
      type: Available
    - lastTransitionTime: 2019-04-16T11:07:36Z
      lastUpdateTime: 2019-04-16T11:07:47Z
      message: replication controller "nodejs-myapp-2" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: "True"
      type: Progressing
    details:
      causes:
      - imageTrigger:
          from:
            kind: DockerImage
            name: image-registry.openshift-image-registry.svc:5000/json-test/nodejs-myapp@sha256:c91495338896114cdc9b039028df41243ea084262ceb62194867765f1ebc7a8a
        type: ImageChange
      message: image change
    latestVersion: 2
    observedGeneration: 5
    readyReplicas: 1
    replicas: 1
    unavailableReplicas: 0
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by amitkrout** [comment] 2019-04-16 11:26
```
$ oc get rc -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    annotations:
      openshift.io/deployer-pod.completed-at: 2019-04-16 11:06:01 +0000 UTC
      openshift.io/deployer-pod.created-at: 2019-04-16 11:05:43 +0000 UTC
      openshift.io/deployer-pod.name: nodejs-myapp-1-deploy
      openshift.io/deployment-config.latest-version: "1"
      openshift.io/deployment-config.name: nodejs-myapp
      openshift.io/deployment.phase: Complete
      openshift.io/deployment.replicas: "1"
      openshift.io/deployment.status-reason: config change
      openshift.io/encoded-deployment-config: |
        {"kind":"DeploymentConfig","apiVersion":"apps.openshift.io/v1","metadata":{"name":"nodejs-myapp","namespace":"json-test","selfLink":"/apis/apps.openshift.io/v1/namespaces/json-test/deploymentconfigs/nodejs-myapp","uid":"5e112358-6037-11e9-b9da-0a580a800041","resourceVersion":"199997","generation":2,"creationTimestamp":"2019-04-16T11:04:12Z","labels":{"app":"myapp","app.kubernetes.io/component-name":"nodejs","app.kubernetes.io/component-type":"nodejs","app.kubernetes.io/component-version":"latest","app.kubernetes.io/name":"myapp"},"annotations":{"app.kubernetes.io/component-source-type":"git","app.kubernetes.io/url":"https://github.com/openshift/nodejs-ex"}},"spec":{"strategy":{"type":"Recreate","recreateParams":{"timeoutSeconds":600},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ConfigChange"},{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["nodejs-myapp"],"from":{"kind":"ImageStreamTag","namespace":"json-test","name":"nodejs-myapp:latest"},"lastTriggeredImage":"image-registry.openshift-image-registry.svc:5000/json-test/nodejs-myapp@sha256:91efa21bbab7df02ead85a86a898818ec8452ce2ddecad06b78c60ff3f07fdbe"}}],"replicas":1,"revisionHistoryLimit":10,"test":false,"selector":{"deploymentconfig":"nodejs-myapp"},"template":{"metadata":{"creationTimestamp":null,"labels":{"deploymentconfig":"nodejs-myapp"}},"spec":{"containers":[{"name":"nodejs-myapp","image":"image-registry.openshift-image-registry.svc:5000/json-test/nodejs-myapp@sha256:91efa21bbab7df02ead85a86a898818ec8452ce2ddecad06b78c60ff3f07fdbe","ports":[{"name":"8080-tcp","containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":1,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"config change","causes":[{"type":"ConfigChange"}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2019-04-16T11:04:13Z","lastTransitionTime":"2019-04-16T11:04:13Z","message":"Deployment config does not have minimum availability."}]}}
    creationTimestamp: 2019-04-16T11:05:43Z
    generation: 3
    labels:
      app: myapp
      app.kubernetes.io/component-name: nodejs
      app.kubernetes.io/component-type: nodejs
      app.kubernetes.io/component-version: latest
      app.kubernetes.io/name: myapp
      openshift.io/deployment-config.name: nodejs-myapp
    name: nodejs-myapp-1
    namespace: json-test
    ownerReferences:
    - apiVersion: apps.openshift.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: DeploymentConfig
      name: nodejs-myapp
      uid: 5e112358-6037-11e9-b9da-0a580a800041
    resourceVersion: "201114"
    selfLink: /api/v1/namespaces/json-test/replicationcontrollers/nodejs-myapp-1
    uid: 9425e645-6037-11e9-816f-0ef72485a714
  spec:
    replicas: 0
    selector:
      deployment: nodejs-myapp-1
      deploymentconfig: nodejs-myapp
    template:
      metadata:
        annotations:
          openshift.io/deployment-config.latest-version: "1"
          openshift.io/deployment-config.name: nodejs-myapp
          openshift.io/deployment.name: nodejs-myapp-1
        creationTimestamp: null
        labels:
          deployment: nodejs-myapp-1
          deploymentconfig: nodejs-myapp
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/json-test/nodejs-myapp@sha256:91efa21bbab7df02ead85a86a898818ec8452ce2ddecad06b78c60ff3f07fdbe
          imagePullPolicy: Always
          name: nodejs-myapp
          ports:
          - containerPort: 8080
            name: 8080-tcp
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    observedGeneration: 3
    replicas: 0
- apiVersion: v1
  kind: ReplicationController
  metadata:
    annotations:
      openshift.io/deployer-pod.completed-at: 2019-04-16 11:07:46 +0000 UTC
      openshift.io/deployer-pod.created-at: 2019-04-16 11:07:18 +0000 UTC
      openshift.io/deployer-pod.name: nodejs-myapp-2-deploy
      openshift.io/deployment-config.latest-version: "2"
      openshift.io/deployment-config.name: nodejs-myapp
      openshift.io/deployment.phase: Complete
      openshift.io/deployment.replicas: "1"
      openshift.io/deployment.status-reason: image change
      openshift.io/encoded-deployment-config: |
        {"kind":"DeploymentConfig","apiVersion":"apps.openshift.io/v1","metadata":{"name":"nodejs-myapp","namespace":"json-test","selfLink":"/apis/apps.openshift.io/v1/namespaces/json-test/deploymentconfigs/nodejs-myapp","uid":"5e112358-6037-11e9-b9da-0a580a800041","resourceVersion":"201006","generation":3,"creationTimestamp":"2019-04-16T11:04:12Z","labels":{"app":"myapp","app.kubernetes.io/component-name":"nodejs","app.kubernetes.io/component-type":"nodejs","app.kubernetes.io/component-version":"latest","app.kubernetes.io/name":"myapp"},"annotations":{"app.kubernetes.io/component-source-type":"git","app.kubernetes.io/url":"https://github.com/openshift/nodejs-ex"}},"spec":{"strategy":{"type":"Recreate","recreateParams":{"timeoutSeconds":600},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ConfigChange"},{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["nodejs-myapp"],"from":{"kind":"ImageStreamTag","namespace":"json-test","name":"nodejs-myapp:latest"},"lastTriggeredImage":"image-registry.openshift-image-registry.svc:5000/json-test/nodejs-myapp@sha256:c91495338896114cdc9b039028df41243ea084262ceb62194867765f1ebc7a8a"}}],"replicas":1,"revisionHistoryLimit":10,"test":false,"selector":{"deploymentconfig":"nodejs-myapp"},"template":{"metadata":{"creationTimestamp":null,"labels":{"deploymentconfig":"nodejs-myapp"}},"spec":{"containers":[{"name":"nodejs-myapp","image":"image-registry.openshift-image-registry.svc:5000/json-test/nodejs-myapp@sha256:c91495338896114cdc9b039028df41243ea084262ceb62194867765f1ebc7a8a","ports":[{"name":"8080-tcp","containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":2,"observedGeneration":2,"replicas":1,"updatedReplicas":1,"availableReplicas":1,"unavailableReplicas":0,"details":{"message":"image change","causes":[{"type":"ImageChange","imageTrigger":{"from":{"kind":"DockerImage","name":"image-registry.openshift-image-registry.svc:5000/json-test/nodejs-myapp@sha256:c91495338896114cdc9b039028df41243ea084262ceb62194867765f1ebc7a8a"}}}]},"conditions":[{"type":"Available","status":"True","lastUpdateTime":"2019-04-16T11:06:01Z","lastTransitionTime":"2019-04-16T11:06:01Z","message":"Deployment config has minimum availability."},{"type":"Progressing","status":"True","lastUpdateTime":"2019-04-16T11:06:02Z","lastTransitionTime":"2019-04-16T11:06:02Z","reason":"NewReplicationControllerAvailable","message":"replication controller \"nodejs-myapp-1\" successfully rolled out"}],"readyReplicas":1}}
    creationTimestamp: 2019-04-16T11:07:18Z
    generation: 2
    labels:
      app: myapp
      app.kubernetes.io/component-name: nodejs
      app.kubernetes.io/component-type: nodejs
      app.kubernetes.io/component-version: latest
      app.kubernetes.io/name: myapp
      openshift.io/deployment-config.name: nodejs-myapp
    name: nodejs-myapp-2
    namespace: json-test
    ownerReferences:
    - apiVersion: apps.openshift.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: DeploymentConfig
      name: nodejs-myapp
      uid: 5e112358-6037-11e9-b9da-0a580a800041
    resourceVersion: "201347"
    selfLink: /api/v1/namespaces/json-test/replicationcontrollers/nodejs-myapp-2
    uid: cca75116-6037-11e9-816f-0ef72485a714
  spec:
    replicas: 1
    selector:
      deployment: nodejs-myapp-2
      deploymentconfig: nodejs-myapp
    template:
      metadata:
        annotations:
          openshift.io/deployment-config.latest-version: "2"
          openshift.io/deployment-config.name: nodejs-myapp
          openshift.io/deployment.name: nodejs-myapp-2
        creationTimestamp: null
        labels:
          deployment: nodejs-myapp-2
          deploymentconfig: nodejs-myapp
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/json-test/nodejs-myapp@sha256:c91495338896114cdc9b039028df41243ea084262ceb62194867765f1ebc7a8a
          imagePullPolicy: Always
          name: nodejs-myapp
          ports:
          - containerPort: 8080
            name: 8080-tcp
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by amitkrout** [comment] 2019-04-16 12:38
#1625

**Comment by amitkrout** [comment] 2019-04-16 13:17
@surajnarwade @mohammedzee1000 Are you seeing anything suspicious in https://github.com/openshift/odo/issues/1628#issuecomment-483620139 and https://github.com/openshift/odo/issues/1628#issuecomment-483620349 with respect to the push failure ?

**Comment by cdrage** [comment] 2019-04-17 03:13
I've been trying this for about 6-8 hours and I've only able to replicate this TWICE out of about 30 runs of:

```sh
▶ odo delete -f && rm -rf .odo && odo create nodejs nodejs --app myapp --project json-test --git https://github.com/openshift/nodejs-ex && odo push -v 4 && odo url create myurl --port 8080 && odo push -v 4
```

So when the bug occurs, the current revision (after the first push) is:
```sh
NAME           REVISION   DESIRED   CURRENT   TRIGGERED BY
nodejs-myapp   2         1         0         config,image(node-myapp:latest)
```

With the current desired still being `0` and effectively it's still not *fully* deployed.

When diagnosing this issue, I also ran into ANOTHER issue from doing `odo push && odo url create && odo push` in quick 

```sh
unable to update DeploymentConfig image for nodejs component: unable to update the current DeploymentConfig nodejs-myapp: unable to update DeploymentConfig nodejs-myapp: Operation cannot be fulfilled on deploymentconfigs.apps.openshift.io "nodejs-myapp": the object has been
 modified; please apply your changes to the latest version and try again
 ✗  Failed to update config to component deployed
```

I will add validation for DeploymentConfig as we are not checking for correct DC deployment after BuildConfig is used / has updated DC: https://github.com/openshift/odo/blob/master/pkg/occlient/occlient.go#L1646

We've got to make sure that it's correctly waiting for the DC to fully update as after building git, as we are not waiting for DC to finish.

**Comment by amitkrout** [comment] 2019-04-18 07:02
Reproducible on TravisCI too - https://travis-ci.org/openshift/odo/jobs/521316421 via pr #1632.

**Comment by kadel** [comment] 2019-04-23 07:01
attempting to fix this issue in #1634

**Comment by cdrage** [comment] 2019-04-23 13:50
https://github.com/openshift/odo/issues/1633 is also related to this issue (two issues in one).

**Comment by amitkrout** [comment] 2019-05-06 09:48
@kadel @cdrage Ci consistently reporting the same failure in my pr #1612 - https://travis-ci.org/openshift/odo/jobs/528706216

**Comment by amitkrout** [comment] 2019-06-12 09:16
Similar scenario is covered in ```generic```,  ```java``` and ```json``` test file. None of the time the issue is hit in each pr run since it was last reproduce. Probably #1633 fixed this flake.

Lets take a call in sprint planning meeting for the next action.

**Comment by girishramnani** [comment] 2019-06-12 12:43
Closing this bug as it is being reproduced

**Closed by girishramnani** 2019-06-12 12:43 UTC
Labels: priority/High, state/In Analysis
