### ISSUE TITLE
Merging is blocked due to CI issue (route53 error)

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1941] opened 2019-07-23 08:20 UTC
```
level=fatal msg="failed to fetch Terraform Variables: failed to fetch dependency of \"Terraform Variables\": failed to fetch dependency of \"Bootstrap Ignition Config\": failed to fetch dependency of \"Common Manifests\": failed to generate asset \"DNS Config\": getting public zone for \"origin-ci-int-aws.dev.rhcloud.com\": No public route53 zone found matching name \"origin-ci-int-aws.dev.rhcloud.com\""
```

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/1939/pull-ci-openshift-odo-master-integration/940
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/1918/pull-ci-openshift-odo-master-integration/941

**Comment by amitkrout** [comment] 2019-07-24 07:37
Seems no resolution has been done form the concern team - https://coreos.slack.com/archives/CBN38N3MW/p1563853906030000

**Comment by amitkrout** [comment] 2019-07-25 09:04
The issue is fixed as per the last comment in the slack thread [1]. I updated one of my pr and i do not see the issue in OpenShift CI. Hence closing the issue. 

[1] https://coreos.slack.com/archives/CBN38N3MW/p1563974411089800?thread_ts=1563853906.030000&cid=CBN38N3MW

**Closed by amitkrout** 2019-07-25 09:04 UTC
Labels: priority/critical-urgent
