### ISSUE TITLE
"odo create" supports for dowloading devfile compoent template

### ISSUE THREAD

**Issue by GeekArthur** [openshift/odo#2850] opened 2020-04-08 19:41 UTC
/kind user-story

## User Story
As a user I want to use the template that is compatible with the devfile I specify during `odo create [component type]` so that I don't need to bring my own template and I can start working on the component development based on the provided template.

## Acceptance Criteria 
- [ ] Read the template location directly from devfile and use that template location to download template:
```
projects:
-
  name: example
  source:
    type: git
    location: https://github.com/golang/example.git
  clonePath: src/github.com/golang/example/
```
- [ ] Create a new flag like `--template` to enable the feature of downloading template

That's my initial thought and rough idea 🤔 , please feel free to add comments or questions

/kind user-story
/area devfile

**Comment by johnmcollier** [comment] 2020-04-08 22:27
@GeekArthur This seems like a dupe of https://github.com/openshift/odo/issues/2582?

**Comment by GeekArthur** [comment] 2020-04-09 15:19
@johnmcollier Yeah, essentially they are talking about the same thing, but for the time being we can leave this issue open to keep the rough design, then we can use one issue to track until we finalize the design. Thanks for pointing this out.

**Comment by elsony** [comment] 2020-04-20 18:14
Closing this one since this is a dup of #2582 . Design info can be found on that item.

**Closed** 2020-04-20 18:14 UTC
Labels: area/devfile, kind/user-story
