### ISSUE TITLE
odo url list -o json does not report not pushed URLs

### ISSUE THREAD

**Issue by jeffmaury** [openshift/odo#1947] opened 2019-07-24 13:45 UTC
[kind/bug]

## What versions of software are you using?
- Operating System: Win10Pro
- Output of `odo version`:

```
odo v1.0.0-beta3 (c2b402e3)

Server: https://api.rh-us-east-1.openshift.com:443
OpenShift: v3.11.43
Kubernetes: v1.11.0+d4cacc0
```

## How did you run odo exactly?

` odo url list -o json`

## Actual behavior

```
$ odo url list -o json
{"kind":"List","apiVersion":"odo.openshift.io/v1alpha1","metadata":{},"items":[{"kind":"url","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"url1","creationTimestamp":null},"spec":{"host":"url1-sbapp-sbproject.6923.rh-us-east-1.openshiftapps.com","protocol":"http","port":8080}}]}
```

Output of `odo url list`:

```
$ odo url list
Found the following URLs for component sbcomp in application sbapp:
NAME     URL                                                                 PORT
url1     http://url1-sbapp-sbproject.6923.rh-us-east-1.openshiftapps.com     8080
url2     <not created on cluster>                                            8080

Use `odo push` to create url on cluster
```
## Expected behavior

Reports non pushed URLs as well

**Comment by kadel** [comment] 2019-08-12 06:23
duplicate of https://github.com/openshift/odo/issues/1893
/close

**Closed by kadel** 2019-08-12 06:23 UTC
