### ISSUE TITLE
`odo service create` doesn't honor parameters

### ISSUE THREAD

**Issue by VeerMuchandi** [openshift/odo#2069] opened 2019-08-30 21:12 UTC
[kind/bug]

## What versions of software are you using?
- Operating System:
- Output of `odo version`:

```
$ odo version
odo v1.0.0-beta4 (d11517f1)
```

## How did you run odo exactly?

```
odo service create mongodb-ephemeral mongodb -p DATABASE_SERVICE_NAME=mongodb -p MONGODB_USER=user -p MONGODB_PASSWORD=password -p MONGODB_DATABASE=todos -p MONGODB_ADMIN_PASSWORD=password
```
The result of the above command creates a database along with a secret `mongodb`. If you reveal the secret values they are different (only uses defaults and ignores supplied parameters).  I also tried to use params comma separated. No difference.

Compare this with
```
oc new-app --template=mongodb-ephemeral \
--param=DATABASE_SERVICE_NAME=mongodb \
--param=MONGODB_USER=user \
--param=MONGODB_PASSWORD=password \
--param=MONGODB_DATABASE=todos \
--param=MONGODB_ADMIN_PASSWORD=password
```
which creates the secret `mongodb` with the values you want.

## Actual behavior
`odo` not using the values supplied as parameters

## Expected behavior
`odo` should create secret using parameters supplied

**Comment by kadel** [comment] 2019-09-02 07:21
This looks like duplicate of https://github.com/openshift/odo/issues/2033

**Comment by dharmit** [comment] 2019-09-04 10:16
I think it's not an exact dupe because the parameters will be accessible/visible under the "Environment" tab on OpenShift console and not stored as a secret as mentioned in "Expected behavior". AFAIK, this is true even when setting the parameters using interactive mode of `odo service create`.

**Comment by kadel** [comment] 2019-09-04 11:55
@dharmit the  Secret is created automatically by Service Broker. It doesn't matter if you call it using oc or odo. This is auto of clients control.

The problem was that odo didn't pass the parameters to ServiceInstance. This got fixed in https://github.com/openshift/odo/pull/2040/


You will be always able to read Secret values in OpenShift console.

**Comment by girishramnani** [comment] 2019-12-26 08:45
Actually when you provide param using odo then its not stored as secret vs when creating using oc its created as a secret and then injected. I had opened an issue related to this https://github.com/openshift/odo/issues/2044

**Comment by girishramnani** [comment] 2019-12-26 08:49
as per @kadel comment it seems this is a duplicate. Closing

**Closed by girishramnani** 2019-12-26 08:49 UTC
Labels: area/service, kind/bug
