### ISSUE TITLE
use Devfiles for s2i components

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4281] opened 2020-12-03 08:43 UTC
Use devfile.yml for s2i components instead of LocalConfig.yaml

# Motivation

Odo has two types of components, Devfile and s2i. Currently, each component type has its own separate code path. This means that each command needs to understand how to do the action for Devfile and also for s2i. Technically it is possible to create a Devfile that will mimic what odo is doing with s2i. We already have this in `odo utils convert`. Odo should leverage that logic and start treating s2i components as regular Devfile. This will reduce the odo code base and will make code maintenance a lot simpler.

## `odo create --s2i`

`odo create --s2i` command would no longer generate `LocalConfig` (`./odo/config.yml`). Instead, it should just generate `devfile.yml`, and optionally `./odo/env.yml`) depending on what will be required.

## all other commands

The rest of the commands (like `odo storage`, `odo url`, etc..) should not need to know anything about s2i. For them, it will be just another Devfile component. 

## Acceptance Criteria

- [x] `odo create --s2i` should use the s2i to devfile tool to build the devfile on the fly and follow devfile flow in the future.
- [x] if user has existing `LocalConfig` s2i component it still needs to work
- [ ]  We're going to need to make changes to odo create -h as well.
- [ ]  Finally, we're going to need to update docs that end on odo.dev site as well.

**Comment by dharmit** [comment] 2021-01-18 11:38
@girishramnani you might want to consider #4201 while working on this. Basically, `odo create --s2i` with `--env` should not break if we were to keep compatibility with `odo create` from v1.

**Comment by dharmit** [comment] 2021-01-21 13:41
Also consider `odo link` with Service Catalog breaking since this works only between s2i component & SC backed service.

**Comment by dharmit** [comment] 2021-01-21 13:45
Need https://github.com/openshift/odo/pull/4369 to go in first, right @girishramnani ?

**Comment by girishramnani** [comment] 2021-02-09 14:59
Just so its documented - I dont think `--now` flag works for devfile so I am not gonna worry about it for now

**Comment by girishramnani** [comment] 2021-02-09 15:59
Also this issue will break all s2i components - no existing s2i components would work.

**Comment by kadel** [comment] 2021-02-09 16:15
> Also this issue will break all s2i components - no existing s2i components would work.

I forgot to mention that in the issue :-(. This can't break existing s2i components without any warning. 
We either have to find a way to convert existing s2i components or keep the s2i code there for some time and display a depreciation warning and then after a few releases remove it.

**Comment by girishramnani** [comment] 2021-02-09 16:41
we can do a Y stream release to signify such a huge breaking change @kadel

**Comment by girishramnani** [comment] 2021-02-09 16:57
We can deprecate s2i components using an early PR that goes in the week’s release and then this PR can be released in later version

**Comment by kadel** [comment] 2021-02-10 08:11
> we can do a Y stream release to signify such a huge breaking change @kadel

Y stream should not break backward compatibility.



> We can deprecate s2i components using an early PR that goes in the week’s release and then this PR can be released in later version

that is too quick.



BTW the original idea for this PR was to just make sure that new components will be all based on Devfile.
But the existing components, even old s2i based on LocalConfig should work as they currently do.

Removal of LocalConfig components would happen later.

**Comment by girishramnani** [comment] 2021-02-11 10:38
> BTW the original idea for this PR was to just make sure that new components will be all based on Devfile.
> But the existing components, even old s2i based on LocalConfig should work as they currently do.

I cannot see that on the issue description before you updated it yesterday.

**Comment by girishramnani** [comment] 2021-02-11 10:43
As part of the PR I have completed the 1st AC but as I have removed all s2i code so I need to reverse that

- [ ] if user has existing LocalConfig s2i component it still needs to work
- [ ] We're going to need to make changes to odo create -h as well.
- [ ] Finally, we're going to need to update docs that end on odo.dev site as well.

**Comment by girishramnani** [comment] 2021-02-16 18:02
also `--git` will no longer be supported as devfile doesn't support that

**Comment by girishramnani** [comment] 2021-02-16 18:17
a huge blocker - when I am trying to add ports to a `nodejs` component generated using `--s2i` - I get this error
```
✗  no port is exposed by the component nodejs
```

**Comment by girishramnani** [comment] 2021-02-16 18:24
we have no json output for devfile based odo create?

```

girish@MacBook-Pro assss % odo create nodejs -o json
(base) girish@MacBook-Pro assss % ls
devfile.yaml

```
using current master branch

this is gonna break odo create --s2i conversion compatibility

**Comment by kadel** [comment] 2021-02-17 09:51
> a huge blocker - when I am trying to add ports to a `nodejs` component generated using `--s2i` - I get this error


Isn't this just because there are no `endpoints` in generated devfile?
If there are no endpoints than it is correct that `odo url create` errors out. But `odo url create --port 8080` should work. 

For every port in `LocalConfig` there should be `endpoint` in the devfile. 

> we have no json output for devfile based odo create?

We will have to add json output.



> also `--git` will no longer be supported as devfile doesn't support that

Theoretically, this could be implemented. Devfile should have everything that we need for this. We would just have to start using `projects` section in Devfile, which odo currently ignores.

**Comment by girishramnani** [comment] 2021-02-17 09:57
> If there are no endpoints than it is correct that `odo url create` errors out. But `odo url create --port 8080` should work.

It works, actually —url in odo create isn’t being respected by the converter

**Comment by girishramnani** [comment] 2021-03-02 13:25
These 3 bugs/pre-req founds so far

- Already have a PR open for json output for `odo create`
- [ ] `no ports given` for converted nodejs components need to be fixed
- [ ] bypass conversion of s2i to devfile when user provides `--git` as devfile doesn't support and we dont intend to right now ( maybe in the future )

**Comment by dharmit** [comment] 2021-03-25 10:34
Are we going to have `odo create --s2i --port` get converted into a devfile with #4518? Or is that scoped for other time?

**Comment by kadel** [comment] 2021-03-31 11:09
> Are we going to have `odo create --s2i --port` get converted into a devfile with #4518? Or is that scoped for other time?

it should be part of the initial work. Some components won't work without `--port support`

**Comment by girishramnani** [comment] 2021-04-07 10:02
its supported now @dharmit

**Comment by girishramnani** [comment] 2021-04-07 10:05
Currently a converted s2i component would already have a url defined even if the original s2i component didn't have one, this was done to keep the behavior consistent between s2i and devfile cmps, as a new devfile component creates the url without a user doing "odo url create"

**Comment by girishramnani** [comment] 2021-04-14 14:07
removing all duplicate tests that are present in devfile and s2i both - Criteria of removal is to exactly match the title of the test and instructions in the tests

Current situation - 10 integration tests failing, 12 e2e tests failing.
Fixed 5 today, more underday.

**Comment by girishramnani** [comment] 2021-04-14 15:05
Currently I cannot debug e2e tests because they are timing out on prow.

**Comment by girishramnani** [comment] 2021-04-15 12:56
Fixed all the tests but gingko is timing out, I tried to reproduce this timeout but it didn’t happen so thinking about other ways to fix this

**Comment by girishramnani** [comment] 2021-04-15 21:11
Some questions asked so far
https://github.com/openshift/odo/pull/4518#issuecomment-820731449

**Comment by girishramnani** [comment] 2021-04-20 18:10
Need to add help and update docs

**Comment by girishramnani** [comment] 2021-04-21 10:53
But I went through the odo.dev docs, there are 20 pages of doc and nearly no mention of —s2i.

We need 2-3 paragraphs explaining —git, —binary and other 2 issues.

And the demo video needs to change.
Will share more of my findings

**Comment by girishramnani** [comment] 2021-04-29 09:47
Current plan -
I am writing a page in odo.dev titled “breaking changes in odo 2.2”
Explaining my —s2i change. I wasn’t sure where to document this so this seemed like the best option

**Comment by girishramnani** [comment] 2021-05-03 11:38
Docs https://github.com/openshift/odo/pull/4683

**Closed** 2021-05-04 09:39 UTC
Labels: kind/cleanup, points/2, priority/High
