### ISSUE TITLE
Deprecated project command "get" and "set" are still alive

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1961] opened 2019-07-30 05:29 UTC
[kind/bug]

## What versions of software are you using?
- Operating System: Supported
- Output of `odo version`: master

## How did you run odo exactly?
```
$ odo project -h
Perform project operations
Usage:
  odo project [options] [flags]
  odo project [command]
Examples:
  # Set the active project
  odo project set
  [...]
  # Get the active project
  odo project get
Available Commands:
  create      Create a new project
  delete      Delete a project
  get         Get the active project
  list        List all the projects
  set         Set the current active project
[...]
```
```
$ odo project list
ACTIVE     NAME
           myproject

# Command get the project name from the local config
$ odo project get
The current project is: test

$ odo project set test1
 ✗  The project test1 does not exist

$ odo project set myproject
Switched to project : myproject
```
## Actual behavior
get and set commands are still available. 

## Expected behavior
Should not visible in the UX and ofcourse if executed, these command should report error

**Comment by kadel** [comment] 2019-07-30 11:05
The decision on removing "get" and "set" was never made. 
It is being discussed in https://github.com/openshift/odo/issues/1720

Closing this as a duplicate of https://github.com/openshift/odo/issues/1720 and prevent fragmenting discussion.


/close

**Closed by kadel** 2019-07-30 11:05 UTC
Labels: kind/bug

**Comment by amitkrout** [comment] 2019-07-30 11:56
> The decision on removing "get" and "set" was never made.
> It is being discussed in #1720
> 
> Closing this as a duplicate of #1720 and prevent fragmenting discussion.
> 
> /close

@kadel Make sense. Thanks for the old issue reference.
