### ISSUE TITLE
output text for odo push seems to have duplicate messages

### ISSUE THREAD

**Issue by jankleinert** [openshift/odo#1648] opened 2019-04-24 20:26 UTC
[kind/bug]
Some of the output generated by odo push seems redundant. It would also be easier to skim if the different output messages used the same format.

## What versions of software are you using?
- Operating System: macOS
- Output of `odo version`: v1.0.0-beta1

## How did you run odo exactly?
Using this as your source code: https://github.com/openshift-labs/beercan-shooter-game.git
run:

odo create nodejs
odo url create --port 8080
odo push

## Actual behavior
The output from odo push looks like this:

✓  Checking component
 ✓  Checking component version
 ✓  Creating nodejs component with name nodejs-tgfc
 ✓  Initializing 'nodejs-tgfc' component
 ✓  Creating component nodejs-tgfc
 ✓  Successfully created component nodejs-tgfc
 ✓  Applying component settings to component: nodejs-tgfc
 ✓  Checking URL nodejs-tgfc-8080
 ✓  Successfully created URL for component: nodejs-tgfc
 ✓  http://nodejs-tgfc-8080-app-odo-odo-lab-53wy0.apps.jkleinert-e293.openshiftworkshop.com
 ✓  The component nodejs-tgfc was updated successfully
 ✓  Successfully updated component with name: nodejs-tgfc
 ✓  Pushing changes to component: nodejs-tgfc of type local
 ✓  Waiting for component to start
 ✓  Copying files to component
 ✓  Building component
 ✓  Changes successfully pushed to component: nodejs-tgfc

As a user who doesn't have a ton of insight into what exactly odo is doing during a push, I don't see how "Creating nodejs component with name nodejs-tgfc" and "Creating component nodejs-tgfc" are different, so they appear to be telling me the same thing twice. If both messages are printed because they are two different steps in the process and either one could fail, could we make the messages a bit more clear as to what's happening?

Similarly, what's the difference between "The component nodejs-tgfc was updated successfully" and "Successfully updated component with name: nodejs-tgfc"

This next part is stylistic, and just my opinion, but I feel that the messages would be clearer and easier to skim if they used similar formatting.

For example, the messages currently use 4 different formats when logging the component name:
1. "component: nodejs-tgfc"
2.  "component nodejs-tgfc"
3. " component with name nodejs-tgfc"
4.  "'nodejs-tgfc' component"

**Comment by kadel** [comment] 2019-04-25 06:01
Agreed, we need to clean that up.

How about something like that.
Each item will be a spinner, and once the operation is successful it will turn into a checkmark.

How about something like this?
```
✓ Checking nodejs component
✓ Creating nodejs component with name nodejs-tgfc
✓ Creating URL
✓ http://nodejs-tgfc-8080-app-odo-odo-lab-53wy0.apps.jkleinert-e293.openshiftworkshop.com
✓ Waiting for component to start
✓ Copying files to component
✓ Building component
✓ Changes successfully pushed to component
```

Those are steps that can take a few seconds, it is nice to inform the user what is happening.
We can remove even more messages, it depends on what info will be useful for users.

**Comment by jankleinert** [comment] 2019-04-25 13:29
@kadel I think messages like you listed above would be more clear and informative to the user. 

Along the same lines, I think we could improve the messages from the component create command to help the user understand what's actually happened. Right now it just says:
```
odo create nodejs
 ✓  Checking component
 ✓  Checking component version
Please use `odo push` command to create the component with source deployed.
```

As a user, I don't really know what that means, and it sounds like all odo has done is checked a couple things. If that step is creating a configuration for the component (or whatever the actual, correct description is of what's happening), could we include that as one of the messages, upon successful completion of that part of the command? Let me know if you'd like me to raise a separate issue for the `odo create` message

**Comment by jorgemoralespou** [comment] 2019-04-25 16:29
@kadel What does "checking component" mean? 
As a user I would like to understand better what's going on, which I'm guessing is validating the configuration.

I would also change the URL to the end.

```
✓ Validating component configuration
✓ Creating nodejs component with name nodejs-tgfc
✓ Creating URL
✓ Waiting for component to start
✓ Copying files to component
✓ Building component
✓ Changes successfully pushed to component
You can now access your component at: http://nodejs-tgfc-8080-app-odo-odo-lab-53wy0.apps.jkleinert-e293.openshiftworkshop.com
```

If there's no URL, don't print that message.

**Comment by kadel** [comment] 2019-04-26 09:15
> @kadel What does "checking component" mean?

it is checking if the builder image is present in the cluster.
`odo component create java:7` will check if there is a builder image (image stream) called `java` with tag `7` in `openshift` project in the current project.




> I would also change the URL to the end.

👍 you are right, that looks better

**Comment by cdrage** [comment] 2019-05-28 16:09
I'll take this up :+1:

**Comment by cdrage** [comment] 2019-05-28 18:49
So I've opened up PR #1774  that improves the output.

The problem is that we always do "ApplyConfig" before Build or Pushing the component and thus the URL changes need to happen **before** the build / copying files over process.

I've come up with the following output / solution:

[![asciicast](https://asciinema.org/a/Szh9pBMWL5Rbg4gGVC0MvLHdi.svg)](https://asciinema.org/a/Szh9pBMWL5Rbg4gGVC0MvLHdi)

Which works out to be a bit cleaner output wise!

Let me know what you all think @girishramnani @jankleinert @kadel

**Comment by kadel** [comment] 2019-05-29 10:11
@cdrage 
The long delay after 
```
✓  Checking component version
```
Looks weird, it feels like it got stuck :-/

I think that we don't need both `Checking component` and `Checking component version`, just `Checking component` that is displayed while both checks are done would be enough.

**Comment by cdrage** [comment] 2019-05-29 12:52
@kadel Yeah, I opened up a separate issue here: https://github.com/openshift/odo/issues/1775 as the above "Checking component version" is unrelated.

What do you think of the layout?

**Comment by kadel** [comment] 2019-05-29 12:57
The output that you have there is great. I would just group
```
✓  Checking component                                                          
✓  Checking component version  
```
Into something like
```
✓  Validating component configuration
```

**Comment by jorgemoralespou** [comment] 2019-05-31 21:08
@cdrage looking at your screencast it seems the component needs to be build when your just creating a url.
We need to provide a mechanism to detect if source code has changed, probably in another issue if it didn't exist.
I also agree with @kadel that the time between messages which should be really fast seems as something is stuck.

**Comment by danielhelfand** [comment] 2019-06-04 16:32
Something that I have noticed that may be related to this is that running `odo url create` after an initial push results in the following:

```
 ✓  Checking component
 ✓  Checking component version
 ◑  Applying component settings to component: frontend ✓  Checking URL frontend
 ◒  Applying component settings to component: frontend ✓  Successfully created URL for component: frontend
 ✓  http://frontend-app-odo.192.168.64.2.nip.io
 ✓  Applying component settings to component: frontend
 ✓  Successfully updated component with name: frontend
 ✓  Pushing changes to component: frontend of type local
 ✓  Waiting for component to start
 ✓  Copying files to component
 ✓  Building component
 ✓  Changes successfully pushed to component: frontend
```

So the  `◑  Applying component settings to component: frontend` spinner never converts to a  ✓ and it also gets stuck on the same line as `✓  Checking URL frontend` and `✓  Successfully created URL for component: frontend`.

To reproduce this, run:

`odo create nodejs frontend`
`odo push`
`odo url create frontend --port 8080`
`odo push`

**Comment by cdrage** [comment] 2019-06-04 19:02
@jorgemoralespou That is something we need to implement that would be outside of the scope of these changes.

I've opened up the issue here: https://github.com/openshift/odo/issues/1788

**Comment by cdrage** [comment] 2019-06-04 19:03
@danielhelfand That's also fixed in PR: https://github.com/openshift/odo/pull/1774

**Closed** 2019-06-06 17:12 UTC
Labels: kind/bug
