### ISSUE TITLE
Add wait command for deleting service

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#2077] opened 2019-09-03 18:36 UTC
[kind/Feature]

## Which functionality do you think we should add?

Currently we use:

```sh
oc wait ServiceInstance/${service} --for delete --namespace ${project}
```

Within VSCode.

We should also have a `--wait` command for deleting a service within odo.

## Why is this needed?

Needed so that the CLI will correctly "hang" until it's completely deleted.

**Comment by girishramnani** [comment] 2019-12-26 09:39
seems like this is a duplicate of https://github.com/openshift/odo/issues/2077, closing this as its newer

**Closed by girishramnani** 2019-12-26 09:39 UTC
Labels: area/service, kind/feature, priority/Medium
