### ISSUE TITLE
Bugs with odo push

### ISSUE THREAD

**Issue by anmolbabu** [openshift/odo#1510] opened 2019-03-22 07:52 UTC
[kind/bug]

## What versions of software are you using?
- Operating System:
- Output of `odo version`:

## Actual behavior
1. odo push with multiple ports creates only 1 service
2. odo push with ignore isn't working as expected

**Comment by amitkrout** [comment] 2019-03-22 11:22
Can please provide the steps to reproduce it

**Comment by anmolbabu** [comment] 2019-03-29 06:20
Part 1:

* `odo create nodejs` from within the component source
* `odo config set Ports 8080/TCP,9090/TCP`
* `odo push`

Part 2:
* `odo create nodejs`
* Set .git, tests etc.. in odoignore
* `odo push`
* Verify that the files in .odoignore are not pushed to the component

**Comment by cdrage** [comment] 2019-03-29 16:14
@anmolbabu 

I'm confused on Part 1:

Ports 8080 and 9090 open absolutely fine... see below:

```sh
~/nodejs-ex  master ✗                                                                                                                                                                                                                                                                                                                                             164d ⚑ ◒  
▶ cat .odo/config.yaml 
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: nodejs
  SourceLocation: /home/wikus/nodejs-ex
  SourceType: local
  Application: odo-dtgi
  Project: foobar
  Name: nodejs-ex-nodejs-hfja

~/nodejs-ex  master ✗                                                                                                                                                                                                                                                                                                                                             164d ⚑ ◒  
▶ odo config set Ports 8080/TCP,9090/TCP
Local config was successfully updated.

~/nodejs-ex  master ✗                                                                                                                                                                                                                                                                                                                                             164d ⚑ ◒  
▶ odo push
 ✓  Checking component
 ✓  Checking component version
 ✓  Creating nodejs component with name nodejs-ex-nodejs-hfja
 ✓  Initializing 'nodejs-ex-nodejs-hfja' component
 ✓  Creating component nodejs-ex-nodejs-hfja
 ✓  Successfully created component nodejs-ex-nodejs-hfja
 ✓  Pushing changes to component: nodejs-ex-nodejs-hfja of type local
 ✓  Waiting for component to start
 ✓  Copying files to component
 ✓  Building component
 ✓  Changes successfully pushed to component: nodejs-ex-nodejs-hfja

~/nodejs-ex  master ✗                                                                                                                                                      164d ⚑ ◒  
▶ oc get svc
NAME                                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
java-jgvu-wikus-kcwl                   ClusterIP   172.30.209.178   <none>        8778/TCP,8080/TCP,8443/TCP   22h
nodejs-ex-nodejs-aqex-odo-dtgi         ClusterIP   172.30.213.45    <none>        8080/TCP                     22h
nodejs-ex-nodejs-bjpn-odo-dtgi         ClusterIP   172.30.17.244    <none>        8080/TCP                     3d
nodejs-ex-nodejs-hfja-odo-dtgi         ClusterIP   172.30.18.39     <none>        8080/TCP,9090/TCP            3m
nodejs-ex-nodejs-jmcj-odo-dtgi         ClusterIP   172.30.252.173   <none>        8080/TCP                     6d
nodejs-ex-nodejs-ncvp-downloads-rhoo   ClusterIP   172.30.80.247    <none>        8080/TCP,9090/TCP            5s
nodejs-ex-nodejs-rhly-odo-dtgi         ClusterIP   172.30.139.70    <none>        8080/TCP                     6d
```
`nodejs-ex-nodejs-hfja-odo-dtgi` is the one built on the most current master branch...

`nodejs-ex-nodejs-ncvp-downloads-rhoo` was built from the last release.

Both open ports 9090 and 8080 correctly? Isn't creating just 1 service correct?

**Comment by cdrage** [comment] 2019-03-29 16:20
Part 2 I'm also unable to reproduce / encounter the error:

In `.gitignore` I ignore the file "foobar", see the below output from when I do `odo push -v 5`:

```sh
I0329 12:18:07.727925   21236 component.go:610] Copying files  to pod                                                                                                                 
I0329 12:18:07.728155   21236 occlient.go:2798] makeTar arguments: srcPath: /home/wikus/nodejs-ex, destPath: /tmp/src/nodejs-ex, files: []
I0329 12:18:07.728190   21236 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex, destBase: /tmp/src, destFile: nodejs-ex                             
I0329 12:18:07.728501   21236 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/.git, destBase: /tmp/src, destFile: nodejs-ex/.git              
I0329 12:18:07.728575   21236 util.go:535] ignoring path /home/wikus/nodejs-ex/.git because of glob rule /home/wikus/nodejs-ex/.git                                                                    
I0329 12:18:07.728598   21236 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/.gitignore, destBase: /tmp/src, destFile: nodejs-ex/.gitignore                      
I0329 12:18:08.132805   21236 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/.odo, destBase: /tmp/src, destFile: nodejs-ex/.odo                                                      
I0329 12:18:08.133058   21236 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/.odo/config.yaml, destBase: /tmp/src, destFile: nodejs-ex/.odo/config.yaml                                            
I0329 12:18:08.133604   21236 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/README.md, destBase: /tmp/src, destFile: nodejs-ex/README.md                                                                    
I0329 12:18:08.134029   21236 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/foo, destBase: /tmp/src, destFile: nodejs-ex/foo                                                                      
I0329 12:18:08.134830   21236 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/foobar, destBase: /tmp/src, destFile: nodejs-ex/foobar                                                    
I0329 12:18:08.134934   21236 util.go:535] ignoring path /home/wikus/nodejs-ex/foobar because of glob rule /home/wikus/nodejs-ex/foobar   
```

Specifically: `I0329 12:18:08.134934   21236 util.go:535] ignoring path /home/wikus/nodejs-ex/foobar because of glob rule /home/wikus/nodejs-ex/foobar`

**Comment by anmolbabu** [comment] 2019-03-29 16:24
May be they were fixed in some intermediate commit in #1360 or some other PR essentially I faced issues with this sometime and hence raised this issue but feel free to close this issue if things are working as expected

**Comment by anmolbabu** [comment] 2019-03-29 16:24
But please also verify it for update scenario

**Comment by cdrage** [comment] 2019-03-29 16:31
@anmolbabu Confused regards to update scenario?

But yeah.. I'm unable to reproduce anything. Most likely was fixed with #1360 then!

**Comment by cdrage** [comment] 2019-03-29 18:11
Same for `.odoignore`:

```sh
I0329 12:27:10.064086   24334 component.go:610] Copying files  to pod
I0329 12:27:10.064221   24334 occlient.go:2798] makeTar arguments: srcPath: /home/wikus/nodejs-ex, destPath: /tmp/src/nodejs-ex, files: []
I0329 12:27:10.064236   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex, destBase: /tmp/src, destFile: nodejs-ex
I0329 12:27:10.064362   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/.git, destBase: /tmp/src, destFile: nodejs-ex/.git
I0329 12:27:10.064395   24334 util.go:535] ignoring path /home/wikus/nodejs-ex/.git because of glob rule /home/wikus/nodejs-ex/.git
I0329 12:27:10.064405   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/.gitignore, destBase: /tmp/src, destFile: nodejs-ex/.gitignore
I0329 12:27:10.450110   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/.odo, destBase: /tmp/src, destFile: nodejs-ex/.odo
I0329 12:27:10.450454   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/.odo/config.yaml, destBase: /tmp/src, destFile: nodejs-ex/.odo/config.yaml
I0329 12:27:10.450840   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/.odoignore, destBase: /tmp/src, destFile: nodejs-ex/.odoignore
I0329 12:27:10.451131   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/README.md, destBase: /tmp/src, destFile: nodejs-ex/README.md
I0329 12:27:10.451542   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/foo, destBase: /tmp/src, destFile: nodejs-ex/foo
I0329 12:27:10.451892   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/foobar, destBase: /tmp/src, destFile: nodejs-ex/foobar
I0329 12:27:10.452229   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/foobar2, destBase: /tmp/src, destFile: nodejs-ex/foobar2
I0329 12:27:10.452327   24334 util.go:535] ignoring path /home/wikus/nodejs-ex/foobar2 because of glob rule /home/wikus/nodejs-ex/foobar2
I0329 12:27:10.452364   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm, destBase: /tmp/src, destFile: nodejs-ex/helm
I0329 12:27:10.452501   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm/nodejs, destBase: /tmp/src, destFile: nodejs-ex/helm/nodejs
I0329 12:27:10.452634   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm/nodejs/Chart.yaml, destBase: /tmp/src, destFile: nodejs-ex/helm/nodejs/Chart.yaml
I0329 12:27:10.452905   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm/nodejs/templates, destBase: /tmp/src, destFile: nodejs-ex/helm/nodejs/templates
I0329 12:27:10.453175   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm/nodejs/templates/NOTES.txt, destBase: /tmp/src, destFile: nodejs-ex/helm/nodejs/templates/NOTES.txt
I0329 12:27:10.453592   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm/nodejs/templates/buildconfig.yaml, destBase: /tmp/src, destFile: nodejs-ex/helm/nodejs/templates/buildconfig.yaml
I0329 12:27:10.453973   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm/nodejs/templates/deploymentconfig.yaml, destBase: /tmp/src, destFile: nodejs-ex/helm/nodejs/templates/deploymentconfig.yaml
I0329 12:27:10.454476   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm/nodejs/templates/imagestream.yaml, destBase: /tmp/src, destFile: nodejs-ex/helm/nodejs/templates/imagestream.yaml
I0329 12:27:10.454848   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm/nodejs/templates/route.yaml, destBase: /tmp/src, destFile: nodejs-ex/helm/nodejs/templates/route.yaml
I0329 12:27:10.455229   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm/nodejs/templates/service.yaml, destBase: /tmp/src, destFile: nodejs-ex/helm/nodejs/templates/service.yaml
I0329 12:27:10.455582   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm/nodejs/values.yaml, destBase: /tmp/src, destFile: nodejs-ex/helm/nodejs/values.yaml
I0329 12:27:10.455941   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/openshift, destBase: /tmp/src, destFile: nodejs-ex/openshift
I0329 12:27:10.456099   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/openshift/pipeline, destBase: /tmp/src, destFile: nodejs-ex/openshift/pipeline
I0329 12:27:10.456228   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/openshift/pipeline/Jenkinsfile, destBase: /tmp/src, destFile: nodejs-ex/openshift/pipeline/Jenkinsfile
I0329 12:27:10.456545   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/openshift/pipeline/README.md, destBase: /tmp/src, destFile: nodejs-ex/openshift/pipeline/README.md
I0329 12:27:10.456899   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/openshift/templates, destBase: /tmp/src, destFile: nodejs-ex/openshift/templates
I0329 12:27:10.457059   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/openshift/templates/nodejs-mongodb-persistent.json, destBase: /tmp/src, destFile: nodejs-ex/openshift/templates/nodejs-mongodb-persistent.json
I0329 12:27:10.457359   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/openshift/templates/nodejs-mongodb.json, destBase: /tmp/src, destFile: nodejs-ex/openshift/templates/nodejs-mongodb.json
I0329 12:27:10.457760   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/openshift/templates/nodejs.json, destBase: /tmp/src, destFile: nodejs-ex/openshift/templates/nodejs.json
I0329 12:27:10.458009   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/package.json, destBase: /tmp/src, destFile: nodejs-ex/package.json
I0329 12:27:10.493784   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/server.js, destBase: /tmp/src, destFile: nodejs-ex/server.js
I0329 12:27:10.494265   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/tests, destBase: /tmp/src, destFile: nodejs-ex/tests
I0329 12:27:10.494444   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/tests/app_test.js, destBase: /tmp/src, destFile: nodejs-ex/tests/app_test.js
I0329 12:27:10.494830   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/views, destBase: /tmp/src, destFile: nodejs-ex/views
I0329 12:27:10.495046   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/views/index.html, destBase: /tmp/src, destFile: nodejs-ex/views/index.html
```

(see the line about foobar2, I have foobar2 in my `.odoignore` file...)

I'm unable to reproduce either issues.

I DID however encounter ONE bug. It looks like we're combining `.odoignore` and `.gitignore` even though a `.odoignore` exists. Is this normal behavior?

**Comment by anmolbabu** [comment] 2019-04-01 14:56
> Same for `.odoignore`:
> 
> ```shell
> I0329 12:27:10.064086   24334 component.go:610] Copying files  to pod
> I0329 12:27:10.064221   24334 occlient.go:2798] makeTar arguments: srcPath: /home/wikus/nodejs-ex, destPath: /tmp/src/nodejs-ex, files: []
> I0329 12:27:10.064236   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex, destBase: /tmp/src, destFile: nodejs-ex
> I0329 12:27:10.064362   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/.git, destBase: /tmp/src, destFile: nodejs-ex/.git
> I0329 12:27:10.064395   24334 util.go:535] ignoring path /home/wikus/nodejs-ex/.git because of glob rule /home/wikus/nodejs-ex/.git
> I0329 12:27:10.064405   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/.gitignore, destBase: /tmp/src, destFile: nodejs-ex/.gitignore
> I0329 12:27:10.450110   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/.odo, destBase: /tmp/src, destFile: nodejs-ex/.odo
> I0329 12:27:10.450454   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/.odo/config.yaml, destBase: /tmp/src, destFile: nodejs-ex/.odo/config.yaml
> I0329 12:27:10.450840   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/.odoignore, destBase: /tmp/src, destFile: nodejs-ex/.odoignore
> I0329 12:27:10.451131   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/README.md, destBase: /tmp/src, destFile: nodejs-ex/README.md
> I0329 12:27:10.451542   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/foo, destBase: /tmp/src, destFile: nodejs-ex/foo
> I0329 12:27:10.451892   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/foobar, destBase: /tmp/src, destFile: nodejs-ex/foobar
> I0329 12:27:10.452229   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/foobar2, destBase: /tmp/src, destFile: nodejs-ex/foobar2
> I0329 12:27:10.452327   24334 util.go:535] ignoring path /home/wikus/nodejs-ex/foobar2 because of glob rule /home/wikus/nodejs-ex/foobar2
> I0329 12:27:10.452364   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm, destBase: /tmp/src, destFile: nodejs-ex/helm
> I0329 12:27:10.452501   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm/nodejs, destBase: /tmp/src, destFile: nodejs-ex/helm/nodejs
> I0329 12:27:10.452634   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm/nodejs/Chart.yaml, destBase: /tmp/src, destFile: nodejs-ex/helm/nodejs/Chart.yaml
> I0329 12:27:10.452905   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm/nodejs/templates, destBase: /tmp/src, destFile: nodejs-ex/helm/nodejs/templates
> I0329 12:27:10.453175   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm/nodejs/templates/NOTES.txt, destBase: /tmp/src, destFile: nodejs-ex/helm/nodejs/templates/NOTES.txt
> I0329 12:27:10.453592   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm/nodejs/templates/buildconfig.yaml, destBase: /tmp/src, destFile: nodejs-ex/helm/nodejs/templates/buildconfig.yaml
> I0329 12:27:10.453973   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm/nodejs/templates/deploymentconfig.yaml, destBase: /tmp/src, destFile: nodejs-ex/helm/nodejs/templates/deploymentconfig.yaml
> I0329 12:27:10.454476   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm/nodejs/templates/imagestream.yaml, destBase: /tmp/src, destFile: nodejs-ex/helm/nodejs/templates/imagestream.yaml
> I0329 12:27:10.454848   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm/nodejs/templates/route.yaml, destBase: /tmp/src, destFile: nodejs-ex/helm/nodejs/templates/route.yaml
> I0329 12:27:10.455229   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm/nodejs/templates/service.yaml, destBase: /tmp/src, destFile: nodejs-ex/helm/nodejs/templates/service.yaml
> I0329 12:27:10.455582   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/helm/nodejs/values.yaml, destBase: /tmp/src, destFile: nodejs-ex/helm/nodejs/values.yaml
> I0329 12:27:10.455941   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/openshift, destBase: /tmp/src, destFile: nodejs-ex/openshift
> I0329 12:27:10.456099   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/openshift/pipeline, destBase: /tmp/src, destFile: nodejs-ex/openshift/pipeline
> I0329 12:27:10.456228   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/openshift/pipeline/Jenkinsfile, destBase: /tmp/src, destFile: nodejs-ex/openshift/pipeline/Jenkinsfile
> I0329 12:27:10.456545   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/openshift/pipeline/README.md, destBase: /tmp/src, destFile: nodejs-ex/openshift/pipeline/README.md
> I0329 12:27:10.456899   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/openshift/templates, destBase: /tmp/src, destFile: nodejs-ex/openshift/templates
> I0329 12:27:10.457059   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/openshift/templates/nodejs-mongodb-persistent.json, destBase: /tmp/src, destFile: nodejs-ex/openshift/templates/nodejs-mongodb-persistent.json
> I0329 12:27:10.457359   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/openshift/templates/nodejs-mongodb.json, destBase: /tmp/src, destFile: nodejs-ex/openshift/templates/nodejs-mongodb.json
> I0329 12:27:10.457760   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/openshift/templates/nodejs.json, destBase: /tmp/src, destFile: nodejs-ex/openshift/templates/nodejs.json
> I0329 12:27:10.458009   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/package.json, destBase: /tmp/src, destFile: nodejs-ex/package.json
> I0329 12:27:10.493784   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/server.js, destBase: /tmp/src, destFile: nodejs-ex/server.js
> I0329 12:27:10.494265   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/tests, destBase: /tmp/src, destFile: nodejs-ex/tests
> I0329 12:27:10.494444   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/tests/app_test.js, destBase: /tmp/src, destFile: nodejs-ex/tests/app_test.js
> I0329 12:27:10.494830   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/views, destBase: /tmp/src, destFile: nodejs-ex/views
> I0329 12:27:10.495046   24334 occlient.go:2863] recursiveTar arguments: srcBase: /home/wikus, srcFile: nodejs-ex/views/index.html, destBase: /tmp/src, destFile: nodejs-ex/views/index.html
> ```
> 
> (see the line about foobar2, I have foobar2 in my `.odoignore` file...)
> 
> I'm unable to reproduce either issues.
> 
> I DID however encounter ONE bug. It looks like we're combining `.odoignore` and `.gitignore` even though a `.odoignore` exists. Is this normal behavior?

I think @mik-dass can confirm this

**Comment by kadel** [comment] 2019-04-08 12:31
@kadel tests it!

**Comment by kadel** [comment] 2019-04-08 14:04
created component with two ports

```
▶ odo create java --port 8080 --port 8088
 ✓  Checking component
 ✓  Checking component version
Please use `odo push` command to create the component with source deployed

▶ odo push
 ✓  Checking component
 ✓  Checking component version
 ✓  Creating project hyycxtlhgj
 ✓  Successfully created project hyycxtlhgj
 ✓  Creating java component with name java-wygx
 ✓  Initializing 'java-wygx' component
 ✓  Creating component java-wygx
 ✓  Successfully created component java-wygx
 ✓  Pushing changes to component: java-wygx of type local
 ✓  Waiting for component to start
 ✓  Copying files to component
 ✓  Building component
 ✓  Changes successfully pushed to component: java-wygx

▶ oc get svc
NAME                         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
java-wygx-spring-boot-zhrc   ClusterIP   172.30.207.37   <none>        8080/TCP,8088/TCP   118s
```

odo correctly creates  one service with two ports


ignore seems to work correctly also:
```
▶ touch noignore

▶ touch ignorethis

▶ odo push --ignore ignorethis
 ✓  Checking component
 ✓  Checking component version
 ✓  Applying component settings to component: java-wygx
 ✓  The component java-wygx was updated successfully
 ✓  Successfully created component with name: java-wygx
 ✓  Pushing changes to component: java-wygx of type local
 ✓  Waiting for component to start
 ✓  Copying files to component
 ✓  Building component
 ✓  Changes successfully pushed to component: java-wygx

▶ oc exec java-wygx-spring-boot-zhrc-2-tb75h -i -t ls /opt/app-root/src-backup/src/
Jenkinsfile  README.md	 mvnw	   noignore  src
LICENSE      guide.adoc  mvnw.cmd  pom.xml   target
```

**Closed by kadel** 2019-04-08 14:04 UTC
Labels: new workflow, priority/High
