### ISSUE TITLE
Create Windows Chocolatey package

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4078] opened 2020-10-05 08:51 UTC
As a Windows user using Chocolatey I want to be able to easily install odo

https://chocolatey.org/

/area windows
/priority medium
/kind user-story

**Comment by girishramnani** [comment] 2020-10-05 09:08
this is duplicate of https://github.com/openshift/odo/issues/4042

**Closed by girishramnani** 2020-10-05 09:08 UTC
Labels: area/Windows
