### ISSUE TITLE
"odo catalog describe service" doesn't work outside a component directory

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2487] opened 2019-12-26 07:05 UTC
/kind bug

## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** `master`

## How did you run odo exactly?
```sh
$ odo catalog describe service mysql-persistent
 ✗  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component
```

## Actual behavior
odo didn't describe the service from outside a component directory

## Expected behavior
odo should describe the service because we're just fetching the info from Service Catalog. We're not querying a service running in the cluster.

**Comment by girishramnani** [comment] 2019-12-26 08:14
@dharmit I feel this should be area/catalog as the commands with `odo catalog *` come under that :slightly_smiling_face:

**Comment by dharmit** [comment] 2019-12-26 12:09
Ack. But the description for `area/service` label says that anything related to service catalog could belong to it. Anyway, `catalog` seems more appropriate here. Thanks for the tip.

**Comment by girishramnani** [comment] 2020-01-07 06:39
This is a duplicate of https://github.com/openshift/odo/issues/2111. Hence closing this issue as its more recent.

**Closed by girishramnani** 2020-01-07 06:39 UTC
Labels: area/catalog, kind/bug, points/2, state/Ready
