### ISSUE TITLE
`odo list --path` does not list devfile components in Experimental mode

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#3092] opened 2020-05-05 22:49 UTC
/kind bug

## What versions of software are you using?

**Operating System:**
Windows 10
**Output of `odo version`:**
1.2.0

## How did you run odo exactly?

I created maven component using 
`odo create maven --context ~/component/dir`

## Actual behavior

`odo list --path ~/component` returns empty list 

## Expected behavior

`odo list --path ~/component` returns list with one devfile component

## Any logs, error output, etc?
N/A

**Comment by girishramnani** [comment] 2020-05-11 08:02
duplicate of https://github.com/openshift/odo/issues/2835

**Comment by girishramnani** [comment] 2020-05-11 08:03
@dgolovin work is being done on this.

**Closed by girishramnani** 2020-05-11 08:02 UTC
Labels: kind/bug

**Comment by dgolovin** [comment] 2020-05-12 08:13
@girishramnani thanks, that would let to try it in vscode.
