### ISSUE TITLE
default registry not initialized when user already has a preference.yaml file

### ISSUE THREAD

**Issue by jeffmaury** [openshift/odo#3940] opened 2020-09-11 15:47 UTC
/kind bug

## What versions of software are you using?

**Operating System:**
Win10Pro

**Output of `odo version`:**
`odo v2.0.0-beta-1 (c19e1f390)`

## How did you run odo exactly?
`odo catalog list components`

## Actual behavior
No Devfile components reported

## Expected behavior
Devfile components should be reported.

## Any logs, error output, etc?

So if there is no `preference.yaml` file then one is created with the default one. But if it was already there (from 1.0), as it does not have a `RegistryList` field, then no registries are used.
I think the initialization should be done also if `preference.yaml` is there but only if it does not contain a `RegistryList` field.

Adding @dgolovin and @sbouchet for migration issues in VSCode and IntelliJ

**Comment by GeekArthur** [comment] 2020-09-11 16:27
We used to support the case where user already had `preference.yaml`. This is a migration issue after the `make the devfile to be the default deployment mechanism` PR (https://github.com/openshift/odo/pull/3705) gets merged 18 hours ago. The problem is here https://github.com/openshift/odo/pull/3705/files#diff-5f21db40ee2e66f00f206912f4dddc2fL231-L239, we shouldn't move that code block as it is used for `handle user has preference file but doesn't use dynamic registry before` as the comment said.

**Closed** 2020-09-15 07:11 UTC
Labels: kind/bug
