### ISSUE TITLE
skip `odo create` for existing devfiles

### ISSUE THREAD

**Issue by gorkem** [openshift/odo#3346] opened 2020-06-14 23:50 UTC
/kind feature

## Which functionality do you think we should add?
If a folder already has a devfile, odo should be able to skip the `odo create` and it should be possible to call `odo push` directly. 

## Why is this needed?

It reduces getting started with one command.

**Comment by kadel** [comment] 2020-07-10 12:26
duplicate of https://github.com/openshift/odo/issues/3144
Support for this was recently merged in  https://github.com/openshift/odo/pull/3254

/triage duplicate
/close

**Closed** 2020-07-10 12:26 UTC
Labels: kind/feature, triage/duplicate
