### ISSUE TITLE
odo watch should skip some steps

### ISSUE THREAD

**Issue by gorkem** [openshift/odo#3323] opened 2020-06-08 21:13 UTC
/kind bug

When I am using `odo watch` with `devfile`. I see that it  is going through the cycle of `Validation`,`Creating Kubernetes resources for component`, `Applying URL changes`. 
Since watch already knows which files are modified can we skip these steps. Although these items seems to be happening sub-seconds, everything counts. 

I also noticed that we seem to be deleting and recreating the ingress. Although it looks like a quick process in some clusters ingress refresh takes longer and we get a gateway error. 

## What versions of software are you using?
**Operating System:**
MacOS

**Output of `odo version`:**
odo v1.2.2 (53530e0e5)

**Comment by mik-dass** [comment] 2020-06-09 05:51
> I also noticed that we seem to be deleting and recreating the ingress. Although it looks like a quick process in some clusters ingress refresh takes longer and we get a gateway error.

Was it a secure ingress? For unsecured ones, I can't seem to reproduce it. But we have a issue for secure ingresses https://github.com/openshift/odo/issues/3304

**Comment by gorkem** [comment] 2020-06-09 15:01
I did not specify, whatever the default is. You can use any of the examples on https://github.com/gorkem/odo-devfile/ to reproduce but it does sounds like replicate of #3304.

**Comment by mik-dass** [comment] 2020-06-10 07:56
> https://github.com/gorkem/odo-devfile/ to reproduce

The link throws a 404 for me.

**Comment by mik-dass** [comment] 2020-06-11 12:58
I can't seem to reproduce the URL recreation (normal unsecured URLs) issue with the devfile https://github.com/gorkem/odo-devfile/blob/master/nodejs-example/devfile.yaml

```
[mrinaldas@localhost che-nodejs]$ odo push
Validation
 ✓  Validating the devfile [132574ns]

Creating Kubernetes resources for component nodejs
 ✓  Waiting for component to start [412ms]

Applying URL changes
 ✓  URL example: http://example.com created

Syncing to component nodejs
 ✓  Checking file changes for pushing [1ms]
 ✓  No file changes detected, skipping build. Use the '-f' flag to force the build.

Pushing devfile component nodejs
 ✓  Changes successfully pushed to component
[mrinaldas@localhost che-nodejs]$ odo push

Validation
 ✓  Validating the devfile [45265ns]

Creating Kubernetes resources for component nodejs
 ✓  Waiting for component to start [436ms]

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component nodejs
 ✓  Checking file changes for pushing [1ms]
 ✓  No file changes detected, skipping build. Use the '-f' flag to force the build.

Pushing devfile component nodejs
 ✓  Changes successfully pushed to component
```
Tested on both an openshift and a minikube cluster.

**Comment by gorkem** [comment] 2020-06-11 14:02
Can you do a `odo watch` and modify for instance the index.html? I noticed it on that flow

**Comment by mik-dass** [comment] 2020-06-15 17:09
> Can you do a odo watch and modify for instance the index.html? I noticed it on that flow

I was able to reproduce the error. It occurs when I create a URL of route kind and provide a host to it on a openshift cluster. It occurs with odo push too.
```
[mrinaldas@localhost che-nodejs]$ odo url create example --host com
 ✓  URL example created for component: nodejs

To apply the URL configuration changes, please use `odo push`
```
@gorkem Is this how you created the URL?
Created issue https://github.com/openshift/odo/issues/3354 to track it.

**Comment by gorkem** [comment] 2020-06-15 18:29
I used `odo url create --host api-crc-testing`

**Comment by mik-dass** [comment] 2020-06-16 04:31
> I used odo url create --host api-crc-testing

I am sure it's the same error as #3354. On a openshift cluster, the command will create a route instead of a ingress. The problem is that for openshift clusters, the host is auto detected. This causes the mismatch between the cluster and the config. We will fix it asap.

For creating a ingress on a openshift cluster, the flag `--ingress` needs to be used.

**Comment by girishramnani** [comment] 2020-07-02 23:14
@mik-dass can we close this issue then?

**Comment by mik-dass** [comment] 2020-07-03 06:37
> @mik-dass can we close this issue then?

No two issues were described in the description. One now has a seperate issue now https://github.com/openshift/odo/issues/3354. The other, whether to skip some steps during watch, is up for debate.

**Closed** 2021-01-23 12:49 UTC
Labels: kind/bug, kind/discussion, lifecycle/rotten, priority/Medium
