### ISSUE TITLE
Ingress in extensions/v1beta1 is depricated in 1.14+

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4592] opened 2021-04-07 08:25 UTC
on kubernetes v1.19.7

```
W0407 09:37:11.196372    9497 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
 ✓  URLs are synced with the cluster, no changes are required.
```

Odo should start creating `Ingres` in `networking.k8s.io` API group if it is available.

**Comment by mohammedzee1000** [comment] 2021-04-21 07:11
Beginning investigation into this

**Comment by mohammedzee1000** [comment] 2021-04-22 09:10
I think I figured out where the change needs to happen. But one thing I still have not found out is how to check if the cluster supports the new `networking.k8s.io/v1` ingress. Any ideas @kadel? One way i can think of is checking the Kubernetes version but I am not sure it will be a dependable way or not

**Comment by dharmit** [comment] 2021-04-22 09:30
The [Ingress documentation page](https://kubernetes.io/docs/concepts/services-networking/ingress/) says this at the top:
```
FEATURE STATE: Kubernetes v1.19 [stable]
```
I assume that it means that it's out of beta and available as stable feature since kubernetes v1.19.

Recent minikube and CRC versions are at least at kubernetes v1.19 AFAIK. Mapping it to OpenShift is made simpler by [this article on RH Customer Portal](https://access.redhat.com/solutions/4870701).

I'm not sure if it's 100% helpful response because it's still got some level of assumption to it.

**Comment by mohammedzee1000** [comment] 2021-04-22 09:47
So do we drop v1beta ingress entirely and not have detection  logic to use v1beta if n/w.k8s.io/v1/ingress does not exist or do we want to keep supporting v1beta ingress for a bit longer?

**Comment by mohammedzee1000** [comment] 2021-04-22 09:48
As far as supported of n and n-1 goes 4.7 and 4.6 map to 1.20 and 1.19 respectively

**Comment by mohammedzee1000** [comment] 2021-04-22 10:47
Also, from what I have researched, Ingress is available under networking/v1beta till 1.19 and moved into v1 in 1.19+
Currently, we are using k8s api 0.17.1 from what I can make out from go.mod (require and replace).

So for now, we can use networking.k8s.io/v1beta/ingress. If we want to use 1 from v1/ingress, we will have to bump version
But that brings its own complications

**Comment by mohammedzee1000** [comment] 2021-04-22 11:11
I feel the simplest solution, for now, would be to move to networking.k8s.io/v1beta1 ingress.
Of course we could also upgrade out client, but that will involve some fighting with go mod

**Comment by kadel** [comment] 2021-04-22 11:18
> I feel the simplest solution, for now, would be to move to networking.k8s.io/v1beta1 ingress.
> Of course we could also upgrade out client, but that will involve some fighting with go mod (at minimum)

The client will be upgraded as part of https://github.com/openshift/odo/pull/4648

We could detect what cluster supports. If it has `networking.k8s.io/v1` use it, if not check for `networking.k8s.io/v1beta` if not check for extensions/v1beta1

**Comment by mohammedzee1000** [comment] 2021-04-22 11:31
So what do we want to do now?
 1. Hold this issue until your pr goes in as you are already done fighting with go.mod
 2. Replicate your changes in my own pr and proceed further (investigation on how to detect what is available and what is not)
 3. Go with v1beta implementation for now and worry about v1 later

**Comment by mohammedzee1000** [comment] 2021-04-22 11:35
@kadel ^

**Comment by kadel** [comment] 2021-04-22 12:45
> So what do we want to do now?
> 
> 1. Hold this issue until your pr goes in as you are already done fighting with go.mod
> 2. Replicate your changes in my own pr / rebase on it and proceed further (investigation on how to detect what is available and what is not)
> 3. Go with v1beta implementation for now and worry about v1 later

Ingress in networking/v1beta is even in the current version that we already vendor. So you can start with that.

Detect what cluster supports. If it has networking.k8s.io/v1beta  use it if not check for extensions/v1beta1 and use that.
Once  #4648 is you can just extend that with networking/v1 in separate PR  or in add it into the one that you open, depending which one will be merged first

**Comment by dharmit** [comment] 2021-04-22 13:10
I'd forgotten to add this to Sprint 200.

**Comment by mohammedzee1000** [comment] 2021-06-11 05:53
The PR linked above is ready for review.It is the part one of tix for this issue and there will be a followup pr

**Comment by mohammedzee1000** [comment] 2021-06-14 13:44
What is completed in https://github.com/openshift/odo/pull/4661:

- [ ] Create generator for networking v1 ingress
- [ ] Create Union for networking v1 and extensions v1 ingress
- [ ] Add new client functions for creating, deleting, getting, and listing ingresses using union
- [ ] Update usages of list across the code
- [ ] Fixing tests as needed without modifying them too much

What is left:

- [ ] Update usage of creating, deleting and getting for ingresses to use new functions
- [ ] Cleanup old functions
- [ ] Update existing tests to use networking v1 ingress
- [ ] Add few cases for extensions v1 ingress

**Comment by sbouchet** [comment] 2021-06-16 06:43
Hi guys,

not sure it's the correct place but I ran into an issue with this deprecation message. It breaks the json output we use by adding the warning message in the output.
in odo 2.2.0, it's to present, so I consider it like a regression.

below the output for the same command used by our tooling with odo 2.2.0 and 2.2.1 on a Kubernetes 1.20.0 cluster

```
sbouchet$ /home/sbouchet/.odo/cache/2.2.1/odo list --app app --project stephane-bouchet-dev -o json
W0616 08:25:06.322612  735867 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
{
	"kind": "List",
	"apiVersion": "odo.dev/v1alpha1",
	"metadata": {},
	"s2iComponents": [],
	"devfileComponents": [
		{
			"kind": "Component",
			"apiVersion": "odo.dev/v1alpha1",
			"metadata": {
				"name": "nodejs",
				"namespace": "stephane-bouchet-dev",
				"creationTimestamp": null
			},
			"spec": {
				"app": "app",
				"type": "nodejs",
				"sourceType": "local",
				"url": [
					"http-3000"
				],
				"env": [
					{
						"name": "PROJECTS_ROOT",
						"value": "/project"
					},
					{
						"name": "PROJECT_SOURCE",
						"value": "/project"
					},
					{
						"name": "DEBUG_PORT",
						"value": "5858"
					}
				]
			},
			"status": {
				"state": "Pushed"
			}
		}
	]
}

sbouchet$ /home/sbouchet/.odo/cache/2.2.0/odo list --app app --project stephane-bouchet-dev -o json
{
	"kind": "List",
	"apiVersion": "odo.dev/v1alpha1",
	"metadata": {},
	"s2iComponents": [],
	"devfileComponents": [
		{
			"kind": "Component",
			"apiVersion": "odo.dev/v1alpha1",
			"metadata": {
				"name": "nodejs",
				"namespace": "stephane-bouchet-dev",
				"creationTimestamp": null
			},
			"spec": {
				"app": "app",
				"type": "nodejs",
				"sourceType": "local",
				"url": [
					"http-3000"
				],
				"env": [
					{
						"name": "PROJECTS_ROOT",
						"value": "/project"
					},
					{
						"name": "PROJECT_SOURCE",
						"value": "/project"
					},
					{
						"name": "DEBUG_PORT",
						"value": "5858"
					}
				]
			},
			"status": {
				"state": "Pushed"
			}
		}
	]
}
```

**Comment by mohammedzee1000** [comment] 2021-06-16 07:44
@sbouchet yep Fixing is in progress. Should hopefully get fixed in this sprint

**Comment by mohammedzee1000** [comment] 2021-06-16 07:47
Infact once the pr above goes in you should at least not see the error for listing

**Comment by mohammedzee1000** [comment] 2021-07-01 11:04
@sbouchet ^^ should get rid of remaining error messages:

```bash
> odo create nodejs
Devfile Object Validation
 ✓  Checking devfile existence [93840ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [159109ns]
Validation
 ✓  Validating if devfile name is correct [137914ns]

Please use `odo push` command to create the component with source deployed
> odo url create ingress-3001 --port 3001 --host com --protocol https --ingress --secure
 ✓  URL ingress-3001 created for component: nodejs-nodejs-ex-kfga

To apply the URL configuration changes, please use `odo push`
> odo url create ingress-3002 --port 3002 --host com --protocol http --ingress
 ✓  URL ingress-3002 created for component: nodejs-nodejs-ex-kfga

To apply the URL configuration changes, please use `odo push`
> odo url list
Found the following URLs for component nodejs-nodejs-ex-kfga
NAME             STATE          URL                          PORT     SECURE     KIND
http-3000        Not Pushed     <provided by cluster>        3000     false      route
ingress-3001     Not Pushed     https://ingress-3001.com     3001     true       ingress
ingress-3002     Not Pushed     http://ingress-3002.com      3002     false      ingress
There are local changes. Please run 'odo push'.
> odo push

Validation
 ✓  Validating the devfile [147584ns]

Creating Kubernetes resources for component nodejs-nodejs-ex-kfga
 ✓  Waiting for component to start [2s]
 ✓  Waiting for component to start [454ms]

Applying URL changes
 ✓  URL http-3000: http://http-3000-nodejs-nodejs-ex-kfga-uv.apps.testocp47.psiodo.net/ created
 ✓  URL ingress-3001: https://ingress-3001.com/ created
 ✓  URL ingress-3002: http://ingress-3002.com/ created

Syncing to component nodejs-nodejs-ex-kfga
 ✓  Checking files for pushing [10ms]
 ✓  Syncing files to the component [10s]

Executing devfile commands for component nodejs-nodejs-ex-kfga
 ✓  Waiting for component to start [460ms]
 ✓  Executing install command "npm install" [10s]
 ✓  Executing run command "npm start" [3s]

Pushing devfile component "nodejs-nodejs-ex-kfga"
 ✓  Changes successfully pushed to component
> odo url list
Found the following URLs for component nodejs-nodejs-ex-kfga
NAME             STATE      URL                                                                     PORT     SECURE     KIND
http-3000        Pushed     http://http-3000-nodejs-nodejs-ex-kfga-uv.apps.testocp47.psiodo.net     3000     false      route
ingress-3001     Pushed     https://ingress-3001.com                                                3001     true       ingress
ingress-3002     Pushed     http://ingress-3002.com                                                 3002     false      ingress
> odo url delete ingress-3002
? Are you sure you want to delete the url ingress-3002 Yes
 ✓  URL ingress-3002 removed from component nodejs-nodejs-ex-kfga
> odo url list
Found the following URLs for component nodejs-nodejs-ex-kfga
NAME             STATE               URL                                                                     PORT     SECURE     KIND
http-3000        Pushed              http://http-3000-nodejs-nodejs-ex-kfga-uv.apps.testocp47.psiodo.net     3000     false      route
ingress-3001     Pushed              https://ingress-3001.com                                                3001     true       ingress
ingress-3002     Locally Deleted     http://ingress-3002.com                                                 3002     false      ingress
There are local changes. Please run 'odo push'.
> odo push
 ✓  Waiting for component to start [539ms]

Validation
 ✓  Validating the devfile [170418ns]

Creating Kubernetes resources for component nodejs-nodejs-ex-kfga
 ✓  Waiting for component to start [13s]
 ✓  Waiting for component to start [409ms]

Applying URL changes
 ✓  URL ingress-3002 successfully deleted

Syncing to component nodejs-nodejs-ex-kfga
 ✓  Checking file changes for pushing [3ms]
 ✓  Syncing files to the component [14s]

Executing devfile commands for component nodejs-nodejs-ex-kfga
 ✓  Waiting for component to start [505ms]
 ✓  Executing install command "npm install" [12s]
 ✓  Executing run command "npm start" [4s]

Pushing devfile component "nodejs-nodejs-ex-kfga"
 ✓  Changes successfully pushed to component
> odo url list
Found the following URLs for component nodejs-nodejs-ex-kfga
NAME             STATE      URL                                                                     PORT     SECURE     KIND
http-3000        Pushed     http://http-3000-nodejs-nodejs-ex-kfga-uv.apps.testocp47.psiodo.net     3000     false      route
ingress-3001     Pushed     https://ingress-3001.com                                                3001     true       ingress
> odo version
odo v2.2.2 (8b135744e)

Server: https://api.testocp47.psiodo.net:6443
Kubernetes: v1.20.0+bafe72f
> time odo version
odo v2.2.2 (8b135744e)

Server: https://api.testocp47.psiodo.net:6443
Kubernetes: v1.20.0+bafe72f
odo version  0.22s user 0.04s system 9% cpu 2.749 total
> odo version -v 9
I0701 16:31:15.994282  113297 preference.go:220] The path for preference file is /home/mzee1000/.odo/preference.yaml
I0701 16:31:15.994436  113297 util.go:761] HTTPGetRequest: https://raw.githubusercontent.com/openshift/odo/master/build/VERSION
I0701 16:31:15.994606  113297 util.go:782] Response will be cached in /tmp/odohttpcache for 1h0m0s
I0701 16:31:15.995124  113297 util.go:795] Cached response used.
I0701 16:31:16.003994  113297 preference.go:220] The path for preference file is /home/mzee1000/.odo/preference.yaml
I0701 16:31:16.004236  113297 occlient.go:337] Trying to connect to server api.testocp47.psiodo.net:6443
I0701 16:31:16.367498  113297 occlient.go:344] Server https://api.testocp47.psiodo.net:6443 is up
I0701 16:31:17.961146  113297 occlient.go:1202] Unable to get OpenShift Version - endpoint '/version/openshift' doesn't exist
odo v2.2.2 (8b135744e)

Server: https://api.testocp47.psiodo.net:6443
Kubernetes: v1.20.0+bafe72f
I0701 16:31:18.317514  113297 odo.go:75] Could not get the latest release information in time. Never mind, exiting gracefully :)

```

**Comment by mohammedzee1000** [comment] 2021-07-01 11:05
What you care about

```bash
> odo list
Devfile Components: 
APP     NAME                      PROJECT     TYPE       STATE
app     nodejs-nodejs-ex-kfga     uv          nodejs     Pushed

> odo list -o json
{
	"kind": "List",
	"apiVersion": "odo.dev/v1alpha1",
	"metadata": {},
	"s2iComponents": [],
	"devfileComponents": [
		{
			"kind": "Component",
			"apiVersion": "odo.dev/v1alpha1",
			"metadata": {
				"name": "nodejs-nodejs-ex-kfga",
				"namespace": "uv",
				"creationTimestamp": null
			},
			"spec": {
				"app": "app",
				"type": "nodejs",
				"sourceType": "local",
				"url": [
					"http-3000",
					"ingress-3001"
				],
				"env": [
					{
						"name": "PROJECTS_ROOT",
						"value": "/project"
					},
					{
						"name": "PROJECT_SOURCE",
						"value": "/project"
					},
					{
						"name": "DEBUG_PORT",
						"value": "5858"
					}
				]
			},
			"status": {
				"state": "Pushed"
			}
		}
	],
	"otherComponents": []
}

```

**Comment by sbouchet** [comment] 2021-07-01 12:49
@mohammedzee1000: it looks good!

**Closed** 2021-07-02 11:49 UTC
Labels: kind/task, milestone/2.3, points/8, priority/High
