### ISSUE TITLE
odo log  for devfile components

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2848] opened 2020-04-08 13:31 UTC
/kind user-story

## User Story
As a user, I want to see logs of a running application So that I can check if my application is running properly

## Acceptance Criteria 
- [ ] `odo log` command should show the stdout of the "devRun" process, similarly how it does for s2i based components

/kind user-story
/area devfile
/priority medium

**Comment by johnmcollier** [comment] 2020-04-08 17:16
Could we expand this to also retrieve the build logs from the `devBuild` process? When I was running through the end-end scenario today, there were a couple times I thought it'd be handy to have the build logs on hand 🙂

**Comment by maysunfaisal** [comment] 2020-04-08 18:49
yep, I think this would be really nice to have for both build and run commands tbh. I have stack creators ask me a couple of times how they could view their command outputs

**Comment by kadel** [comment] 2020-04-09 11:50
> Could we expand this to also retrieve the build logs from the `devBuild` process? When I was running through the end-end scenario today, there were a couple times I thought it'd be handy to have the build logs on hand 🙂
> 
> CC @maysunfaisal 


We used to always show build output, but it was really noisy and most people don't care about the output if the build was successful.

If the build process fails (at least with s2i components) it dumps stdout and stderr of the build process.
Or you can use `odo push --show-log` to always show build logs.

**Comment by jgwest** [comment] 2020-04-16 23:07
@johnmcollier  At least for the machine readable case (eg Odo called by IDEs, projects like Codewind turbine container, etc) the build log output would be covered by the work described on https://github.com/openshift/odo/issues/2550 via a command like `odo push -o=json` (referred to as `odo push --events` in the comments  on 2550)

**Comment by girishramnani** [comment] 2020-06-04 13:44
this is duplicate of https://github.com/openshift/odo/issues/3260 hence closing

**Closed by girishramnani** 2020-06-04 13:44 UTC
Labels: area/devfile, area/devfileV2, kind/user-story, priority/High, triage/needs-information
