### ISSUE TITLE
odo crash after storage deleted

### ISSUE THREAD

**Issue by jichenjc** [openshift/odo#2874] opened 2020-04-13 10:15 UTC
/kind bug

**Output of `odo version`:**

```
[root@xyimgr77 ftq]# ./odo version
odo v1.1.2 (df2590cec)

Server: https://api.ocp-test.redhat.com:6443
Kubernetes: v1.14.6+cd3a7d0

```

## How did you run odo exactly?

have 2 storage previously, and delete them successful
after that, push lead to crash and every command from then on will 
have error on `unable to get PVC mystor-app-pvc`
```
[root@xyimgr77 frontend]# ./odo storage delete mystor
? Are you sure you want to delete the storage mystor mounted to /opt/app-root/src/storage/ in nodejs-frontend-arbn component Yes
Deleted storage mystor from nodejs-frontend-arbn

Please use `odo push` command to delete the storage from the cluster
[root@xyimgr77 frontend]# ./odo storage delete mystor1
? Are you sure you want to delete the storage mystor1 mounted to /opt/app-root/src/ in nodejs-frontend-arbn component Yes
Deleted storage mystor1 from nodejs-frontend-arbn




./odo push
Validation
 ✓  Checking component [20ms]

Configuration changes
 ✓  Deleted storage mystor from nodejs-frontend-arbn
 ✓  Deleted storage mystor1 from nodejs-frontend-arbn
 ✓  Retrieving component data [35ms]
 ✗  Applying configuration [15ms]
panic: runtime error: slice bounds out of range [4:3]

goroutine 1 [running]:
github.com/openshift/odo/pkg/occlient.addOrRemoveVolumeAndVolumeMount(0xc00076cd20, 0xc0000cce00, 0xc000b026f0, 0xc000b02720, 0xc000b10ce0, 0x18)
        /root/go/src/github.com/openshift/odo/pkg/occlient/volumes.go:166 +0x6a8
github.com/openshift/odo/pkg/occlient.(*Client).PatchCurrentDC(0xc00076cd20, 0x0, 0x0, 0x0, 0x0, 0xc000b10ce0, 0x18, 0x0, 0x0, 0x0, ...)
        /root/go/src/github.com/openshift/odo/pkg/occlient/occlient.go:1371 +0x152
github.com/openshift/odo/pkg/occlient.(*Client).UpdateDCToSupervisor(0xc00076cd20, 0xc000b10ce0, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/src/github.com/openshift/odo/pkg/occlient/occlient.go:1630 +0x410
github.com/openshift/odo/pkg/component.Update(0xc00076cd20, 0xc0009fa040, 0x1f, 0x1ad9ca0, 0x2ab4278, 0xc0009eb270, 0xb, 0xc0009fa160, 0x19, 0xc0009e38f0, ...)
        /root/go/src/github.com/openshift/odo/pkg/component/component.go:1292 +0xc66
github.com/openshift/odo/pkg/component.ApplyConfig(0xc00076cd20, 0x0, 0xc0009fa040, 0x1f, 0x1ad9ca0, 0x2ab4278, 0xc0009eb270, 0xb, 0xc0009fa160, 0x19, ...)
        /root/go/src/github.com/openshift/odo/pkg/component/component.go:547 +0x228
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).createCmpIfNotExistsAndApplyCmpConfig(0xc000410ee0, 0x1a5d740, 0xc0000c4008, 0x100000000000013, 0x100000000000199)
        /root/go/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:128 +0x12e
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).Push(0xc000410ee0, 0x0, 0x0)
        /root/go/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:190 +0xc2
github.com/openshift/odo/pkg/odo/cli/component.(*PushOptions).Run(0xc0005fcc30, 0x0, 0x0)
        /root/go/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:136 +0x84
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x1a913a0, 0xc0005fcc30, 0xc00076bb00, 0x2ab4278, 0x0, 0x0)
        /root/go/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:31 +0x168
github.com/openshift/odo/pkg/odo/cli/component.NewCmdPush.func1(0xc00076bb00, 0x2ab4278, 0x0, 0x0)
        /root/go/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:152 +0x4e
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc00076bb00, 0x2ab4278, 0x0, 0x0, 0xc00076bb00, 0x2ab4278)
        /root/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702 +0x25c
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0008198c0, 0x18a4c88, 0xc0008d9080, 0x0)
        /root/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783 +0x28c
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main()
        /root/go/src/github.com/openshift/odo/cmd/odo/odo.go:75 +0x49c






[root@xyimgr77 frontend]# ./odo  component  list
 ✗  unable to get PVC mystor-app-pvc
[root@xyimgr77 frontend]#


# ./odo  component  list
 ✗  unable to get PVC mystor-app-pvc


```

**Comment by girishramnani** [comment] 2020-04-20 09:28
will be fixed by this PR https://github.com/openshift/odo/pull/2881

**Comment by girishramnani** [comment] 2020-04-20 09:28
Current issue is duplicate of https://github.com/openshift/odo/issues/2646

**Comment by girishramnani** [comment] 2020-05-11 14:05
this issue got resolved

**Closed by girishramnani** 2020-05-11 14:05 UTC
Labels: area/storage, kind/bug
