### ISSUE TITLE
Flaky Unit test on MacOS

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2588] opened 2020-02-10 16:26 UTC
Unit tests for watch.go sometimes fail with the following error:

```
E0206 11:44:38.778673    8045 watch.go:183] Failed getting details of the changed file /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis226431371/tests770224629/test_read_licenses.py758549112. Ignoring the change
E0206 11:44:38.780835    8045 watch.go:189] Ignoring event for file /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis226431371/tests770224629/test_read_licenses.py758549112 as details about the file couldn't be fetched
--- FAIL: TestWatchAndPush (11.26s)
    watch_test.go:690: Running test:  Case 1: Valid watch with list of files to be ignored with a append event
    watch_test.go:690: Running test:  Case 2: Valid watch with list of files to be ignored with a append and a delete event
    --- FAIL: TestWatchAndPush/Case_2:_Valid_watch_with_list_of_files_to_be_ignored_with_a_append_and_a_delete_event (1.01s)
        watch_test.go:714: Done with basePath creation and client init will trigger WatchAndPush and file modifications next...
            map[.git:{FilePath:.git293237548 FileParent:/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143 FileType:1 ModificationType:create} LICENSE:{FilePath:LICENSE685135003 FileParent:/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143 FileType:0 ModificationType:create} __init__.py:{FilePath:__init__.py163502398 FileParent:/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143 FileType:0 ModificationType:create} src:{FilePath:src129033322 FileParent:/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143 FileType:1 ModificationType:create} src/__init__.py:{FilePath:__init__.py988291973 FileParent:/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143/src129033322 FileType:0 ModificationType:create} src/main.py:{FilePath:main.py185418528 FileParent:/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143/src129033322 FileType:0 ModificationType:create} src/read_licenses.py:{FilePath:read_licenses.py376695433 FileParent:/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143/src129033322 FileType:0 ModificationType:create} tests:{FilePath:tests522703041 FileParent:/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143 FileType:1 ModificationType:create} tests/__init__.py:{FilePath:__init__.py734300159 FileParent:/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143/tests522703041 FileType:0 ModificationType:create} tests/test1.py:{FilePath:test1.py861969234 FileParent:/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143/tests522703041 FileType:0 ModificationType:create}]
        watch_test.go:763: Starting WatchAndPush now
        watch_test.go:717: Starting file simulations 
            [{FilePath:__init__.py FileParent: FileType:0 ModificationType:append} {FilePath:read_licenses.py FileParent:src FileType:0 ModificationType:delete} {FilePath:test_read_licenses.py FileParent:tests FileType:0 ModificationType:create} {FilePath:tests FileParent: FileType:1 ModificationType:delete}]
        watch_test.go:754: The CompDirStructure is 
            map[.git:{FilePath:.git293237548 FileParent:/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143 FileType:1 ModificationType:create} LICENSE:{FilePath:LICENSE685135003 FileParent:/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143 FileType:0 ModificationType:create} __init__.py:{FilePath:__init__.py163502398 FileParent:/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143 FileType:0 ModificationType:create} src:{FilePath:src129033322 FileParent:/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143 FileType:1 ModificationType:create} src/__init__.py:{FilePath:__init__.py988291973 FileParent:/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143/src129033322 FileType:0 ModificationType:create} src/main.py:{FilePath:main.py185418528 FileParent:/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143/src129033322 FileType:0 ModificationType:create} src/read_licenses.py:{FilePath:read_licenses.py376695433 FileParent:/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143/src129033322 FileType:0 ModificationType:create} tests:{FilePath:tests522703041 FileParent:/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143 FileType:1 ModificationType:create} tests/__init__.py:{FilePath:__init__.py734300159 FileParent:/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143/tests522703041 FileType:0 ModificationType:create} tests/test1.py:{FilePath:test1.py861969234 FileParent:/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143/tests522703041 FileType:0 ModificationType:create} tests/test_read_licenses.py:{FilePath:test_read_licenses.py207477332 FileParent:/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143/tests522703041 FileType:1 ModificationType:create}]
        watch_test.go:780: error in WatchAndPush error watching filesystem for changes: open /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/fabric8-analytics-license-analysis913313143/tests522703041: no such file or directory
    watch_test.go:690: Running test:  Case 3: Valid watch with list of files to be ignored with a create and a delete event
    watch_test.go:690: Running test:  Case 4: Valid watch with list of files to be ignored with a folder create event
    watch_test.go:690: Running test:  Case 5: Valid watch with list of files to be ignored with a folder delete event
FAIL
FAIL	github.com/openshift/odo/pkg/component	11.598s
```

/kind flake
/area testing
/priority high

**Comment by kadel** [comment] 2020-03-03 12:11
another flake https://travis-ci.com/openshift/odo/jobs/293045150

**Comment by kadel** [comment] 2020-03-26 09:03
Any updates on this? I still see it in almost every PR.

**Comment by girishramnani** [comment] 2020-03-30 13:38
duplicate of this issue https://github.com/openshift/odo/issues/2570

**Closed by girishramnani** 2020-03-30 13:38 UTC
Labels: area/testing, kind/flake, priority/High
