### ISSUE TITLE
odo catalog describe service broken

### ISSUE THREAD

**Issue by jeffmaury** [openshift/odo#5004] opened 2021-08-18 06:46 UTC
/kind bug

## What versions of software are you using?

**Operating System:** Win10Pro

**Output of `odo version`:**

```
odo v2.2.4 (f12e036b5)

Server: https://api.crc.testing:6443
Kubernetes: v1.20.0+df9c838
```

## How did you run odo exactly?

`odo catalog service describe myoperator`

## Actual behavior

` X  unable to search classes by name (clusterserviceclasses.servicecatalog.k8s.io is forbidden: User "developer" cannot list resource "clusterserviceclasses" in API group "servicecatalog.k8s.io" at the cluster scope)
`
## Expected behavior

operator should be described

**Comment by dharmit** [comment] 2021-08-18 07:15
> `X unable to search classes by name (clusterserviceclasses.servicecatalog.k8s.io is forbidden: User "developer" cannot list resource "clusterserviceclasses" in API group "servicecatalog.k8s.io" at the cluster scope)`

I can reproduce this on 2.2.4. However, I think #4906 would take care of it because it drops support for Service Catalog. Building odo from that PR works as below:
```bash
$ odo catalog list services                                    
Services available through Operators
NAME                                CRDs
etcdoperator.v0.9.4-clusterwide     EtcdCluster, EtcdBackup, EtcdRestore
redis-operator.v0.6.0               RedisCluster, Redis

$ odo catalog describe service myoperator                        
 ✗  no deployable operators found

$ odo catalog describe service etcdoperator.v0.9.4-clusterwide
 ✗  no deployable operators found

$ odo catalog describe service etcdoperator.v0.9.4-clusterwide/EtcdCluster
Kind: EtcdCluster
Version: v1beta2
Description: Represents a cluster of etcd nodes.
Parameters:

 PATH           DISPLAYNAME            DESCRIPTION                    

 size           Size                   The desired number of member   
                                       Pods for the etcd cluster.     
 pod.resources  Resource Requirements  Limits describes the           
                                       minimum/maximum amount         
                                       of compute resources           
                                       required/allowed               

```

Do you think this works as you would expect?

For below, we are tracking it in https://github.com/openshift/odo/issues/4786:
```shell
$ odo catalog describe service etcdoperator.v0.9.4-clusterwide
 ✗  no deployable operators found
```

**Comment by jeffmaury** [comment] 2021-08-18 07:18
Yes I just wanted to report it in case odo team missed it. Feel free to close

**Comment by dharmit** [comment] 2021-08-18 07:20
> Yes I just wanted to report it in case odo team missed it. Feel free to close

Thanks, Jeff! 👍🏾 

I'll update #4906 so that when it gets merged, this issue gets closed.

**Closed** 2021-08-18 11:41 UTC
Labels: kind/bug
