### ISSUE TITLE
`odo delete` is not deleting user created storage

### ISSUE THREAD

**Issue by adisky** [openshift/odo#2710] opened 2020-03-12 10:56 UTC
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

## How did you run odo exactly?
odo component has following storage.

```
$ odo describe 
Component Name: nodejs-mytest1-mhaz
Type: nodejs
Source: file://./
Environment Variables:
 · DEBUG_PORT=5858
Storage:
 · nodejs-mytest1-mhaz-csgq of size 1Gi mounted to /tmp1
```
When `odo delete` command is run, it gives message of deleting storage but it is not actually deleting it.
```
$ odo delete 
This component has following storages which will be deleted with the component
Storage nodejs-mytest1-mhaz-csgq of size 1Gi
? Are you sure you want to delete nodejs-mytest1-mhaz from app? Yes
 ✓  Deleting component nodejs-mytest1-mhaz [213ms]
 ✓  Component nodejs-mytest1-mhaz from application app has been deleted

$ oc get pvc nodejs-mytest1-mhaz-csgq-app-pvc
NAME                               STATUS   VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
nodejs-mytest1-mhaz-csgq-app-pvc   Bound    pv0013   100Gi      RWO,ROX,RWX                   3m35s

```

## Actual behavior
What should be the behavior of odo when `odo delete` command is run.  It should delete user created pvc along with or not?
I think Ideally user created persistent volume to have persisted data. so deleting along with component deletion is not right.

**option1:**  Delete user created storage with `odo delete`
1. This needs to be fixed as currently we are only showing message, not actually deleting the pvc.

**option2:** Do not Delete user created storage with `odo delete`
1. The message in `odo delete` needs to be updated.
2. behavior of `odo push` after `odo delete`? as it will give error `storage already exist` . Proceed for component creation and show storage exist error as message?
```
$ odo push
Validation
 ✓  Checking component [25ms]

Configuration changes
 ✗  Failed to create component with name nodejs-mytest1-mhaz. Please use `odo config view` to view settings used to create component. Error: unable to create PVC: unable to create PVC: persistentvolumeclaims "nodejs-mytest1-mhaz-csgq-app-pvc" already exists
```

**Comment by adisky** [comment] 2020-03-12 13:31
From the Integration tests[1] it is evident that we want to delete user pvc with `odo delete`
[1 ]https://github.com/openshift/odo/blob/master/tests/integration/component.go#L834.

The above tests is also missed to catch that pvc is not deleted
cc @girishramnani  as discussed on slack we should go with option2, I am not sure how to proceed for `odo push` after that.

**Comment by adisky** [comment] 2020-03-17 10:45
as discussed with @kadel we need to delete user created pvc with `odo delete` , as it was an input from odo users and to keep it simple..lets currently delete pvc with `odo delete`.

**Comment by girishramnani** [comment] 2020-03-17 10:47
You can add owner reference to the pvc and that should get deleted if dc is deleted

**Comment by dharmit** [comment] 2020-03-17 10:54
> You can add owner reference to the pvc and that should get deleted if dc is deleted

It's already there in PVC since we merged #2125.

**Comment by adisky** [comment] 2020-03-17 12:22
> > You can add owner reference to the pvc and that should get deleted if dc is deleted
> 
> It's already there in PVC since we merged #2125. Unless there's a bug in the code added via that PR.
No ownerReference being passed here :)
https://github.com/openshift/odo/blob/master/pkg/occlient/volumes.go#L16

**Comment by dharmit** [comment] 2020-03-17 13:15
Umm, are you looking at the right place? I see two calls to `CreatePVC` function in `occlient.go` file and they both have `ownerReference`.

1. https://github.com/openshift/odo/blob/e170ddee351452f1b208d66364c62900a6571d0c/pkg/occlient/occlient.go#L1199

2. https://github.com/openshift/odo/blob/e170ddee351452f1b208d66364c62900a6571d0c/pkg/occlient/occlient.go#L1576

**Comment by adisky** [comment] 2020-03-17 13:26
While `odo push` storage is created from here, and it is not passing `ownerRef`
https://github.com/openshift/odo/blob/2faf28420a64a238f1661560a01335c401cc32b6/pkg/storage/storage.go#L48

**Comment by mik-dass** [comment] 2020-03-24 05:36
I recently raised a PR which was supposed to update owner references for storage https://github.com/openshift/odo/pull/2533. The problem is in the function `updateStorageOwnerReference` where I updated the owner references to the outdated PVC instead of the latest one. I will send a fix asap.

/assign

**Comment by adisky** [comment] 2020-03-24 06:05
@mik-dass Thanks!!

**Closed** 2020-03-30 15:54 UTC
Labels: kind/bug
