### ISSUE TITLE
java component doesn't get rebuild after code change

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2476] opened 2019-12-18 12:35 UTC
```
odo component create java
odo url create
odo push
odo config set --env foo=bar
odo push
#edit java source code
odo push  -v 4
# check application
# changes in the source code are not there
```

In the verbose output of `odo push  -v 4` you can see the following lines:
```
+ exec /usr/local/s2i/assemble
INFO S2I source build with plain binaries detected
INFO Copying binaries from /tmp/src to /deployments ...
```

It looks like there is jar file  form the previous build in `/tmp/src` when s2i assemble script detects that . it just copies it to `/deployments` and then this executed instead of building new one.

/kind bug
/area component
/area s2i-java
/priority high

**Comment by mohammedzee1000** [comment] 2020-01-07 12:00
I think the easiest way to sort this to `rm -rf *.jar|war|ear` every time push happens. 

This could, of course, be expensive, in which case, maybe a config/env say for eg `ODO_JAVA_CLEAN` for example (maybe can think of a better name) which will be set to true or false depending on if we need a fresh build (for eg any change needs rebuild of sources should set `ODO_JAVA_CLEAN`). And then when we copy over the source, if true, we do what I suggested at first and then unset `ODO_JAVA_CLEAN`.

wdyt @kadel

**Comment by kadel** [comment] 2020-01-07 12:08
> I think the easiest way to sort this to `rm -rf *.jar|war|ear` every time push happens.

Wouldn't it be enough to do this just on the backup directory?

**Comment by mohammedzee1000** [comment] 2020-01-07 12:14
> > I think the easiest way to sort this to `rm -rf *.jar|war|ear` every time push happens.
> 
> Wouldn't it be enough to do this just on the backup directory?

Hmm, yea, I think that should work. We will need to do this either before the copy to backup happens or after the build completes, again from backup.

One thing though is are there any scenarios where we might want to keep built artifacts in backup as well. That is something I am looking at at the moment

**Comment by mohammedzee1000** [comment] 2020-01-07 13:10
I think the best action would be to `rm -rf *.jar|war|ear` whenever push source  is done ie 
- -f
- --source
- file changes detected

**Comment by mohammedzee1000** [comment] 2020-01-08 14:07
The problem related to a build failing could probably be handled by renaming the file instead of removing it. If the build fails (we do detect failure right) we put it back. If it succeeds, we can delete it

**Comment by mohammedzee1000** [comment] 2020-01-10 07:12
@kadel wdyt. I ran it by @hrishin and he said it should be doale. we only need to do this for jar/war/ear files

**Comment by mohammedzee1000** [comment] 2020-01-10 16:18
Here is what it could look like

```
❯ ls
f1.ear  f1.jar  f1.war  f2.ear  f2.jar  f2.war  f3.ear  f3.jar  f3.war  somerandomfile

❯ for file in `ls *.{jar,war,ear}`; do mv $file $file.bak;  done

❯ ls
f1.ear.bak  f1.jar.bak  f1.war.bak  f2.ear.bak  f2.jar.bak  f2.war.bak  f3.ear.bak  f3.jar.bak  f3.war.bak  somerandomfile

❯ for file in `ls *.{jar.bak,war.bak,ear.bak}`; do mv $file ${file%.bak};  done

❯ ls
f1.ear  f1.jar  f1.war  f2.ear  f2.jar  f2.war  f3.ear  f3.jar  f3.war  somerandomfile

```

**Comment by mohammedzee1000** [comment] 2020-02-06 13:22
I tried renaming artifact files such as jar, war, ear in https://github.com/mohammedzee1000/odo-supervisord-image/blob/java_cleanup_artifacts/language-scripts/java/dev-assemble but it still finds the necessary.  artifacts. I validated the command

**Comment by mohammedzee1000** [comment] 2020-03-09 13:14
Working on deeper research. I have been playing a bit with odo code to see if something needs to be done from there as well

**Comment by dev-gaur** [comment] 2020-06-17 17:16
I'm confused regarding this issue. I have been trying to reproduce this issue but I see non deterministic behaviour. I follow the same steps provided by @kadel  and majority of the time , rebuild is working for me and fails a few times.

**Comment by girishramnani** [comment] 2020-06-18 11:16
yes I think that would happen because sometimes java just decides to rebuild the class files sometimes it doesn't If I remember correctly.

**Comment by girishramnani** [comment] 2020-06-18 11:16
the ideal outcome should be that when the build is supposed to fail, it should fail.

**Comment by dev-gaur** [comment] 2020-06-18 12:17
After a discussion with @kadel , It seems like this issue got resolved somewhere accidentally. While trying to reproduce the issue, almost all of the times, the rebuild seems to work fine for me. @kadel also verified the same. Thus, closing this issue.

**Comment by girishramnani** [comment] 2020-06-18 12:23
Closing as per discussed

**Closed by girishramnani** 2020-06-18 12:23 UTC
Labels: area/component, area/s2i, kind/bug, priority/Medium, triage/needs-information
