### ISSUE TITLE
Component's "SourceLocation" is messed up when creating it in interactive mode

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2193] opened 2019-09-27 07:16 UTC
[kind/bug]

## What versions of software are you using?
- Operating System:
- Output of `odo version`: master

## How did you run odo exactly?
1. To circumvent #2192, I set the port using `odo config set ports 8080/TCP` before doing `odo push`. To create the component in interactive mode, I just chose the component name and version and hit "Return" key for everything else that `odo` chose for me by default.
2. Executed `odo push`. Here's `odo config view`, note the absolute path for `SourceLocatoin`
    ```sh
    $ odo config view
    COMPONENT SETTINGS
    ------------------------------------------------
    PARAMETER         CURRENT_VALUE
    Type              nodejs:latest
    Application       app
    Project           myproject
    SourceType        local
    Ref               
    SourceLocation    /home/dshah/src/nodejs-ex
    Ports             8080/TCP
    Name              nodejs-nodejs-ex-noqw
    MinMemory         
    MaxMemory         
    DebugPort         
    Ignore            
    MinCPU            
    MaxCPU

    $ pwd
    /home/dshah/src/nodejs-ex

    $ ls -a
    .  ..  .git  helm  .odo  openshift  tests  views  .gitignore  package.json  README.md  server.js
    ```

## Actual behavior
Not sure why it's trying to open the directory `/home/dshah/src/nodejs-ex/home/dshah/src/nodejs-ex`
```sh
$ odo push
Validation
 ✓  Checking component [13ms]

Configuration changes
 ✓  Initializing component
 ✓  Creating component [74ms]

Pushing to component nodejs-nodejs-ex-noqw of type local
 ✓  Checking files for pushing [762916ns]
 ✗  open /home/dshah/src/nodejs-ex/home/dshah/src/nodejs-ex: no such file or directory
```

## Expected behavior
odo should honour the `SourceLocation` that already seems proper in `odo config view` output.

**Comment by kadel** [comment] 2019-09-27 07:27
I think that this is duplicate of https://github.com/openshift/odo/issues/2163

**Closed** 2019-09-27 07:30 UTC
