### ISSUE TITLE
Kuberenetes tests failing

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4776] opened 2021-06-04 12:36 UTC
```
INFO[2021-06-04T06:48:16Z] [ssh:Fedora-32-minikube] ginkgo  -mod=vendor -randomizeAllSpecs -slowSpecThreshold=120 -timeout 14400s -nodes=1 -focus="odo project command tests" tests/integration/project/ 
INFO[2021-06-04T06:48:16Z] [ssh:Fedora-32-minikube] Failed to compile project: 
INFO[2021-06-04T06:48:16Z] [ssh:Fedora-32-minikube]                     
INFO[2021-06-04T06:48:16Z] [ssh:Fedora-32-minikube] go: inconsistent vendoring in /home/fedora/amqp_ci_rcv_odo-minikube-pr-build_PR_4769/repo: 
INFO[2021-06-04T06:48:16Z] [ssh:Fedora-32-minikube] 	github.com/devfile/library@v1.0.0-alpha.2: is explicitly required in go.mod, but vendor/modules.txt indicates github.com/devfile/library@v1.0.0-alpha.3.0.20210601183802-bd6996094a73 
INFO[2021-06-04T06:48:16Z] [ssh:Fedora-32-minikube] 	sigs.k8s.io/controller-runtime@v0.6.5: is explicitly required in go.mod, but vendor/modules.txt indicates sigs.k8s.io/controller-runtime@v0.7.0 
INFO[2021-06-04T06:48:16Z] [ssh:Fedora-32-minikube]                     
INFO[2021-06-04T06:48:16Z]                                      
```

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/4769/pull-ci-openshift-odo-main-psi-kubernetes-integration-e2e/1400704802039533568

in PR https://github.com/openshift/odo/pull/4769

It looks like something went wrong with VM

/kind testing
/priority high
/kind failing-test

**Comment by kadel** [comment] 2021-06-08 08:56
after cleaning go mod cache `go clean -modcache` it fails on 
```
[root@bfb4ae73fc20 odo]# make
verifying github.com/mikefarah/yaml/v2@v2.4.0/go.mod: checksum mismatch
	downloaded: h1:RDklbk79AGWmwhnvt/jBztapEOGDOx6ZbXqjP6csGnQ=
	go.sum:     h1:ahVqZF4n1W4NqwvVnZzC4es67xsW9uR/RRf2RRxieJU=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
go build -mod=vendor -ldflags="-X github.com/openshift/odo/pkg/version.GITCOMMIT=a54cfd86d" cmd/odo/odo.go
```

Interesting is that copy/pasting build command `go build -mod=vendor -ldflags="-X github.com/openshift/odo/pkg/version.GITCOMMIT=a54cfd86d" cmd/odo/odo.go` exectued by `make` makes it build sucesfully

**Comment by kadel** [comment] 2021-06-08 09:37
> Interesting is that copy/pasting build command `go build -mod=vendor -ldflags="-X github.com/openshift/odo/pkg/version.GITCOMMIT=a54cfd86d" cmd/odo/odo.go` exectued by `make` makes it build sucesfully

it looks like that for some reason when the command is executed using `make` it ignores `-mod=vendor` that's why it fails on checksum mismatch

**Comment by kadel** [comment] 2021-06-08 13:48
It was failing when something got changes in vendor.
The reason for failure was that `go list` in 
```
PKGS := $(shell go list  ./... | grep -v $(PROJECT)/vendor | grep -v $(PROJECT)/tests)
```
was not using `-mod=vedor`
the same for `ginkgo` commands


fix: https://github.com/openshift/odo/pull/4784

**Comment by prietyc123** [comment] 2021-06-10 06:40
We are still facing this issue on fedora machine https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/4754/pull-ci-openshift-odo-main-psi-kubernetes-integration-e2e/1402613266974248960#1:build-log.txt%3A174

**Comment by prietyc123** [comment] 2021-06-10 10:38
duplicate of issue https://github.com/openshift/odo/issues/4726

**Closed by prietyc123** 2021-06-10 10:38 UTC
Labels: area/testing, kind/failing-test, priority/High
