### ISSUE TITLE
unable to start or create Service for component with "odo push --build-command"

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#3639] opened 2020-07-24 09:55 UTC
/kind bug

## What versions of software are you using?

**Operating System:**
All supported

**Output of `odo version`:**
master

## How did you run odo exactly?

Running test on travis CI.

## Actual behavior

```
Running odo with args [odo preference set Experimental true]
[odo] I0724 07:25:04.478713    1559 preference.go:196] The path for preference file is /tmp/537875377/config.yaml
[odo] Global preference was successfully updated
[odo] I0724 07:25:04.479071    1559 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)
Setting KUBECONFIG=/tmp/537875377/config
Creating a new project: nbdkxklnsr
Running odo with args [odo project create nbdkxklnsr -w -v4]
[...]
Running odo with args [odo create java-openliberty dehkdp --project nbdkxklnsr]
[odo] Experimental mode is enabled, use at your own risk
[...]
Running odo with args [odo push --project nbdkxklnsr]
[odo] I0724 07:25:22.131092    1805 preference.go:196] The path for preference file is /tmp/537875377/config.yaml
[odo] I0724 07:25:22.131212    1805 context.go:69] absolute devfile path: '/tmp/537875377/devfile.yaml'
[...]
[odo]  ✓  Changes successfully pushed to component
Running odo with args [odo push --build-command devbuild -f --project nbdkxklnsr]
[odo] I0724 07:26:00.081421    3556 preference.go:196] The path for preference file is /tmp/537875377/config.yaml
[odo] I0724 07:26:00.082282    3556 context.go:69] absolute devfile path: '/tmp/537875377/devfile.yaml'
[odo] I0724 07:26:00.088271    3556 content.go:33] converted devfile YAML to JSON
[odo] I0724 07:26:00.088367    3556 apiVersion.go:50] devfile apiVersion: '2.0.0'
[odo] I0724 07:26:00.088402    3556 helper.go:35] devfile apiVersion '2.0.0' is supported in odo
[odo] I0724 07:26:00.094409    3556 schema.go:47] validated devfile schema
[odo] I0724 07:26:00.336537    3556 content.go:33] converted devfile YAML to JSON
[odo] I0724 07:26:00.336609    3556 apiVersion.go:50] devfile apiVersion: '2.0.0'
[odo] I0724 07:26:00.336626    3556 helper.go:35] devfile apiVersion '2.0.0' is supported in odo
[odo] I0724 07:26:00.343428    3556 schema.go:47] validated devfile schema
[odo] I0724 07:26:00.394435    3556 content.go:33] converted devfile YAML to JSON
[odo] I0724 07:26:00.394539    3556 apiVersion.go:50] devfile apiVersion: '2.0.0'
[odo] I0724 07:26:00.394556    3556 helper.go:35] devfile apiVersion '2.0.0' is supported in odo
[odo] I0724 07:26:00.399259    3556 schema.go:47] validated devfile schema
[odo] I0724 07:26:00.402781    3556 parse.go:83] overriding data of devfile with URI: https://raw.githubusercontent.com/odo-devfiles/registry/f56180b89556ee2945a355ac0dcf3428d3ab35c7/devfiles/java-openliberty/devfile.yaml
[odo] I0724 07:26:00.402998    3556 parse.go:106] adding data of devfile with URI: https://raw.githubusercontent.com/odo-devfiles/registry/f56180b89556ee2945a355ac0dcf3428d3ab35c7/devfiles/java-openliberty/devfile.yaml
[odo] I0724 07:26:00.403020    3556 parse.go:83] overriding data of devfile with URI: https://gist.githubusercontent.com/mik-dass/6f88d133b73e90bc52ffcda92833b625/raw/cc46d1ba348cd085855f163b269c0f1be87226c4/devfile-middle.yaml
[odo] I0724 07:26:00.403200    3556 parse.go:106] adding data of devfile with URI: https://gist.githubusercontent.com/mik-dass/6f88d133b73e90bc52ffcda92833b625/raw/cc46d1ba348cd085855f163b269c0f1be87226c4/devfile-middle.yaml
[odo] I0724 07:26:00.403219    3556 validate.go:32] Successfully validated devfile sections
[odo] I0724 07:26:00.403435    3556 preference.go:196] The path for preference file is /tmp/537875377/config.yaml
[odo] I0724 07:26:04.007138    3556 preference.go:196] The path for preference file is /tmp/537875377/config.yaml
[odo] I0724 07:26:04.007265    3556 preference.go:196] The path for preference file is /tmp/537875377/config.yaml
[odo] I0724 07:26:04.007333    3556 preference.go:196] The path for preference file is /tmp/537875377/config.yaml
[odo] I0724 07:26:04.007396    3556 context.go:69] absolute devfile path: '/tmp/537875377/devfile.yaml'
[odo] I0724 07:26:04.007621    3556 content.go:33] converted devfile YAML to JSON
[odo] I0724 07:26:04.007666    3556 apiVersion.go:50] devfile apiVersion: '2.0.0'
[odo] I0724 07:26:04.007673    3556 helper.go:35] devfile apiVersion '2.0.0' is supported in odo
[odo] I0724 07:26:04.011758    3556 schema.go:47] validated devfile schema
[odo] I0724 07:26:04.061397    3556 content.go:33] converted devfile YAML to JSON
[odo] I0724 07:26:04.061534    3556 apiVersion.go:50] devfile apiVersion: '2.0.0'
[odo] I0724 07:26:04.061596    3556 helper.go:35] devfile apiVersion '2.0.0' is supported in odo
[odo] I0724 07:26:04.094639    3556 schema.go:47] validated devfile schema
[odo] I0724 07:26:04.144820    3556 content.go:33] converted devfile YAML to JSON
[odo] I0724 07:26:04.144951    3556 apiVersion.go:50] devfile apiVersion: '2.0.0'
[odo] I0724 07:26:04.144997    3556 helper.go:35] devfile apiVersion '2.0.0' is supported in odo
[odo] I0724 07:26:04.149876    3556 schema.go:47] validated devfile schema
[odo] I0724 07:26:04.150045    3556 parse.go:83] overriding data of devfile with URI: https://raw.githubusercontent.com/odo-devfiles/registry/f56180b89556ee2945a355ac0dcf3428d3ab35c7/devfiles/java-openliberty/devfile.yaml
[odo] I0724 07:26:04.150227    3556 parse.go:106] adding data of devfile with URI: https://raw.githubusercontent.com/odo-devfiles/registry/f56180b89556ee2945a355ac0dcf3428d3ab35c7/devfiles/java-openliberty/devfile.yaml
[odo] I0724 07:26:04.150257    3556 parse.go:83] overriding data of devfile with URI: https://gist.githubusercontent.com/mik-dass/6f88d133b73e90bc52ffcda92833b625/raw/cc46d1ba348cd085855f163b269c0f1be87226c4/devfile-middle.yaml
[odo] I0724 07:26:04.150440    3556 parse.go:106] adding data of devfile with URI: https://gist.githubusercontent.com/mik-dass/6f88d133b73e90bc52ffcda92833b625/raw/cc46d1ba348cd085855f163b269c0f1be87226c4/devfile-middle.yaml
[odo] I0724 07:26:04.150476    3556 validate.go:32] Successfully validated devfile sections
[odo] I0724 07:26:04.150650    3556 preference.go:196] The path for preference file is /tmp/537875377/config.yaml
[odo] I0724 07:26:04.150734    3556 preference.go:196] The path for preference file is /tmp/537875377/config.yaml
[odo] I0724 07:26:04.152532    3556 preference.go:196] The path for preference file is /tmp/537875377/config.yaml
[odo] I0724 07:26:04.152695    3556 preference.go:196] The path for preference file is /tmp/537875377/config.yaml
[odo] I0724 07:26:12.020285    3556 pods.go:31] Waiting for component=dehkdp pod
[odo] I0724 07:26:13.516316    3556 pods.go:58] Status of dehkdp-8668c66c76-lfj92 pod is Running
[odo] I0724 07:26:13.516401    3556 pods.go:64] Pod dehkdp-8668c66c76-lfj92 is Running
[odo] 
[odo] Validation
[odo]  •  Validating the devfile  ...
[odo] I0724 07:26:13.516658    3556 command.go:65] the command group of kind "init" is not found in the devfile
[odo] I0724 07:26:13.516684    3556 command.go:258] No init command was provided
[odo] I0724 07:26:13.516720    3556 utils.go:98] Found component "Container" with name "appsodyrun"
[odo] I0724 07:26:13.516753    3556 command.go:275] Build command: devbuild
[odo] I0724 07:26:13.516766    3556 utils.go:98] Found component "Container" with name "appsodyrun"
[odo] I0724 07:26:13.516798    3556 command.go:282] Run command: devrun
 ✓  Validating the devfile [244218ns]
[odo] 
[odo] Creating Kubernetes resources for component dehkdp
[odo] I0724 07:26:13.516907    3556 utils.go:98] Found component "Container" with name "appsodyrun"
[odo] I0724 07:26:13.517144    3556 utils.go:98] Found component "Container" with name "appsodyrun"
[odo] I0724 07:26:13.517186    3556 command.go:65] the command group of kind "debug" is not found in the devfile
[odo] I0724 07:26:13.517201    3556 utils.go:270] Updating container appsodyrun entrypoint with supervisord
[odo] I0724 07:26:13.517239    3556 utils.go:149] Updating container appsodyrun with supervisord volume mounts
[odo] I0724 07:26:13.517263    3556 utils.go:159] Updating container appsodyrun env with run command
[odo] I0724 07:26:13.517280    3556 utils.go:177] Updating container appsodyrun env with run command's workdir
[odo] I0724 07:26:13.517310    3556 utils.go:98] Found component "Container" with name "appsodyrun"
[odo] I0724 07:26:13.517341    3556 utils.go:98] Found component "Container" with name "appsodyrun"
[odo] I0724 07:26:13.517365    3556 adapter.go:306] Creating deployment dehkdp
[odo] I0724 07:26:13.517400    3556 adapter.go:307] The component name is dehkdp
[odo] I0724 07:26:13.517423    3556 adapter.go:311] The component already exists, attempting to update it
[odo] I0724 07:26:23.216674    3556 adapter.go:316] Successfully updated component dehkdp



[odo]  ✗  Failed to start component with name dehkdp. Error: Failed to create the component: unable to create or 
update component: unable to create Service for dehkdp: Post 
https://127.0.0.1:8443/api/v1/namespaces/nbdkxklnsr/services: read tcp 127.0.0.1:44140->127.0.0.1:8443: read: 
connection reset by peer




Deleting project: nbdkxklnsr
Running odo with args [odo project delete nbdkxklnsr -f]
[odo]  ✗  The project nbdkxklnsr does not exist. Please check the list of projects using `odo project list`
• Failure [84.793 seconds]
odo devfile push command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:17
  Handle devfiles with parent
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:663
    should handle a multi layer parent [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:689
    No future change is possible.  Bailing out early after 28.693s.
    Running odo with args [odo push --build-command devbuild -f --project nbdkxklnsr]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
```

## Expected behavior

"odo push --build-command" should start the component during validation

**Comment by amitkrout** [comment] 2020-07-24 13:35
Similar failure - https://travis-ci.com/github/openshift/odo/jobs/364609348#L538

**Comment by prietyc123** [comment] 2020-07-24 16:31
I have observed similar failure occurring frequently on the prs.

One of the pr facing the same issue #3635 

```
[odo]  •  Waiting for component to start  ...
 ✓  Waiting for component to start [3s]
[odo] I0724 13:50:24.784500    5616 deployments.go:92] Deployment "wgyrhu" successfully rolled out
[odo] I0724 13:50:24.784515    5616 deployments.go:96] Waiting for deployment spec update to be observed...
[odo] I0724 13:50:24.784569    5616 pods.go:31] Waiting for component=wgyrhu pod
[odo] I0724 13:50:24.881494    5616 pods.go:58] Status of wgyrhu-74f894b7b6-zsr88 pod is Running
[odo] I0724 13:50:24.881519    5616 pods.go:64] Pod wgyrhu-74f894b7b6-zsr88 is Running
[odo] I0724 13:50:24.881586    5616 preference.go:196] The path for preference file is /tmp/873789133/config.yaml
[odo] I0724 13:50:25.149844    5616 url.go:402] Listing ingresses with label selector: app.kubernetes.io/instance=wgyrhu
[odo] I0724 13:50:26.415250    5616 url.go:379] Listing routes with label selector: app.kubernetes.io/part-of=,app.kubernetes.io/instance=wgyrhu
[odo] I0724 13:50:26.415284    5616 occlient.go:2653] Listing routes with label selector: app.kubernetes.io/part-of=,app.kubernetes.io/instance=wgyrhu
[odo]  ✗  Failed To Update Config To Component Deployed.
[odo] Error: unable to list route names: unable to get route list: Get https://127.0.0.1:8443/apis/route.openshift.io/v1/namespaces/kvbrvbyknb/routes?labelSelector=app.kubernetes.io%2Fpart-of%3D%2Capp.kubernetes.io%2Finstance%3Dwgyrhu: unexpected EOF
Deleting project: kvbrvbyknb
Running odo with args [odo project delete kvbrvbyknb -f]
[odo]  ✗  The project kvbrvbyknb does not exist. Please check the list of projects using `odo project list`
• Failure [114.763 seconds]
odo devfile push command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:17
  Handle devfiles with parent
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:685
    should handle a multi layer parent [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:711
    No future change is possible.  Bailing out early after 40.184s.
    Running odo with args [odo push --build-command devbuild -f --project kvbrvbyknb]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
```

**Comment by prietyc123** [comment] 2020-07-24 17:44
Not sure why everytime `--build-command` throwing error.

```
✓  Syncing files to the component [23s]
[odo] 
[odo] Executing devfile commands for component lbzila
[odo]  •  Executing firstbuild command "npm install"  ...
[odo] I0724 17:03:00.530396   23162 exec.go:27] Executing command [/bin/sh -c cd ${CHE_PROJECTS_ROOT}/nodejs-starter && npm install] for pod: lbzila-767764b4bc-rt62c in container: runtime
[odo] I0724 17:03:14.501962   23162 adapter.go:453] Executing devfile command singleenv
[odo] I0724 17:03:14.502044   23162 exec.go:27] Executing command [/opt/odo/bin/supervisord ctl stop all] for pod: lbzila-767764b4bc-rt62c in container: runtime
 ✓  Executing firstbuild command "npm install" [14s]
[odo]  •  Executing singleenv command "mkdir $ENV1"  ...
[odo]  ✗  Executing singleenv command "mkdir $ENV1" [521ms]
[odo]  ✗  
[odo] Unable to exec command [/opt/odo/bin/supervisord ctl stop all]: 
[odo] 
[odo]  ✗  Failed to start component with name lbzila. Error: Failed to create the component: unable to execute the run command: error while streaming command: error sending request: Post https://127.0.0.1:8443/api/v1/namespaces/jqasdveqmv/pods/lbzila-767764b4bc-rt62c/exec?command=%2Fopt%2Fodo%2Fbin%2Fsupervisord&command=ctl&command=stop&command=all&container=runtime&stderr=true&stdout=true: read tcp 127.0.0.1:50428->127.0.0.1:8443: read: connection reset by peer
Deleting project: jqasdveqmv
Running odo with args [odo project delete jqasdveqmv -f]
[odo]  ✗  The project jqasdveqmv does not exist. Please check the list of projects using `odo project list`
• Failure [59.825 seconds]
odo devfile push command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:17
  exec commands with environment variables
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:556
    Should be able to exec command with single environment variable [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:557
    No future change is possible.  Bailing out early after 55.657s.
    Running odo with args [odo push --build-command firstbuild --run-command singleenv --namespace jqasdveqmv --context /tmp/814552147]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
```
One more occurence in pr #3635

**Comment by kadel** [comment] 2020-07-27 10:59
Have you been able to reproduce this outside our CI environment?
All the error images look like network related

**Comment by amitkrout** [comment] 2020-07-28 06:12
Tried thrice and none of the time i hit the issue locally

**Comment by amitkrout** [comment] 2020-07-29 06:13
@kadel Recently most of our periodic and few pr test failing at same spec - https://github.com/openshift/odo/blob/master/tests/integration/devfile/cmd_devfile_push_test.go#L557. This time same spec hit with a different error in periodic job. 

```
✓  Syncing files to the component [1s]
[odo] 
[odo] Executing devfile commands for component tmwocz
[odo]  •  Executing devbuild command "touch blah.js"  ...
[odo] I0729 02:15:48.917034   13610 exec.go:27] Executing command [/bin/sh -c cd ${CHE_PROJECTS_ROOT}/nodejs-starter && touch blah.js] for pod: tmwocz-5945596784-k575v in container: runtime
[odo] /bin/sh: line 0: cd: /project/nodejs-starter: No such file or directory
[odo]  ✗  Executing devbuild command "touch blah.js" [617ms]
[odo]  ✗  
[odo] Unable to exec command [/bin/sh -c cd ${CHE_PROJECTS_ROOT}/nodejs-starter && touch blah.js]: 
[odo] /bin/sh: line 0: cd: /project/nodejs-starter: No such file or directory
[odo] 
[odo]  ✗  Failed to start component with name tmwocz. Error: Failed to create the component: unable to execute the build command: error while streaming command: command terminated with exit code 1
```

Details:
Periodic job - https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-odo-master-v4.5-integration-e2e-periodic/1288263134854778880#1:build-log.txt%3A1034
Pr job - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/3573/pull-ci-openshift-odo-master-v4.5-integration-e2e/1288284114700472320

**Comment by girishramnani** [comment] 2020-08-05 12:36
closing this issue as it seems to be network related

**Closed by girishramnani** 2020-08-05 12:36 UTC
Labels: area/devfile, kind/bug, kind/flake, priority/High
