### ISSUE TITLE
unable to push component created with beta3 version

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1910] opened 2019-07-15 14:31 UTC
```
▶ cat .odo/config.yaml
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: java
  SourceLocation: ./
  SourceType: local
  Application: app
  Project: myproject
  Name: java-pfio

▶ odo push
 ✓  Creating project myproject
 ✓  Successfully created project myproject
Validation
 ✓  Validating component [5s]
 ✓  Checking component [116ms]

Configuration changes
 ✓  Initializing component
 ◑  Creating component ✗  Failed to create component with name java-pfio. Please use `odo config view` to view settings used to create component. Error: Service "java-pfio-app" is invalid: spec.ports: Required value
unable to create Service for java-pfio-app
github.com/openshift/odo/pkg/occlient.(*Client).CreateService
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/occlient/occlient.go:1253
github.com/openshift/odo/pkg/occlient.(*Client).BootstrapSupervisoredS2I
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/occlient/occlient.go:1207
github.com/openshift/odo/pkg/component.CreateFromPath
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/component/component.go:251
github.com/openshift/odo/pkg/component.CreateComponent
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/component/component.go:412
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).createCmpIfNotExistsAndApplyCmpConfig
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:84
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).Push
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:153
github.com/openshift/odo/pkg/odo/cli/component.(*PushOptions).Run
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:102
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:17
github.com/openshift/odo/pkg/odo/cli/component.NewCmdPush.func1
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:116
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/cmd/odo/odo.go:65
runtime.main
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/proc.go:200
runtime.goexit
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/asm_amd64.s:1337
unable to create Service for java-pfio-app
github.com/openshift/odo/pkg/occlient.(*Client).BootstrapSupervisoredS2I
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/occlient/occlient.go:1209
github.com/openshift/odo/pkg/component.CreateFromPath
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/component/component.go:251
github.com/openshift/odo/pkg/component.CreateComponent
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/component/component.go:412
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).createCmpIfNotExistsAndApplyCmpConfig
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:84
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).Push
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:153
github.com/openshift/odo/pkg/odo/cli/component.(*PushOptions).Run
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:102
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:17
github.com/openshift/odo/pkg/odo/cli/component.NewCmdPush.func1
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:116
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/cmd/odo/odo.go:65
runtime.main
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/proc.go:200
runtime.goexit
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/asm_amd64.s:1337
failed to create component with args {Name:java-pfio SourcePath:./ SourceRef: SourceType:local ImageName:java EnvVars:[] Ports:[] Resources:&ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},} ApplicationName:app Wait:false StorageToBeMounted:map[] StdOut:<nil>}
github.com/openshift/odo/pkg/component.CreateComponent
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/component/component.go:413
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).createCmpIfNotExistsAndApplyCmpConfig
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:84
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).Push
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:153
github.com/openshift/odo/pkg/odo/cli/component.(*PushOptions).Run
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:102
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:17
github.com/openshift/odo/pkg/odo/cli/component.NewCmdPush.func1
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:116
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/cmd/odo/odo.go:65
runtime.main
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/proc.go:200
runtime.goexit
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/asm_amd64.s:1337

````

This is probably due to latest chnages in https://github.com/openshift/odo/pull/1828

ping @surajnarwade

**Comment by surajnarwade** [comment] 2019-07-16 03:17
@kadel , can you point me to example java repo ?
because it works with nodejs and php for me

**Comment by surajnarwade** [comment] 2019-07-16 03:27
@kadel , your `.odo/config.yaml` doesn't have `Ports` section, how come ?
it should error out at `odo create` itself if there's no ports

**Comment by amitkrout** [comment] 2019-07-16 07:42
@kadel I am not able to reproduce this.

Steps i followed:
```
$ oc --request-timeout 5m import-image java --namespace=myproject --from=registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.5 --confirm

$ oc annotate istag/java:latest --namespace=myproject tags=builder --overwrite

$ odo component create java
 ✓  Validating component [69ms]
Please use `odo push` command to create the component with source deployed

$ odo push
Validation
 ✓  Validating component [81ms]
 ✓  Checking component [3ms]

Configuration changes
 ✓  Initializing component
 ✓  Creating component [220ms]
 ✓  Applying configuration [0s]

Pushing to component java-uspf of type local
 ✓  Waiting for component to start [7s]
 ✓  Copying files to component [21s]
 ✓  Building component [1m27s]
 ✓  Changes successfully pushed to component
```

```
$ cat .odo/config.yaml kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: java
  SourceLocation: ./
  SourceType: local
  Application: app
  Project: myproject
  Name: java-uspf
```

@kadel Can please provide the detail steps 

> @kadel , your .odo/config.yaml doesn't have Ports section, how come ?
it should error out at odo create itself if there's no ports

@surajnarwade See the config file i pasted above. That also does not have the ```Port``` section.

**Comment by surajnarwade** [comment] 2019-07-16 10:25
/me on latest master

```
$ odo version
odo v1.0.0-beta3 (HEAD)

Server: https://192.168.42.230:8443
Kubernetes: v1.11.0+d4cacc0
```

```
 $ odo component create java
 ✓  Validating component [111ms]
Please use `odo push` command to create the component with source deployed

$ odo push
Validation
 ✓  Validating component [115ms]
 ✓  Checking component [2ms]

Configuration changes
 ✓  Initializing component
 ✓  Creating component [354ms]
 ✓  Applying configuration [16494ns]

Pushing to component java-ckfl of type local
 ✓  Waiting for component to start [2m]
 ✓  Copying files to component [3s]
 ✓  Building component [3m]
 ✓  Changes successfully pushed to component

```

@amitkrout I followed your steps for java s2i image here's my localconfig with ports

```
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: java
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8080/TCP
  - 8443/TCP
  - 8778/TCP
  Application: app
  Project: myproject
  Name: java-ckfl
```

cc @amitkrout  @kadel

**Comment by amitkrout** [comment] 2019-07-16 12:38
> /me on latest master
> @amitkrout I followed your steps for java s2i image here's my localconfig with ports

I tested it on [beta-3](https://github.com/openshift/odo/releases/tag/v1.0.0-beta3) bits. Then the changes of port info in the config file is not the part of beta-3 releases.

**Comment by surajnarwade** [comment] 2019-07-16 13:13
@amitkrout because there's no release after PR got merged

**Comment by kadel** [comment] 2019-07-16 14:04
To reproduce the issue you have to create a component using beta3 and then run push using the latest master.

**Comment by kadel** [comment] 2019-07-16 14:11
- ./odo-darwin-amd64 is released beta3 version
 - odo is master build

push expects the ports to be in the local config, but the older version was not adding it when `--port` was not used.

````
▶ ./odo-darwin-amd64 version
odo v1.0.0-beta3 (c2b402e3)

Server: https://xxxxx
Kubernetes: v1.14.0+65ef059


▶ ./odo-darwin-amd64 create java
 ✓  Validating component [5s]
Please use `odo push` command to create the component with source deployed

▶ cat .odo/config.yaml
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: java
  SourceLocation: ./
  SourceType: local
  Application: app
  Project: default
  Name: java-xfaw

▶ odo version
odo v1.0.0-beta3 (a0c530b1)

Server: xxxx
Kubernetes: v1.14.0+65ef059


▶ odo push
Validation
 ✓  Validating component [5s]
 ✓  Checking component [113ms]

Configuration changes
 ✓  Initializing component
 ◑  Creating component ✗  Failed to create component with name java-xfaw. Please use `odo config view` to view settings used to create component. Error: Service "java-xfaw-app" is invalid: spec.ports: Required value
unable to create Service for java-xfaw-app
github.com/openshift/odo/pkg/occlient.(*Client).CreateService
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/occlient/occlient.go:1278
github.com/openshift/odo/pkg/occlient.(*Client).BootstrapSupervisoredS2I
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/occlient/occlient.go:1232
github.com/openshift/odo/pkg/component.CreateFromPath
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/component/component.go:251
github.com/openshift/odo/pkg/component.CreateComponent
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/component/component.go:412
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).createCmpIfNotExistsAndApplyCmpConfig
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:84
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).Push
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:153
github.com/openshift/odo/pkg/odo/cli/component.(*PushOptions).Run
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:102
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:17
github.com/openshift/odo/pkg/odo/cli/component.NewCmdPush.func1
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:116
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/cmd/odo/odo.go:65
runtime.main
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/proc.go:200
runtime.goexit
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/asm_amd64.s:1337
unable to create Service for java-xfaw-app
github.com/openshift/odo/pkg/occlient.(*Client).BootstrapSupervisoredS2I
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/occlient/occlient.go:1234
github.com/openshift/odo/pkg/component.CreateFromPath
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/component/component.go:251
github.com/openshift/odo/pkg/component.CreateComponent
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/component/component.go:412
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).createCmpIfNotExistsAndApplyCmpConfig
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:84
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).Push
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:153
github.com/openshift/odo/pkg/odo/cli/component.(*PushOptions).Run
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:102
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:17
github.com/openshift/odo/pkg/odo/cli/component.NewCmdPush.func1
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:116
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/cmd/odo/odo.go:65
runtime.main
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/proc.go:200
runtime.goexit
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/asm_amd64.s:1337
failed to create component with args {Name:java-xfaw SourcePath:./ SourceRef: SourceType:local ImageName:java EnvVars:[] Ports:[] Resources:&ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},} ApplicationName:app Wait:false StorageToBeMounted:map[] StdOut:<nil>}
github.com/openshift/odo/pkg/component.CreateComponent
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/component/component.go:413
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).createCmpIfNotExistsAndApplyCmpConfig
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:84
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).Push
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:153
github.com/openshift/odo/pkg/odo/cli/component.(*PushOptions).Run
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:102
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:17
github.com/openshift/odo/pkg/odo/cli/component.NewCmdPush.func1
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:116
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/cmd/odo/odo.go:65
runtime.main
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/proc.go:200
runtime.goexit
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/asm_amd64.s:1337

▶
````

**Comment by surajnarwade** [comment] 2019-07-16 14:26
@kadel , but things addressed in #1828 are expected right ?

* `odo create` will look for ports in image and put it in localconfig and error out if there's no port
* `odo push` should look for ports in localconfig instead of again making the API call

**Comment by kadel** [comment] 2019-07-16 14:33
> @kadel , but things addressed in #1828 are expected right ?

yes, overall what that PR is doing is right. 
But we need to find a solution for this or document migration path. 
Not breaking compatibility is always a better path.

What if `odo push` would lookup exposed image ports again if there are no ports specified in localconfig?

**Comment by surajnarwade** [comment] 2019-07-16 14:34
@kadel ,

`odo create` itself takes care, right it will error out if there's no port and ask user to provide ports

```
odo create xxx --port yyy
```

**Comment by surajnarwade** [comment] 2019-07-16 14:35
Though I agree with this :smiley_cat: 
> Not breaking compatibility is always a better path.

**Comment by kadel** [comment] 2019-07-16 15:10
> `odo create` itself takes care, right it will error out if there's no port and ask the user to provide ports

the problem is that when the component was created with older odo versions (beta3 and older) push won't work.

**Comment by amitkrout** [comment] 2019-07-17 06:02
We need to include some upgrade path test in our test.

**Comment by girishramnani** [comment] 2019-07-24 13:03
adapter will be released with beta4 so we dont need to provide a upgrade path

**Closed by girishramnani** 2019-07-24 13:03 UTC
Labels: kind/bug, priority/High, state/In Analysis
