### ISSUE TITLE
odo catalog component describe should allow registry parameter

### ISSUE THREAD

**Issue by jeffmaury** [openshift/odo#4463] opened 2021-02-27 17:29 UTC
/kind bug

## What versions of software are you using?

**Operating System:**
Win10Pro

**Output of `odo version`:**
`odo v2.0.5 (e8030b19a)`

## How did you run odo exactly?
`odo catalog component describe`

## Actual behavior
Component from first registry is displayed ?

## Expected behavior
We should be able to specifiy the registry to lookup

**Comment by dharmit** [comment] 2021-03-01 09:17
@jeffmaury I'm marking this as a feature instead of a bug since it's something that never existed. Ideally we should have thought of this at the time of v2 release, but evidently we missed that.

**Comment by dharmit** [comment] 2021-03-01 14:13
@jeffmaury on a call today, @kadel mentioned that registry implementation is up for some change. So I have removed this one from consideration for upcoming sprint.

@kadel if there's an issue on devfile repo, can you please link it here so that we can look into this request when it's done?

/priority medium

**Comment by kadel** [comment] 2021-03-09 09:53
After discussing this with @jeffmaury and understanding more about this issue I think that we can safely implement this as it shouldn't change with the new registry implementation.


The problem is this:
When I add my own registry to odo
```
odo registry add my-registry https://raw.githubusercontent.com/kadel/registry/master
```
and my-registry has the devfile with the same name as the default odo registry, I won't be able to run `odo catalog describes component` on devfile from default registry. 

`odo catalog describes component` should have the `--registry` flag similar to how `odo create` has it. To allow forcing the specific registry instead of always using the highest priority one.

**Comment by kadel** [comment] 2021-03-16 09:40
@jeffmaury 
Wouldn't implementing this https://github.com/openshift/odo/issues/4474#issuecomment-795797599 also solve your problem.

If there are multiple components with the same name, it still prints them both, but now the JSON output has the registry name.

**Comment by jeffmaury** [comment] 2021-03-16 12:04
Yes

**Closed** 2021-03-16 15:10 UTC
Labels: kind/feature, priority/Medium
