### ISSUE TITLE
"odo create" creates components with same name when no name is provided as argument

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#4112] opened 2020-10-12 08:23 UTC
/kind bug

## What versions of software are you using?

**Operating System:** Fedora 32 & CRC

**Output of `odo version`:** `master`

## How did you run odo exactly?
```sh
# set things up
$ mkdir /tmp/node1 /tmp/node2
$ git clone https://github.com/akashshinde/node-todo /tmp/node1
$ cp -r /odo/repo/tests/examples/source/devfiles/nodejs/project/ /tmp/node2
$ cp -r /odo/repo/tests/examples/source/devfiles/nodejs/devfile.yaml /tmp/node2

# create the components
$ cd /tmp/node1
$ odo create nodejs
## modify the endpoint in devfile to use port 8080 instead of 3000
$ odo push


$ cd /tmp/node2
$ odo craete nodejs
$ odo push
```

## Actual behavior
* Doing `cat .odo/env/env.yaml` in both `node1` and `node2` directories gives the same result:
    ```sh
    $ cat .odo/env/env.yaml
    ComponentSettings:
      Name: nodejs  <-------
      Project: myproject
      AppName: app
      RunMode: run
    ```

* The worst part of this is that, for some reason, URL of both the components are rendered useless! Neither URL endpoints give a response!

## Expected behavior
Expect the mess up to not happen unless there's some design decision here that I'm not aware of.

/area component

**Comment by adisky** [comment] 2020-10-12 09:24
@dharmit I think we should add some suffix in `odo create` if user has not specified component name.
here the second component will override first one and in `odo list` we see one component.

regarding url? are they not working after changing the port to 8080 too?

**Comment by dharmit** [comment] 2020-10-12 09:29
> I think we should add some suffix in `odo create` if user has not specified component name.

+1.


>  here the second component will override first one and in `odo list` we see one component.

Yes, `odo list` shows only one component. That observation led me to investigate this further.

> regarding url? are they not working after changing the port to 8080 too?

Not sure if I understand your question correctly. When I created URL for port 8080 in node1 directory, it worked fine till the moment I pushed the other component from node2 that had 3000 port exposed for itself. After doing the two `odo push`, neither of the URL responds.

**Comment by adisky** [comment] 2020-10-12 11:01
> Not sure if I understand your question correctly. When I created URL for port 8080 in node1 directory, it worked fine till the moment I pushed the other component from node2 that had 3000 port exposed for itself. After doing the two `odo push`, neither of the URL responds.

In directory /tmp/node1
1. $ odo create nodejs  
2. $ odo push <- (port 8080 here)

In directory /tmp/node2
3.  $ odo create nodejs
4.  $ odo push <-(port 3000 here) 

After step 4 the node2 component would be actually running, second odo push might not have created url as it was already existing, so basically we have exposed node2 component on port8080, and node1 component does not exist so both are unreachable.

**Comment by adisky** [comment] 2020-10-12 11:11
i have seen similar behavior if we do `odo create nodejs <component-name>`  from two different folders having same name https://github.com/openshift/odo/issues/3579, closed this one as here user choosing the same name, but in this case your issue is valid.

**Comment by scottkurz** [comment] 2020-10-13 01:18
I assumed this was the intended behavior.    I also assumed the user had a responsibility to not push over an existing component's contents.  

It seems like pushing one instance of a component with non-default name over another, (when both are in the same project/ namespace) is just as potentially problematic as having a collision between two instances of a component with a default name, (named after the stack).

 As a default component name, it seemed OK... or maybe odo could keep a counter globally somewhere and increment:  e.g. nodejs, nodejs1, nodejs2, etc.   ?

**Comment by adisky** [comment] 2020-10-13 05:47
I think in the case of not specifying component name `odo create <component-type>`, odo should generate a name, it could suffix some random string to component type rather than taking component type as component name.

**Comment by dharmit** [comment] 2020-10-13 06:04
> I assumed this was the intended behavior. I also assumed the user had a responsibility to not push over an existing component's contents.

Never assume, always assert. 
(Just kidding. Never got a chance to say this on any issue, so I thought I'd make myself sound smart.) :wink: 

> It seems like pushing one instance of a component with non-default name over another, (when both are in the same project/ namespace) is just as potentially problematic as having a collision between two instances of a component with a default name, (named after the stack).

I'm confused. Do you mind giving an example of what you're suggesting?

> As a default component name, it seemed OK... or maybe odo could keep a counter globally somewhere and increment: e.g. nodejs, nodejs1, nodejs2, etc. ?

I agree with what @adisky said about using a random string as a suffix in the name that odo gives to a component.

**Comment by adisky** [comment] 2020-10-13 14:36
> But I think it should be clear that it's ultimately the user's responsibility to avoid "collisions".
> 
> Unless, instead, you think it's odo's responsibility. In that case the `odo create .. [duplicate_component_name]` should fail because odo detects the component/project is in use already.
> 
@scottkurz  with the current design it is user's responsibility to avoid collision, but here we are not dealing with how to handle the overlap or give error if user chose to recreate the component with the same name, In this particular case user is not providing any name so its odo's responsibility to generate unique name

**Comment by scottkurz** [comment] 2020-10-14 12:21
>  In this particular case user is not providing any name so its odo's responsibility to generate unique name

I know practically it's a minor distinction, but generating a random name isn't precisely the same as generating a unique one... with a random name there's a very small possibility of collision.    I think adding a random suffix is a reasonable, good idea, just trying to help clarify the goal here.

**Comment by girishramnani** [comment] 2021-01-18 13:13
I can work on this for upcoming sprint

**Comment by girishramnani** [comment] 2021-03-01 10:24
one thing i understand here is that - this behavior is expected but we need to change it hence - we should make this into a feature.
And about resolving this, i would suggest we follow the same approach we did for s2i where the component name was set as `Project-App-name-<random-string>` and we used label selectors to find all the kube resources, currently we depend on names too much if I remember correctly

**Comment by dharmit** [comment] 2021-03-04 11:15
That would still not solve the problem if user specifies the name on the CLI, no? Or would it? Shoult id?

**Comment by girishramnani** [comment] 2021-03-08 04:03
it would because then the name would be `project-app-<user-provided-name>-<random-string>`
e.g. project - `blah`
app - `app`
component name - `hello`
then final name used would be `blah-app-hello-Hsdvgf` and we would have label selectors to get this component.

**Comment by girishramnani** [comment] 2021-03-09 06:59
this would be a bit complicated but would align with how components are name in s2i and also in future if we change the naming mechanism, this approach would be reslilient as we are using label selectors to get the name

**Comment by kadel** [comment] 2021-03-09 08:26
> it would because then the name would be `project-app-<user-provided-name>-<random-string>`
> e.g. project - `blah`
> app - `app`
> component name - `hello`
> then final name used would be `blah-app-hello-Hsdvgf` and we would have label selectors to get this component

Are you talking about the abstract component name or how odo names Kubernetes components?

In other words, If I would run `odo list`  I would see `user-provided-name` or `project-app-<user-provided-name>-<random-string>`


I thought that we are talking about the component names here. I'm not sure if it makes sense to solve this. 
If a user creates two-component with the same name in the same application in the same project it is ok that they collided. I don't think that we need to do something with it. 

```
cd dir1
odo create nodejs mycomponent
cd dir2
odo create  nodejs mycomponent
```
^ This is users problem, nothing that we can or should do about.

```
cd dir1
odo create nodejs  
cd dir2
odo create  nodejs
```
^ This might be a little bit more problematic. I would say that in most cases users should name their components and if the user default generated one, it is on them if they collide. 

We could lower the chances of the name collision by adding a short random suffix. But as @scottkurz pointed out this doesn't solve the problem, it will just lower the chances of this happening (random and unique are two different things).

I think that the best we can do here is to simply check if there already is the component with the same name (in the same app and project), and show a warning. The reason for not erroring out is that after the user does `odo create` they can still use `odo env` command to change the name. This check should happen only when odo can reach the cluster, `odo create` still needs to work offline. In the case where it can't reach the cluster, it should simply ignore this check. 



```
cd dir1
odo create nodejs 
odo push
cd dir2
odo create  nodejs
WARNING: The cluster already has a component with the same name.
```

This won't solve the problem, because as a user I still will be able to create the first component, not push it, and then create the second one with the same name, push it and then go back to the first one and push that one. But I think that this is a problem that doesn't have a solution. 

```
cd dir1
odo create nodejs 
cd dir2
odo create  nodejs
odo push
cd dir
odo push
```

**Comment by dharmit** [comment] 2021-03-09 10:28
> it would because then the name would be `project-app-<user-provided-name>-<random-string>`
> e.g. project - `blah`
> app - `app`
> component name - `hello`
> then final name used would be `blah-app-hello-Hsdvgf` and we would have label selectors to get this component.

Thinking purely from `odo link` perspective.

We have earlier demonstrated an example of linking multiple components with each other. This was the famous Wild West frontend and backend components. In this example, component names were pretty simple - `backend` and `frontend`. So linking experience was also simple - `odo link frontend` or `odo link backend`.

If we create a component name the way it's proposed here, I think it would lead to bad UX for linking or even something like `odo delete <component-name>`.

**Comment by kadel** [comment] 2021-03-09 12:18
> If we create a component name the way it's proposed here, I think it would lead to bad UX for linking or even something like `odo delete <component-name>`.

This would be done only if users don't specify component names. In the Wild West example that you mentioned every component was explicitly named. 




> it would because then the name would be `project-app-<user-provided-name>-<random-string>`

Using this might be a little bit overkill, but something like what we do for s2i might make more sense. `<component type>-<current directory name>-<4 random letters>`

**Comment by girishramnani** [comment] 2021-03-10 08:42
works

**Comment by dharmit** [comment] 2021-03-10 09:17
> > If we create a component name the way it's proposed here, I think it would lead to bad UX for linking or even something like `odo delete <component-name>`.
> 
> This would be done only if users don't specify component names. In the Wild West example that you mentioned every component was explicitly named.

But this comment suggest otherwise https://github.com/openshift/odo/issues/4112#issuecomment-792446146.

What I understood is that `odo create nodejs frontend` will lead to a component named `myproject-app-frontend-Hsdvgf`.

Correct me if my understanding's wrong.

**Comment by kadel** [comment] 2021-03-10 11:30
> > > If we create a component name the way it's proposed here, I think it would lead to bad UX for linking or even something like `odo delete <component-name>`.
> > 
> > 
> > This would be done only if users don't specify component names. In the Wild West example that you mentioned every component was explicitly named.
> 
> But this comment suggest otherwise [#4112 (comment)](https://github.com/openshift/odo/issues/4112#issuecomment-792446146).
> 
> What I understood is that `odo create nodejs frontend` will lead to a component named `myproject-app-frontend-Hsdvgf`.
> 

Yes, that is what was suggested in that comment. But we should not do this. If the user specifies a component name odo needs to create the component with that name.

**Comment by girishramnani** [comment] 2021-03-16 12:04
please note this is a change that needs to be notified to adapter folks

**Closed** 2021-03-18 09:55 UTC
Labels: area/component, kind/bug
