### ISSUE TITLE
odo link does not work for openshift 4.2.2

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#2392] opened 2019-11-12 05:00 UTC
/kind bug

## What versions of software are you using?

**Operating System:** windows 10 pro
**Output of `odo version`:** odo v1.0.0 (4e3175e6f)

## Actual behavior

When linking [frontend ](https://github.com/openshift-evangelists/Wild-West-Frontend) to [backend](https://github.com/openshift-evangelists/Wild-West-Backend) I am getting this error:

Failed to link component with error 'Error: Command failed: "/home/mdunnett/.vs-openshift/odo" link backend --project crc-demo --app demoapp --component frontend --wait --port 8080
✗ waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=frontend-wildwest''

## Expected behavior

Linking is successful.

## Any logs, error output, etc?

N/A

Downstream issue https://github.com/redhat-developer/vscode-openshift-tools/issues/1266.

**Comment by amitkrout** [comment] 2019-11-12 06:07
@dgolovin This is a flake and has been tracked in #2244. Can you please try it again

**Comment by kadel** [comment] 2019-11-12 08:50
> @dgolovin This is a flake and has been tracked in #2244. Can you please try it again

It is not a flaky test if it can be reproduced outside of our test suite.

/priority high
/remove-priority medium
/kind bug

**Comment by amitkrout** [comment] 2019-11-12 11:38
> > @dgolovin This is a flake and has been tracked in #2244. Can you please try it again
> 
> It is not a flaky test if it can be reproduced outside of our test suite.
> 
> /priority high
> /remove-priority medium
> /kind bug

I am saying it as a flake because in my recent test activities while pushing the java component i have seen the same error (✗ waited 4m0s but couldn't...) atleast 3 times out of my 20 test run against 4.3 cluster on aws.

AFAIU once link does change to frontend dc then build followed by a deployment happens. In this process it hit the same issue of  ```...couldn't find running pod matching selector...```

**Comment by dgolovin** [comment] 2019-11-12 14:59
@amitkrout for me it is always the same experience, 
1. I create two components wildwest backend and frontend.
2. I try to link them and linking fails with message about not being able to search pod using selector
3. I see DeploymentConfig is being updated by adding secret with component host and port, but not redeployed.
4. Wildwest frontend is not functional at this moment
5. If I kick deployment form devconsole frontend starts working as expected

**Comment by cdrage** [comment] 2019-11-13 14:12
Hey @dgolovin can you produce any verbose logs to help diagnose it? I'm trying to reproduce it but to no avail :(

Using `-v 4` of course.

**Comment by dgolovin** [comment] 2019-11-18 19:06
@cdrage 
```
"C:\Users\dgolo\.vs-openshift\odo.exe" link backend --project pipelines --app wildwest --component frontend --wait --port 8080 -v 4
I1118 11:01:15.861125   16416 occlient.go:2556] Getting DeploymentConfig: frontend-wildwest
I1118 11:01:15.882095   16416 common_link.go:46] Unable to determine if backend is a service. This most likely means the service catalog is not installed. Proceesing to only use components
I1118 11:01:15.882095   16416 occlient.go:2556] Getting DeploymentConfig: backend-wildwest
 V  Component backend has been successfully linked to the component frontend

The below secret environment variables were added to the 'frontend' component:

· COMPONENT_BACKEND_HOST
· COMPONENT_BACKEND_PORT

You can now access the environment variables from within the component pod, for example:
$COMPONENT_BACKEND_HOST is now available as a variable within component frontend
I1118 11:01:15.983794   16416 occlient.go:1745] Waiting for deploymentconfig=frontend-wildwest pod
 -  Waiting for component to redeploy  ...
I1118 11:01:15.996792   16416 occlient.go:1769] Status of frontend-wildwest-1-9xqrj pod is Running
 X  Waiting for component to redeploy [4m]
I1118 11:05:15.998034   16416 cmdutils.go:48] Error:
waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=frontend-wildwest'
 X  waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=frontend-wildwest'
```

**Comment by dgolovin** [comment] 2019-11-18 19:25
@cdrage 
```
"C:\Users\dgolo\.vs-openshift\odo.exe" link backend --project pipelines --app wildwest --component frontend --wait --port 8080 -v 8
I1118 11:17:42.654252    4792 loader.go:359] Config loaded from file C:\Users\dgolo/.kube/config
I1118 11:17:42.657267    4792 round_trippers.go:383] GET https://api.crc.testing:6443/apis/project.openshift.io/v1/projects/pipelines
I1118 11:17:42.659454    4792 round_trippers.go:390] Request Headers:
I1118 11:17:42.661254    4792 round_trippers.go:393]     Accept: application/json, */*
I1118 11:17:42.663264    4792 round_trippers.go:393]     User-Agent: odo.exe/v0.0.0 (windows/amd64) kubernetes/$Format
I1118 11:17:42.665255    4792 round_trippers.go:393]     Authorization: Bearer sGzdreLBsG4PxiTPqFUw1-PuRYg_5pQzmQOAMHFSW3s
I1118 11:17:42.834920    4792 round_trippers.go:408] Response Status: 200 OK in 169 milliseconds
I1118 11:17:42.834920    4792 round_trippers.go:411] Response Headers:
I1118 11:17:42.841920    4792 round_trippers.go:414]     Content-Length: 597
I1118 11:17:42.842940    4792 round_trippers.go:414]     Audit-Id: b567defc-d966-4615-8033-8d9615b0fed0
I1118 11:17:42.845934    4792 round_trippers.go:414]     Cache-Control: no-cache, private
I1118 11:17:42.846940    4792 round_trippers.go:414]     Cache-Control: no-store
I1118 11:17:42.849953    4792 round_trippers.go:414]     Content-Type: application/json
I1118 11:17:42.850920    4792 round_trippers.go:414]     Date: Mon, 18 Nov 2019 19:17:42 GMT
I1118 11:17:42.852923    4792 request.go:897] Response Body: {"kind":"Project","apiVersion":"project.openshift.io/v1","metadata":{"name":"pipelines","selfLink":"/apis/project.openshift.io/v1/projects/pipelines","uid":"afe1ab2e-0a32-11ea-926b-00155d009446","resourceVersion":"234440","creationTimestamp":"2019-11-18T18:39:00Z","annotations":{"openshift.io/description":"","openshift.io/display-name":"","openshift.io/requester":"developer","openshift.io/sa.scc.mcs":"s0:c24,c19","openshift.io/sa.scc.supplemental-groups":"1000590000/10000","openshift.io/sa.scc.uid-range":"1000590000/10000"}},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}
I1118 11:17:42.857922    4792 occlient.go:2556] Getting DeploymentConfig: frontend-wildwest
I1118 11:17:42.861928    4792 round_trippers.go:383] GET https://api.crc.testing:6443/apis/apps.openshift.io/v1/namespaces/pipelines/deploymentconfigs/frontend-wildwest
I1118 11:17:42.862922    4792 round_trippers.go:390] Request Headers:
I1118 11:17:42.863932    4792 round_trippers.go:393]     Accept: application/json, */*
I1118 11:17:42.864922    4792 round_trippers.go:393]     User-Agent: odo.exe/v0.0.0 (windows/amd64) kubernetes/$Format
I1118 11:17:42.869931    4792 round_trippers.go:393]     Authorization: Bearer sGzdreLBsG4PxiTPqFUw1-PuRYg_5pQzmQOAMHFSW3s
I1118 11:17:42.879925    4792 round_trippers.go:408] Response Status: 200 OK in 6 milliseconds
I1118 11:17:42.880933    4792 round_trippers.go:411] Response Headers:
I1118 11:17:42.880933    4792 round_trippers.go:414]     Content-Length: 2722
I1118 11:17:42.881923    4792 round_trippers.go:414]     Audit-Id: bfc149c3-18cd-4f77-a9b8-a0950f7b8a65
I1118 11:17:42.883921    4792 round_trippers.go:414]     Cache-Control: no-cache, private
I1118 11:17:42.887923    4792 round_trippers.go:414]     Cache-Control: no-store
I1118 11:17:42.889011    4792 round_trippers.go:414]     Content-Type: application/json
I1118 11:17:42.889926    4792 round_trippers.go:414]     Date: Mon, 18 Nov 2019 19:17:42 GMT
I1118 11:17:42.890926    4792 request.go:897] Response Body: {"kind":"DeploymentConfig","apiVersion":"apps.openshift.io/v1","metadata":{"name":"frontend-wildwest","namespace":"pipelines","selfLink":"/apis/apps.openshift.io/v1/namespaces/pipelines/deploymentconfigs/frontend-wildwest","uid":"86449de6-0a37-11ea-a050-0a580a8000a4","resourceVersion":"240809","generation":2,"creationTimestamp":"2019-11-18T19:13:38Z","labels":{"app":"wildwest","app.kubernetes.io/instance":"frontend","app.kubernetes.io/managed-by":"odo","app.kubernetes.io/managed-by-version":"v1.0.1","app.kubernetes.io/name":"nodejs","app.kubernetes.io/part-of":"wildwest","app.openshift.io/runtime-version":"10"},"annotations":{"app.kubernetes.io/component-source-type":"git","app.openshift.io/vcs-uri":"https://github.com/openshift-evangelists/Wild-West-Frontend"}},"spec":{"strategy":{"type":"Recreate","recreateParams":{"timeoutSeconds":600},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"containerNames":["frontend-wildwest"],"from":{"kind":"ImageStreamTag"," [truncated 1698 chars]
I1118 11:17:42.900920    4792 round_trippers.go:383] GET https://api.crc.testing:6443/apis/servicecatalog.k8s.io/v1beta1/namespaces/pipelines/serviceinstances?labelSelector=app.kubernetes.io%2Fpart-of%3Dwildwest
I1118 11:17:42.900920    4792 round_trippers.go:390] Request Headers:
I1118 11:17:42.901922    4792 round_trippers.go:393]     Accept: application/json, */*
I1118 11:17:42.904019    4792 round_trippers.go:393]     User-Agent: odo.exe/v0.0.0 (windows/amd64) kubernetes/$Format
I1118 11:17:42.904921    4792 round_trippers.go:393]     Authorization: Bearer sGzdreLBsG4PxiTPqFUw1-PuRYg_5pQzmQOAMHFSW3s
I1118 11:17:42.910937    4792 round_trippers.go:408] Response Status: 403 Forbidden in 2 milliseconds
I1118 11:17:42.913920    4792 round_trippers.go:411] Response Headers:
I1118 11:17:42.915920    4792 round_trippers.go:414]     Audit-Id: 3b2a6d4f-bfc3-4b02-b388-0fe0d2a04b42
I1118 11:17:42.916924    4792 round_trippers.go:414]     Cache-Control: no-cache, private
I1118 11:17:42.917921    4792 round_trippers.go:414]     Content-Type: application/json
I1118 11:17:42.918926    4792 round_trippers.go:414]     X-Content-Type-Options: nosniff
I1118 11:17:42.923921    4792 round_trippers.go:414]     Content-Length: 367
I1118 11:17:42.926934    4792 round_trippers.go:414]     Date: Mon, 18 Nov 2019 19:17:42 GMT
I1118 11:17:42.928925    4792 request.go:897] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"serviceinstances.servicecatalog.k8s.io is forbidden: User \"developer\" cannot list resource \"serviceinstances\" in API group \"servicecatalog.k8s.io\" in the namespace \"pipelines\"","reason":"Forbidden","details":{"group":"servicecatalog.k8s.io","kind":"serviceinstances"},"code":403}
I1118 11:17:42.930922    4792 common_link.go:46] Unable to determine if backend is a service. This most likely means the service catalog is not installed. Proceesing to only use components
I1118 11:17:42.930922    4792 occlient.go:2556] Getting DeploymentConfig: backend-wildwest
I1118 11:17:42.931926    4792 round_trippers.go:383] GET https://api.crc.testing:6443/apis/apps.openshift.io/v1/namespaces/pipelines/deploymentconfigs/backend-wildwest
I1118 11:17:42.936932    4792 round_trippers.go:390] Request Headers:
I1118 11:17:42.942922    4792 round_trippers.go:393]     User-Agent: odo.exe/v0.0.0 (windows/amd64) kubernetes/$Format
I1118 11:17:42.944928    4792 round_trippers.go:393]     Authorization: Bearer sGzdreLBsG4PxiTPqFUw1-PuRYg_5pQzmQOAMHFSW3s
I1118 11:17:42.944928    4792 round_trippers.go:393]     Accept: application/json, */*
I1118 11:17:42.956925    4792 round_trippers.go:408] Response Status: 200 OK in 6 milliseconds
I1118 11:17:42.956925    4792 round_trippers.go:411] Response Headers:
I1118 11:17:42.957922    4792 round_trippers.go:414]     Audit-Id: eb4dd6f5-90d0-48ae-b194-117752f488b3
I1118 11:17:42.958934    4792 round_trippers.go:414]     Cache-Control: no-cache, private
I1118 11:17:42.963922    4792 round_trippers.go:414]     Cache-Control: no-store
I1118 11:17:42.966923    4792 round_trippers.go:414]     Content-Type: application/json
I1118 11:17:42.968932    4792 round_trippers.go:414]     Date: Mon, 18 Nov 2019 19:17:42 GMT
I1118 11:17:42.969937    4792 round_trippers.go:414]     Content-Length: 2823
I1118 11:17:42.970945    4792 request.go:897] Response Body: {"kind":"DeploymentConfig","apiVersion":"apps.openshift.io/v1","metadata":{"name":"backend-wildwest","namespace":"pipelines","selfLink":"/apis/apps.openshift.io/v1/namespaces/pipelines/deploymentconfigs/backend-wildwest","uid":"84ed9656-0a37-11ea-a050-0a580a8000a4","resourceVersion":"240929","generation":2,"creationTimestamp":"2019-11-18T19:13:35Z","labels":{"app":"wildwest","app.kubernetes.io/instance":"backend","app.kubernetes.io/managed-by":"odo","app.kubernetes.io/managed-by-version":"v1.0.1","app.kubernetes.io/name":"java","app.kubernetes.io/part-of":"wildwest","app.openshift.io/runtime-version":"8"},"annotations":{"app.kubernetes.io/component-source-type":"git","app.openshift.io/vcs-uri":"https://github.com/openshift-evangelists/Wild-West-Backend"}},"spec":{"strategy":{"type":"Recreate","recreateParams":{"timeoutSeconds":600},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"containerNames":["backend-wildwest"],"from":{"kind":"ImageStreamTag","namespac [truncated 1799 chars]
I1118 11:17:42.972044    4792 round_trippers.go:383] GET https://api.crc.testing:6443/api/v1/namespaces/pipelines/secrets?labelSelector=app.kubernetes.io%2Fpart-of%3Dwildwest%2Capp.kubernetes.io%2Finstance%3Dbackend
I1118 11:17:42.972948    4792 round_trippers.go:390] Request Headers:
I1118 11:17:42.976925    4792 round_trippers.go:393]     Authorization: Bearer sGzdreLBsG4PxiTPqFUw1-PuRYg_5pQzmQOAMHFSW3s
I1118 11:17:42.983922    4792 round_trippers.go:393]     Accept: application/json, */*
I1118 11:17:42.984938    4792 round_trippers.go:393]     User-Agent: odo.exe/v0.0.0 (windows/amd64) kubernetes/$Format
I1118 11:17:42.990128    4792 round_trippers.go:408] Response Status: 200 OK in 3 milliseconds
I1118 11:17:42.990928    4792 round_trippers.go:411] Response Headers:
I1118 11:17:42.990928    4792 round_trippers.go:414]     Audit-Id: 74860381-e6b0-4382-910b-74cc2e8444dc
I1118 11:17:42.991923    4792 round_trippers.go:414]     Cache-Control: no-cache, private
I1118 11:17:42.995922    4792 round_trippers.go:414]     Content-Type: application/json
I1118 11:17:42.996925    4792 round_trippers.go:414]     Content-Length: 2564
I1118 11:17:42.997921    4792 round_trippers.go:414]     Date: Mon, 18 Nov 2019 19:17:42 GMT
I1118 11:17:42.999927    4792 request.go:897] Response Body: {"kind":"SecretList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/namespaces/pipelines/secrets","resourceVersion":"241158"},"items":[{"metadata":{"name":"backend-wildwest-8080","namespace":"pipelines","selfLink":"/api/v1/namespaces/pipelines/secrets/backend-wildwest-8080","uid":"84f0bf5d-0a37-11ea-926b-00155d009446","resourceVersion":"240354","creationTimestamp":"2019-11-18T19:13:35Z","labels":{"app":"wildwest","app.kubernetes.io/instance":"backend","app.kubernetes.io/managed-by":"odo","app.kubernetes.io/managed-by-version":"v1.0.1","app.kubernetes.io/name":"java","app.kubernetes.io/part-of":"wildwest","app.openshift.io/runtime-version":"8"},"annotations":{"app.kubernetes.io/component-source-type":"git","app.openshift.io/vcs-uri":"https://github.com/openshift-evangelists/Wild-West-Backend","component-port":"8080"}},"data":{"COMPONENT_BACKEND_HOST":"YmFja2VuZC13aWxkd2VzdA==","COMPONENT_BACKEND_PORT":"ODA4MA=="},"type":"Opaque"},{"metadata":{"name":"backend-wildwest-8443","namespace":"pipelines","selfLink" [truncated 1540 chars]
I1118 11:17:43.002931    4792 round_trippers.go:383] GET https://api.crc.testing:6443/apis/apps.openshift.io/v1/namespaces/pipelines/deploymentconfigs?labelSelector=app.kubernetes.io%2Fpart-of%3Dwildwest%2Capp.kubernetes.io%2Finstance%3Dfrontend
I1118 11:17:43.003927    4792 round_trippers.go:390] Request Headers:
I1118 11:17:43.009920    4792 round_trippers.go:393]     Authorization: Bearer sGzdreLBsG4PxiTPqFUw1-PuRYg_5pQzmQOAMHFSW3s
I1118 11:17:43.011922    4792 round_trippers.go:393]     Accept: application/json, */*
I1118 11:17:43.012922    4792 round_trippers.go:393]     User-Agent: odo.exe/v0.0.0 (windows/amd64) kubernetes/$Format
I1118 11:17:43.021925    4792 round_trippers.go:408] Response Status: 200 OK in 7 milliseconds
I1118 11:17:43.021925    4792 round_trippers.go:411] Response Headers:
I1118 11:17:43.022922    4792 round_trippers.go:414]     Audit-Id: df8bb133-4824-4c68-96bf-29a65c21daf3
I1118 11:17:43.023925    4792 round_trippers.go:414]     Cache-Control: no-cache, private
I1118 11:17:43.024927    4792 round_trippers.go:414]     Cache-Control: no-store
I1118 11:17:43.025927    4792 round_trippers.go:414]     Content-Type: application/json
I1118 11:17:43.030927    4792 round_trippers.go:414]     Date: Mon, 18 Nov 2019 19:17:42 GMT
I1118 11:17:43.034926    4792 round_trippers.go:414]     Content-Length: 2857
I1118 11:17:43.036926    4792 request.go:897] Response Body: {"kind":"DeploymentConfigList","apiVersion":"apps.openshift.io/v1","metadata":{"selfLink":"/apis/apps.openshift.io/v1/namespaces/pipelines/deploymentconfigs","resourceVersion":"241158"},"items":[{"metadata":{"name":"frontend-wildwest","namespace":"pipelines","selfLink":"/apis/apps.openshift.io/v1/namespaces/pipelines/deploymentconfigs/frontend-wildwest","uid":"86449de6-0a37-11ea-a050-0a580a8000a4","resourceVersion":"240809","generation":2,"creationTimestamp":"2019-11-18T19:13:38Z","labels":{"app":"wildwest","app.kubernetes.io/instance":"frontend","app.kubernetes.io/managed-by":"odo","app.kubernetes.io/managed-by-version":"v1.0.1","app.kubernetes.io/name":"nodejs","app.kubernetes.io/part-of":"wildwest","app.openshift.io/runtime-version":"10"},"annotations":{"app.kubernetes.io/component-source-type":"git","app.openshift.io/vcs-uri":"https://github.com/openshift-evangelists/Wild-West-Frontend"}},"spec":{"strategy":{"type":"Recreate","recreateParams":{"timeoutSeconds":600},"resources":{},"activeDeadlineSeconds":2 [truncated 1833 chars]
I1118 11:17:43.042925    4792 round_trippers.go:383] GET https://api.crc.testing:6443/apis/apps.openshift.io/v1/namespaces/pipelines/deploymentconfigs/frontend-wildwest
I1118 11:17:43.046933    4792 round_trippers.go:390] Request Headers:
I1118 11:17:43.046933    4792 round_trippers.go:393]     Accept: application/json, */*
I1118 11:17:43.048923    4792 round_trippers.go:393]     User-Agent: odo.exe/v0.0.0 (windows/amd64) kubernetes/$Format
I1118 11:17:43.049964    4792 round_trippers.go:393]     Authorization: Bearer sGzdreLBsG4PxiTPqFUw1-PuRYg_5pQzmQOAMHFSW3s
I1118 11:17:43.054925    4792 round_trippers.go:408] Response Status: 200 OK in 4 milliseconds
I1118 11:17:43.056922    4792 round_trippers.go:411] Response Headers:
I1118 11:17:43.057930    4792 round_trippers.go:414]     Date: Mon, 18 Nov 2019 19:17:42 GMT
I1118 11:17:43.059924    4792 round_trippers.go:414]     Content-Length: 2722
I1118 11:17:43.060921    4792 round_trippers.go:414]     Audit-Id: 8d034fa5-9e4a-4209-8bd3-2e55492430fd
I1118 11:17:43.061921    4792 round_trippers.go:414]     Cache-Control: no-cache, private
I1118 11:17:43.062920    4792 round_trippers.go:414]     Cache-Control: no-store
I1118 11:17:43.062920    4792 round_trippers.go:414]     Content-Type: application/json
I1118 11:17:43.063921    4792 request.go:897] Response Body: {"kind":"DeploymentConfig","apiVersion":"apps.openshift.io/v1","metadata":{"name":"frontend-wildwest","namespace":"pipelines","selfLink":"/apis/apps.openshift.io/v1/namespaces/pipelines/deploymentconfigs/frontend-wildwest","uid":"86449de6-0a37-11ea-a050-0a580a8000a4","resourceVersion":"240809","generation":2,"creationTimestamp":"2019-11-18T19:13:38Z","labels":{"app":"wildwest","app.kubernetes.io/instance":"frontend","app.kubernetes.io/managed-by":"odo","app.kubernetes.io/managed-by-version":"v1.0.1","app.kubernetes.io/name":"nodejs","app.kubernetes.io/part-of":"wildwest","app.openshift.io/runtime-version":"10"},"annotations":{"app.kubernetes.io/component-source-type":"git","app.openshift.io/vcs-uri":"https://github.com/openshift-evangelists/Wild-West-Frontend"}},"spec":{"strategy":{"type":"Recreate","recreateParams":{"timeoutSeconds":600},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"containerNames":["frontend-wildwest"],"from":{"kind":"ImageStreamTag"," [truncated 1698 chars]
I1118 11:17:43.064923    4792 request.go:897] Request Body: [{ "op": "add", "path": "/spec/template/spec/containers/0/envFrom", "value": [{"secretRef": {"name": "backend-wildwest-8080"}}] }]
I1118 11:17:43.064923    4792 round_trippers.go:383] PATCH https://api.crc.testing:6443/apis/apps.openshift.io/v1/namespaces/pipelines/deploymentconfigs/frontend-wildwest
I1118 11:17:43.069925    4792 round_trippers.go:390] Request Headers:
I1118 11:17:43.078923    4792 round_trippers.go:393]     Authorization: Bearer sGzdreLBsG4PxiTPqFUw1-PuRYg_5pQzmQOAMHFSW3s
I1118 11:17:43.079922    4792 round_trippers.go:393]     Accept: application/json, */*
I1118 11:17:43.083933    4792 round_trippers.go:393]     Content-Type: application/json-patch+json
I1118 11:17:43.084922    4792 round_trippers.go:393]     User-Agent: odo.exe/v0.0.0 (windows/amd64) kubernetes/$Format
I1118 11:17:43.094924    4792 round_trippers.go:408] Response Status: 200 OK in 10 milliseconds
I1118 11:17:43.094924    4792 round_trippers.go:411] Response Headers:
I1118 11:17:43.094924    4792 round_trippers.go:414]     Audit-Id: 07276314-17e0-4f42-9cb7-282662fd4624
I1118 11:17:43.095923    4792 round_trippers.go:414]     Cache-Control: no-cache, private
I1118 11:17:43.097920    4792 round_trippers.go:414]     Cache-Control: no-store
I1118 11:17:43.100921    4792 round_trippers.go:414]     Content-Type: application/json
I1118 11:17:43.101931    4792 round_trippers.go:414]     Date: Mon, 18 Nov 2019 19:17:42 GMT
I1118 11:17:43.102937    4792 round_trippers.go:414]     Content-Length: 2781
I1118 11:17:43.103921    4792 request.go:897] Response Body: {"kind":"DeploymentConfig","apiVersion":"apps.openshift.io/v1","metadata":{"name":"frontend-wildwest","namespace":"pipelines","selfLink":"/apis/apps.openshift.io/v1/namespaces/pipelines/deploymentconfigs/frontend-wildwest","uid":"86449de6-0a37-11ea-a050-0a580a8000a4","resourceVersion":"241159","generation":3,"creationTimestamp":"2019-11-18T19:13:38Z","labels":{"app":"wildwest","app.kubernetes.io/instance":"frontend","app.kubernetes.io/managed-by":"odo","app.kubernetes.io/managed-by-version":"v1.0.1","app.kubernetes.io/name":"nodejs","app.kubernetes.io/part-of":"wildwest","app.openshift.io/runtime-version":"10"},"annotations":{"app.kubernetes.io/component-source-type":"git","app.openshift.io/vcs-uri":"https://github.com/openshift-evangelists/Wild-West-Frontend"}},"spec":{"strategy":{"type":"Recreate","recreateParams":{"timeoutSeconds":600},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"containerNames":["frontend-wildwest"],"from":{"kind":"ImageStreamTag"," [truncated 1757 chars]
 V  Component backend has been successfully linked to the component frontend

I1118 11:17:43.113925    4792 round_trippers.go:383] GET https://api.crc.testing:6443/api/v1/namespaces/pipelines/secrets/backend-wildwest-8080
I1118 11:17:43.115930    4792 round_trippers.go:390] Request Headers:
I1118 11:17:43.116925    4792 round_trippers.go:393]     Accept: application/json, */*
I1118 11:17:43.116925    4792 round_trippers.go:393]     User-Agent: odo.exe/v0.0.0 (windows/amd64) kubernetes/$Format
I1118 11:17:43.117921    4792 round_trippers.go:393]     Authorization: Bearer sGzdreLBsG4PxiTPqFUw1-PuRYg_5pQzmQOAMHFSW3s
I1118 11:17:43.120922    4792 round_trippers.go:408] Response Status: 200 OK in 1 milliseconds
I1118 11:17:43.125920    4792 round_trippers.go:411] Response Headers:
I1118 11:17:43.126999    4792 round_trippers.go:414]     Audit-Id: 04934375-7929-4b74-a0ca-7aac39716607
I1118 11:17:43.128921    4792 round_trippers.go:414]     Cache-Control: no-cache, private
I1118 11:17:43.128921    4792 round_trippers.go:414]     Content-Type: application/json
I1118 11:17:43.129924    4792 round_trippers.go:414]     Content-Length: 842
I1118 11:17:43.130928    4792 round_trippers.go:414]     Date: Mon, 18 Nov 2019 19:17:42 GMT
I1118 11:17:43.131922    4792 request.go:897] Response Body: {"kind":"Secret","apiVersion":"v1","metadata":{"name":"backend-wildwest-8080","namespace":"pipelines","selfLink":"/api/v1/namespaces/pipelines/secrets/backend-wildwest-8080","uid":"84f0bf5d-0a37-11ea-926b-00155d009446","resourceVersion":"240354","creationTimestamp":"2019-11-18T19:13:35Z","labels":{"app":"wildwest","app.kubernetes.io/instance":"backend","app.kubernetes.io/managed-by":"odo","app.kubernetes.io/managed-by-version":"v1.0.1","app.kubernetes.io/name":"java","app.kubernetes.io/part-of":"wildwest","app.openshift.io/runtime-version":"8"},"annotations":{"app.kubernetes.io/component-source-type":"git","app.openshift.io/vcs-uri":"https://github.com/openshift-evangelists/Wild-West-Backend","component-port":"8080"}},"data":{"COMPONENT_BACKEND_HOST":"YmFja2VuZC13aWxkd2VzdA==","COMPONENT_BACKEND_PORT":"ODA4MA=="},"type":"Opaque"}
The below secret environment variables were added to the 'frontend' component:

· COMPONENT_BACKEND_HOST
· COMPONENT_BACKEND_PORT

You can now access the environment variables from within the component pod, for example:
$COMPONENT_BACKEND_HOST is now available as a variable within component frontend
I1118 11:17:43.164925    4792 occlient.go:1745] Waiting for deploymentconfig=frontend-wildwest pod
 -  Waiting for component to redeploy  ...
I1118 11:17:43.168935    4792 round_trippers.go:383] GET https://api.crc.testing:6443/api/v1/namespaces/pipelines/pods?labelSelector=deploymentconfig%3Dfrontend-wildwest&watch=true
I1118 11:17:43.169926    4792 round_trippers.go:390] Request Headers:
I1118 11:17:43.169926    4792 round_trippers.go:393]     Accept: application/json, */*
I1118 11:17:43.170920    4792 round_trippers.go:393]     User-Agent: odo.exe/v0.0.0 (windows/amd64) kubernetes/$Format
I1118 11:17:43.175921    4792 round_trippers.go:393]     Authorization: Bearer sGzdreLBsG4PxiTPqFUw1-PuRYg_5pQzmQOAMHFSW3s
I1118 11:17:43.179935    4792 round_trippers.go:408] Response Status: 200 OK in 2 milliseconds
I1118 11:17:43.179935    4792 round_trippers.go:411] Response Headers:
I1118 11:17:43.180921    4792 round_trippers.go:414]     Cache-Control: no-cache, private
I1118 11:17:43.181934    4792 round_trippers.go:414]     Content-Type: application/json
I1118 11:17:43.181934    4792 round_trippers.go:414]     Date: Mon, 18 Nov 2019 19:17:42 GMT
I1118 11:17:43.188922    4792 occlient.go:1769] Status of frontend-wildwest-1-fgtmj pod is Running
 X  Waiting for component to redeploy [5m]
I1118 11:22:49.128907    4792 cmdutils.go:48] Error:
waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=frontend-wildwest'
 X  waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=frontend-wildwest'
```

**Comment by amitkrout** [comment] 2020-01-28 08:12
@dgolovin @cdrage I am able to reproduce it with the [frontend](https://github.com/openshift-evangelists/Wild-West-Frontend) and [backend](https://github.com/openshift-evangelists/Wild-West-Backend) of wildwest example

Steps i followed:

```
$ odo component create nodejs frontend --context frontend --project wildwest --git https://github.com/openshift-evangelists/Wild-West-Frontend
 ✓  Validating component [535ms]

Please use `odo push` command to create the component with source deployed
```
```
$ odo component create java backend --context backend --project wildwest --git https://github.com/openshift-evangelists/Wild-West-Backend
 ✓  Validating component [578ms]

Please use `odo push` command to create the component with source deployed
```
```
$ odo push --context backend/Validation
 ✓  Checking component [812ms]

Configuration changes
 ✓  Initializing component
 ✓  Creating component [4s]
 ✓  Triggering build from git [355ms]
 ✓  Waiting for build to finish [2m]
 ✓  Deploying component backend [25s]

Pushing to component backend of type git
 ✓  Changes successfully pushed to component
```
```
$ odo push --context frontend/Validation
 ✓  Checking component [808ms]

Configuration changes
 ✓  Initializing component
 ✓  Creating component [3s]
 ✓  Triggering build from git [343ms]
 ✓  Waiting for build to finish [2m]
 ✓  Deploying component frontend [22s]

Pushing to component frontend of type git
 ✓  Changes successfully pushed to component
```
```
$ odo link backend --port 8080 --wait --context frontend/ -v 4I0128 13:12:47.652226   22068 common_link.go:46] Unable to determine if backend is a service. This most likely means the service catalog is not installed. Proceesing to only use components
I0128 13:12:47.652627   22068 occlient.go:2549] Getting DeploymentConfig: backend-app
 ✓  Component backend has been successfully linked to the component frontend

The below secret environment variables were added to the 'frontend' component:

· COMPONENT_BACKEND_HOST
· COMPONENT_BACKEND_PORT

You can now access the environment variables from within the component pod, for example:
$COMPONENT_BACKEND_HOST is now available as a variable within component frontend
I0128 13:12:49.506759   22068 preference.go:137] The path for preference file is /Users/amit/.odo/preference.yaml
I0128 13:12:49.507162   22068 occlient.go:1756] Waiting for deploymentconfig=frontend-app pod
 •  Waiting for component to redeploy  ...
I0128 13:12:49.779523   22068 occlient.go:1780] Status of frontend-app-1-hh5fn pod is Running
 ✗  Waiting for component to redeploy [4m]
I0128 13:16:49.771103   22068 cmdutils.go:48] Error:
waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=frontend-app'
 ✗  waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=frontend-app'
```

@mik-dass has good amount of experience to dealing with such type issue. I would request @mik-dass have a look into this for a quick analysis result.

**Comment by mik-dass** [comment] 2020-01-29 13:02
>  ✗  waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=frontend-app'
@amitkrout This seems to be a timeout issue similar to https://github.com/openshift/odo/issues/2244

**Comment by cdrage** [comment] 2020-02-10 19:29
@amitkrout Yeah, let me take this up. I'm going to refactor https://github.com/openshift/odo/pull/2426 completely and give some more verbose / better errors for the timeout.

**Comment by kadel** [comment] 2020-03-16 13:09
I tried to multiple times using cluster running on AWS, and also using CRC. So far no luck in trying to reproduce this :-/
@dgolovin or @amitkrout  If you can reproduce this can you please share the output of the following command?
```
kubectl describe pods -n <namespace where frontend is running>
```

**Comment by cdrage** [comment] 2020-03-24 15:16
Hey @dgolovin and @amitkrout https://github.com/openshift/odo/pull/2627 has been merged in to try and help with regards to outputting more information with regards to what is actually causing the issue.

Do you mind @dgolovin using the latest master build and letting us know when you get the issue again what the errors say?

**Comment by kadel** [comment] 2020-04-09 15:04
> [<img alt="@girishramnani" width="20" height="20" src="https://avatars0.githubusercontent.com/u/6551988?s=60&amp;u=93eaf1f99f7a22757db5bad83759b6cf8fd40007&amp;v=4">](/girishramnani) [girishramnani](/girishramnani) added the [status/blocked](/openshift/odo/labels/status%2Fblocked) label [8 days ago](#event-3188149272)

@girishramnani 
what is this blocked on?

**Comment by cdrage** [comment] 2020-05-01 14:25
I'm going to close this as we haven't heard back from @dgolovin (Slack & GitHub).

Please let us know if you encounter this issue again!

**Closed by cdrage** 2020-05-01 14:25 UTC
Labels: area/linking, kind/bug, priority/High, status/blocked, triage/needs-information

**Comment by dgolovin** [comment] 2020-05-07 20:13
works for me with latest release v1.2.0,
