### ISSUE TITLE
Implement `--wait` flag for `odo service delete`

### ISSUE THREAD

**Issue by surajnarwade** [openshift/odo#1943] opened 2019-07-23 10:52 UTC
[kind/Enhancement]

## Which functionality do you think we should update/improve?

Add `--wait` flag in `odo storage delete` similar to `odo project create`

## Why is this needed? 

Reference: `waitForServiceToBeGone` from https://github.com/openshift/odo/issues/1739

as of now, vscode plugin relies on,

```
oc wait ServiceInstance/${service} --for delete --namespace ${project}
```

**Comment by girishramnani** [comment] 2019-12-26 09:43
seems like this is duplicate of https://github.com/openshift/odo/issues/1483. Closing this issue as its newer

**Closed by girishramnani** 2019-12-26 09:43 UTC
