### ISSUE TITLE
Travis failures in "generic login, component command integration tests"

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2953] opened 2020-04-22 09:43 UTC
I observed below flake on Travis in **generic login, component command integration tests**

```
[odo]  ✓  Changes successfully pushed to component
Running odo with args [odo delete --context /tmp/753695717 -f]
[odo]  ✗  invalid configuration: [context was not found for specified context: qhhnzpnvmg/127-0-0-1:8443/developer, cluster has no server defined]
```
/kind flake

_Originally posted by @dharmit in https://github.com/openshift/odo/pull/2944#issuecomment-617552849_

**Comment by dharmit** [comment] 2020-04-22 09:55
Some more errors unrelated to the underlying PR. Saw this in #2901
```
[odo]  •  Checking files for pushing  ...
 ✓  Checking files for pushing [1ms]
[odo]  •  Waiting for component to start  ...
[odo]  ✗  waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=sb-jar-test-app'
[odo]  ✗  Waiting for component to start [4m]
Deleting project: spkhpmdjpm
Running odo with args [odo project delete spkhpmdjpm -f]
[odo] This project contains the following applications, which will be deleted
[odo] Application app
[odo] This application has following components that will be deleted
[odo] component named sb-jar-test
[odo] This component has following urls that will be deleted with component
[odo] URL named uberjaropenjdk with host uberjaropenjdk-app-spkhpmdjpm.127.0.0.1.nip.io having protocol http at port 8080
[odo] No services / could not get services
[odo]  •  Deleting project spkhpmdjpm  ...
 ✓  Deleting project spkhpmdjpm [8s]
[odo]  ✓  Deleted project : spkhpmdjpm
Setting current dir to: /home/travis/gopath/src/github.com/openshift/odo/tests/integration
Deleting dir: /tmp/030781953
• Failure [257.219 seconds]
odo component command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/cmd_cmp_test.go:13
  Creating component using symlink
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/component.go:775
    Should be able to deploy a spring boot uberjar file using symlinks in all odo commands [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/component.go:799
    No future change is possible.  Bailing out early after 241.291s.
    Running odo with args [odo push --context /tmp/ulmzggtuue]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
```

**Comment by amitkrout** [comment] 2020-04-23 09:37
> [odo]  ✓  Changes successfully pushed to component
Running odo with args [odo delete --context /tmp/753695717 -f]
[odo]  ✗  invalid configuration: [context was not found for specified context: qhhnzpnvmg/127-0-0-1:8443/developer, cluster has no server defined]

Duplicate of https://github.com/openshift/odo/issues/2088

> [odo]  •  Checking files for pushing  ...
 ✓  Checking files for pushing [1ms]
[odo]  •  Waiting for component to start  ...
[odo]  ✗  waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=sb-jar-test-app'
[odo]  ✗  Waiting for component to start [4m]

Duplicate of https://github.com/openshift/odo/issues/2877

**Closed by amitkrout** 2020-04-23 09:37 UTC
Labels: kind/flake
