### ISSUE TITLE
README/nodejs example problems with current CDK/minishift 3.8

### ISSUE THREAD

**Issue by rctrh** [openshift/odo#1611] opened 2019-04-12 22:53 UTC
[kind/Documentation]

## What did you find missing in the documentation?

The current README/nodejs example doesn't work with the current release of CDK/minishift 3.8.  It's not clear to a new user whether this is an odo problem or a CDK/minishift problem.

1. The `odo create nodejs` step fails with the implied ":latest" tag.  The message is `image stream nodejs with tag latest not found in openshift and myproject namespaces`.   It works if you use `nodejs:8`. 

2. `docs/getting-started.md` shows a step to update the index.html and push again.  The error is about non-empty directories.

```
odo push
[1mPushing changes to component: nodejs-ex-nodejs-bofu[0m
 [32m✓[0m  Waiting for component to start
 [32m✓[0m  Copying files to component
 ◐  Building component [31m✗[0m  Unable to build files
+ set -eo pipefail
+ '[' '!' -z /opt/app-root/src ']'
+ '[' /tmp '!=' /opt/app-root/src ']'
+ '[' /opt/app-root/src '!=' /opt/app-root/src ']'
+ '[' -f /tmp/src/.s2i/bin/assemble ']'
+ '[' -n /usr/libexec/s2i ']'
+ rm -rf /opt/app-root/src/.git
+ /usr/libexec/s2i/assemble
---> Installing application source ...
mv: inter-device move failed: '/tmp/src/helm' to './helm'; unable to remove target: Directory not empty
mv: inter-device move failed: '/tmp/src/openshift' to './openshift'; unable to remove target: Directory not empty
mv: inter-device move failed: '/tmp/src/tests' to './tests'; unable to remove target: Directory not empty
mv: inter-device move failed: '/tmp/src/views' to './views'; unable to remove target: Directory not empty
```

## What is the relevance of it?

A new user is trying to follow the README or getting-started.md will fail.

**Comment by kadel** [comment] 2019-04-15 16:33
It looks like this might be something related to CDK.
I've tried to reproduce this on minishift v 1.32. and everything worked for me.

I'll try this later with CDK.

**Comment by rctrh** [comment] 2019-04-15 19:12
I switched to upstream mnishift 1.33 from github.    After I cleaned everything out and restarted everything this error on a subsequent push went away.  So I was able to follow the example. 

For CDK I was using the current release CDK 3.8 which includes minishift 1.31 and openshift 3.11

**Comment by amitkrout** [comment] 2019-04-16 08:16
@rctrh Hope your issue is resolved after using the upstream minishift bits. Can you close the issue or else let us know what improvement you need from odo side.

**Comment by rctrh** [comment] 2019-04-17 15:27
@amitkrout - While upstream using minishift did work around the issue for me.  The question is why didn't it work with CDK?   The minishift version difference is 1.31 vs. 1.33.  It would be good if someone else could try with CDK and see whether this was something isolated to my environment or not.

**Comment by rctrh** [comment] 2019-04-17 15:30
Note I originally labeled this a documentation issue which is probably incorrect unless there is a known mininum version of minishift that needs to be documented for odo to work.

**Comment by kadel** [comment] 2019-04-18 14:54
Odo doesn't control the s2i builder images, those come from OpenShift cluster, sadly different flavors of OpenShift can have a different set of build in images :-(

This is something that we will have to address at some point.

**Comment by girishramnani** [comment] 2020-01-02 10:24
We might not be able to do anything in terms of controlling the s2i builder images present in the cluster. Hence closing this issue for now.

**Closed by girishramnani** 2020-01-02 10:24 UTC
Labels: kind/bug, priority/Medium
