### ISSUE TITLE
nodejs-ex fails to copy local files into pod during odo push

### ISSUE THREAD

**Issue by theRemix** [openshift/odo#1702] opened 2019-05-07 23:27 UTC
[kind/bug]

## What versions of software are you using?
- Operating System: Windows 10 Pro
- Output of `odo version`:
    -  odo v1.0.0-beta1 (c226b008)
        Kubernetes: v1.11.0+d4cacc0

## How did you run odo exactly?

1. `minishift start`
1. `odo login`
1. `git clone https://github.com/openshift/nodejs-ex`
1. `cd nodejs-ex`
1. `odo create nodejs`
1. `odo push`

## Actual behavior

`odo push` fails, files from source directory do not get copied into pod

## Expected behavior

source files are copied from nodejs-ex directory into odo generated pod

## Any logs, error output, etc?

Error: 
```
 odo push
 V  Checking component
 V  Checking component version
 V  Creating nodejs component with name nodejs-xccu
 V  Initializing 'nodejs-xccu' component
 V  Creating component nodejs-xccu
 V  Successfully created component nodejs-xccu
 V  Applying component settings to component: nodejs-xccu
 V  The component nodejs-xccu was updated successfully
 V  Successfully updated component with name: nodejs-xccu
 V  Pushing changes to component: nodejs-xccu of type local
 V  Waiting for component to start
 V  Copying files to component
 <  Building component X  Unable to build files
+ set -eo pipefail
+ '[' '!' -z /opt/app-root/src ']'
+ '[' /tmp '!=' /opt/app-root/src ']'
+ '[' -n /opt/app-root/src-backup ']'
+ '[' '!' -d /opt/app-root/src-backup ']'
+ mkdir -p /opt/app-root/src-backup/src
+ rsync -rlO /tmp/src/. /opt/app-root/src-backup/src/
+ b_IFS='
'
+ b_OFS=
+ OIFS='
'
+ IFS='
'
++ ls -A /tmp/src/
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/.dummy
+ OIFS=
+ IFS='
'
+ '[' -n bucharestgold/centos7-s2i-nodejs ']'
+ '[' bucharestgold/centos7-s2i-nodejs == redhat-openjdk-18/openjdk18-openshift ']'
+ '[' -f /tmp/src/.s2i/bin/assemble ']'
+ '[' -n /usr/libexec/s2i ']'
+ rm -rf /opt/app-root/src/.git
+ /usr/libexec/s2i/assemble
---> Installing application source
---> Building your Node application from source
Current git config
url.https://github.com.insteadof=git@github.com:
url.https://.insteadof=ssh://
url.https://github.com.insteadof=ssh://git@github.com
---> Installing dependencies
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module './package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at [eval]:1:13
    at Script.runInThisContext (vm.js:96:20)
    at Object.runInThisContext (vm.js:303:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at evalScript (internal/bootstrap/node.js:582:27)

 X  Building component
 X  command terminated with exit code 1
```

contents of `.odo/config.yaml`

```yaml
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: nodejs
  SourceLocation: ./
  SourceType: local
  Application: app
  Project: myproject
  Name: nodejs-xccu
```

**Comment by amitkrout** [comment] 2019-05-09 16:05
I am able to reproduce it on win7 (Terminal - command prompt)

/kind bug
/priority major

**Comment by amitkrout** [comment] 2019-05-09 16:50
Seems path ./package.json is not parsed properly on windows platform

**Comment by kadel** [comment] 2019-05-16 11:32
I was also hitting this problem. But it looks like that with the recent changes in https://github.com/openshift/odo/issues/1702 this is no longer an issue.

@amitkrout can you please double check that https://github.com/openshift/odo/issues/1702 solves this problem?

**Comment by amitkrout** [comment] 2019-05-20 11:51
> I was also hitting this problem. But it looks like that with the recent changes in #1711 this is no longer an issue.
> 
> @amitkrout can you please double #1711 solves this problem?

Will check and update here

**Comment by amitkrout** [comment] 2019-05-20 11:58
@theRemix In the mean time can you check it using master bits or using ```v1.0.0-beta2``` bits 

NOTE: Shortly (Today) we are announcing v1.0.0-beta2 release.

**Comment by amitkrout** [comment] 2019-05-21 05:19
@theRemix I am not able to reproduce it on v1.0.0-beta2 windows bit [1] . Can you please check from your end and feel free close this if not reproducible. 

[1] https://github.com/openshift/odo/releases/tag/v1.0.0-beta2

**Comment by cdrage** [comment] 2019-05-22 13:37
We did do some changes to filepath / copying files over for both Windows / macOS / Linux support.

If you can try again and see if this issue has been resolved that'd be great @theRemix

**Comment by cdrage** [comment] 2019-06-06 18:03
I'm going to close this for now as we're unable to replicate. If it's still an issue, can you please re-open this @theRemix ? Thanks!

**Closed by cdrage** 2019-06-06 18:03 UTC
Labels: kind/bug, os/windows, priority/High, state/In Analysis
