### ISSUE TITLE
[FLAKE] Unit test on windows throws error of "Windows system assumed buffer larger than it is"

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#3227] opened 2020-05-21 06:13 UTC
/kind bug

## What versions of software are you using?

**Operating System:**
Windows

**Output of `odo version`:**
master

## How did you run odo exactly?

`make test` on travis CI

## Actual behavior

```
$ make test
go test  -race github.com/openshift/odo/cmd/cli-doc github.com/openshift/odo/cmd/odo github.com/openshift/odo/pkg/application github.com/openshift/odo/pkg/application/labels github.com/openshift/odo/pkg/auth github.com/openshift/odo/pkg/catalog github.com/openshift/odo/pkg/component github.com/openshift/odo/pkg/component/labels github.com/openshift/odo/pkg/config 
[...]
?   	github.com/openshift/odo/pkg/version	[no test files]
Waiting for something to change in C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis304253363
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis304253363\__init__.py736347914 changed
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis304253363\src943245174\read_licenses.py183600037 changed
Pushing files...
Waiting for something to change in C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis945225503
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis945225503\__init__.py796944198 changed
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis945225503\src103079922\read_licenses.py901001585 changed
Pushing files...
Waiting for something to change in C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis659762891
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis659762891\__init__.py858530498 changed
Pushing files...
Waiting for something to change in C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis673372855
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis673372855\__init__.py594055550 changed
Pushing files...
Waiting for something to change in C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis680713443
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis680713443\__init__.py234713173 changed
Pushing files...
Waiting for something to change in C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis556044623
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis556044623\__init__.py231248161 changed
Pushing files...
Waiting for something to change in C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003
Waiting for something to change in C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis641258778
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis641258778\__init__.py943711364 changed
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis641258778\bin648676438 changed
Pushing files...
Waiting for something to change in C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis398021565
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis398021565\__init__.py010425554 changed
Pushing files...
Waiting for something to change in C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis605650900
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis605650900\__init__.py268760213 changed
Pushing files...
--- FAIL: TestWatchAndPush (26.22s)
    watch_test.go:724: Running test:  Case 1: Valid watch with list of files to be ignored with a append event
    watch_test.go:724: Running test:  (Experimental mode on) Case 1: Valid watch with list of files to be ignored with a append event
    watch_test.go:724: Running test:  Case 2: Valid watch with list of files to be ignored with a append and a delete event
    watch_test.go:724: Running test:  (Experimental mode on) Case 2: Valid watch with list of files to be ignored with a append and a delete event
    watch_test.go:724: Running test:  Case 3: Valid watch with list of files to be ignored with a create and a delete event
    watch_test.go:724: Running test:  (Experimental mode on) Case 3: Valid watch with list of files to be ignored with a create and a delete event
    watch_test.go:724: Running test:  Case 4: Valid watch with list of files to be ignored with a folder create event
    --- FAIL: TestWatchAndPush/Case_4:_Valid_watch_with_list_of_files_to_be_ignored_with_a_folder_create_event (1.01s)
        watch_test.go:748: Done with basePath creation and client init will trigger WatchAndPush and file modifications next...
            map[.git:{FilePath:.git704782336 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003 FileType:1 ModificationType:create} LICENSE:{FilePath:LICENSE299005791 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003 FileType:0 ModificationType:create} src:{FilePath:src284824350 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003 FileType:1 ModificationType:create} src\__init__.py:{FilePath:__init__.py026442546 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003\src284824350 FileType:0 ModificationType:create} src\main.py:{FilePath:main.py510970601 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003\src284824350 FileType:0 ModificationType:create} src\read_licenses.py:{FilePath:read_licenses.py142415494 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003\src284824350 FileType:0 ModificationType:create} tests:{FilePath:tests134619621 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003 FileType:1 ModificationType:create} tests\__init__.py:{FilePath:__init__.py778375988 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003\tests134619621 FileType:0 ModificationType:create} tests\test1.py:{FilePath:test1.py715384579 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003\tests134619621 FileType:0 ModificationType:create}]
        watch_test.go:797: Starting WatchAndPush now
        watch_test.go:751: Starting file simulations 
            [{FilePath:__init__.py FileParent: FileType:0 ModificationType:create} {FilePath:read_licenses.py FileParent:src FileType:0 ModificationType:delete} {FilePath:test_read_licenses.py FileParent:tests FileType:0 ModificationType:create} {FilePath:tests FileParent: FileType:1 ModificationType:delete} {FilePath:bin FileParent: FileType:1 ModificationType:create}]
        watch_test.go:788: The CompDirStructure is 
            map[.git:{FilePath:.git704782336 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003 FileType:1 ModificationType:create} LICENSE:{FilePath:LICENSE299005791 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003 FileType:0 ModificationType:create} __init__.py:{FilePath:__init__.py573619757 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003 FileType:1 ModificationType:create} bin:{FilePath:bin044949735 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003 FileType:1 ModificationType:create} src:{FilePath:src284824350 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003 FileType:1 ModificationType:create} src\__init__.py:{FilePath:__init__.py026442546 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003\src284824350 FileType:0 ModificationType:create} src\main.py:{FilePath:main.py510970601 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003\src284824350 FileType:0 ModificationType:create} src\read_licenses.py:{FilePath:read_licenses.py142415494 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003\src284824350 FileType:0 ModificationType:create} tests:{FilePath:tests134619621 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003 FileType:1 ModificationType:create} tests\__init__.py:{FilePath:__init__.py778375988 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003\tests134619621 FileType:0 ModificationType:create} tests\test1.py:{FilePath:test1.py715384579 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003\tests134619621 FileType:0 ModificationType:create} tests\test_read_licenses.py:{FilePath:test_read_licenses.py145252776 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis124843003\tests134619621 FileType:1 ModificationType:create}]
        watch_test.go:823: error in WatchAndPush error watching filesystem for changes: Windows system assumed buffer larger than it is, events have likely been missed.
    watch_test.go:724: Running test:  (Experimental mode on) Case 4: Valid watch with list of files to be ignored with a folder create event
    watch_test.go:724: Running test:  Case 5: Valid watch with list of files to be ignored with a folder delete event
    watch_test.go:724: Running test:  (Experimental mode on) Case 5: Valid watch with list of files to be ignored with a folder delete event
FAIL
FAIL	github.com/openshift/odo/pkg/watch	26.529s
FAIL
The command "make test" exited with 2.
```

## Expected behavior

`make test` should run successfully on window.

Note : I suspect `error in WatchAndPush error watching filesystem for changes: Windows system assumed buffer larger than it is, events have likely been missed` occurs due to buffer value fluctuation on windows driver and it has not been handled properly in fsnotify library https://github.com/fsnotify/fsnotify/blob/master/windows.go#L506 I guess.

## Any logs, error output, etc?

Detail logs : https://travis-ci.com/github/openshift/odo/jobs/337120311#L201

**Comment by prietyc123** [comment] 2020-05-21 06:20
One more occurence : https://travis-ci.com/github/openshift/odo/jobs/337411640#L248

**Comment by amitkrout** [comment] 2020-05-27 11:05
On the day the issue is created we hit it couple of times after that we have observed it none of the time till today.

**Comment by mik-dass** [comment] 2020-05-27 13:51
> On the day the issue is created we hit it couple of times after that we have observed it none of the time till today.

Yes. Still let's keep it open for some more days and observe.

**Comment by prietyc123** [comment] 2020-08-24 08:11
Again we are hitting this issue very frequently. I can see it as blocker for devfile v2 as hitting on all the prs 

```
$ make test
go test  -race github.com/openshift/odo/cmd/cli-doc github.com/openshift/odo/cmd/odo github.com/openshift/odo/pkg/application github.com/openshift/odo/pkg/application/labels github.com/openshift/odo/pkg/auth github.com/openshift/odo/pkg/catalog github.com/openshift/odo/pkg/component github.com/openshift/odo/pkg/component/labels github.com/openshift/odo/pkg/config github.com/openshift/odo/pkg/debug github.com/openshift/odo/pkg/devfile github.com/openshift/odo/pkg/devfile/adapters 
[...]
ok  	github.com/openshift/odo/pkg/util	1.350s
?   	github.com/openshift/odo/pkg/version	[no test files]
Waiting for something to change in C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis285911911
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis285911911\__init__.py261915502 changed
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis285911911\src391360922\read_licenses.py672741881 changed
Pushing files...
Component is running in debug mode
Please start port-forwarding in a different terminal
Waiting for something to change in C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis729058451
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis729058451\__init__.py941700202 changed
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis729058451\src821039318\read_licenses.py080877445 changed
Pushing files...
Waiting for something to change in C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis047875583
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis047875583\__init__.py407856806 changed
Pushing files...
Waiting for something to change in C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis756843947
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis756843947\__init__.py258151458 changed
Pushing files...
Waiting for something to change in C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis203809175
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis203809175\__init__.py248433577 changed
Pushing files...
Waiting for something to change in C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis555602371
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis555602371\__init__.py897829429 changed
Pushing files...
Waiting for something to change in C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis944698927
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis944698927\__init__.py483789057 changed
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis944698927\bin960300763 changed
Pushing files...
Waiting for something to change in C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974
Waiting for something to change in C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis372895121
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis372895121\__init__.py604486582 changed
Pushing files...
Waiting for something to change in C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis803015768
File C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis803015768\__init__.py470518761 changed
Pushing files...
--- FAIL: TestWatchAndPush (23.37s)
    watch_test.go:734: Running test:  Case 1: Valid watch with list of files to be ignored with a append event
    watch_test.go:734: Running test:  (Experimental mode on) Case 1: Valid watch with list of files to be ignored with a append event
    watch_test.go:734: Running test:  Case 2: Valid watch with list of files to be ignored with a append and a delete event
    watch_test.go:734: Running test:  (Experimental mode on) Case 2: Valid watch with list of files to be ignored with a append and a delete event
    watch_test.go:734: Running test:  Case 3: Valid watch with list of files to be ignored with a create and a delete event
    watch_test.go:734: Running test:  (Experimental mode on) Case 3: Valid watch with list of files to be ignored with a create and a delete event
    watch_test.go:734: Running test:  Case 4: Valid watch with list of files to be ignored with a folder create event
    watch_test.go:734: Running test:  (Experimental mode on) Case 4: Valid watch with list of files to be ignored with a folder create event
    --- FAIL: TestWatchAndPush/(Experimental_mode_on)_Case_4:_Valid_watch_with_list_of_files_to_be_ignored_with_a_folder_create_event (1.01s)
        watch_test.go:760: Done with basePath creation and client init will trigger WatchAndPush and file modifications next...
            map[.git:{FilePath:.git019872831 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974 FileType:1 ModificationType:create} LICENSE:{FilePath:LICENSE294778002 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974 FileType:0 ModificationType:create} src:{FilePath:src438629317 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974 FileType:1 ModificationType:create} src\__init__.py:{FilePath:__init__.py756888777 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974\src438629317 FileType:0 ModificationType:create} src\main.py:{FilePath:main.py577169812 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974\src438629317 FileType:0 ModificationType:create} src\read_licenses.py:{FilePath:read_licenses.py375589901 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974\src438629317 FileType:0 ModificationType:create} tests:{FilePath:tests231702624 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974 FileType:1 ModificationType:create} tests\__init__.py:{FilePath:__init__.py799586275 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974\tests231702624 FileType:0 ModificationType:create} tests\test1.py:{FilePath:test1.py971680742 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974\tests231702624 FileType:0 ModificationType:create}]
        watch_test.go:809: Starting WatchAndPush now
        watch_test.go:763: Starting file simulations 
            [{FilePath:__init__.py FileParent: FileType:0 ModificationType:create} {FilePath:read_licenses.py FileParent:src FileType:0 ModificationType:delete} {FilePath:test_read_licenses.py FileParent:tests FileType:0 ModificationType:create} {FilePath:tests FileParent: FileType:1 ModificationType:delete} {FilePath:bin FileParent: FileType:1 ModificationType:create}]
        watch_test.go:800: The CompDirStructure is 
            map[.git:{FilePath:.git019872831 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974 FileType:1 ModificationType:create} LICENSE:{FilePath:LICENSE294778002 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974 FileType:0 ModificationType:create} __init__.py:{FilePath:__init__.py893793800 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974 FileType:1 ModificationType:create} bin:{FilePath:bin637617274 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974 FileType:1 ModificationType:create} src:{FilePath:src438629317 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974 FileType:1 ModificationType:create} src\__init__.py:{FilePath:__init__.py756888777 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974\src438629317 FileType:0 ModificationType:create} src\main.py:{FilePath:main.py577169812 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974\src438629317 FileType:0 ModificationType:create} src\read_licenses.py:{FilePath:read_licenses.py375589901 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974\src438629317 FileType:0 ModificationType:create} tests:{FilePath:tests231702624 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974 FileType:1 ModificationType:create} tests\__init__.py:{FilePath:__init__.py799586275 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974\tests231702624 FileType:0 ModificationType:create} tests\test1.py:{FilePath:test1.py971680742 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974\tests231702624 FileType:0 ModificationType:create} tests\test_read_licenses.py:{FilePath:test_read_licenses.py661753799 FileParent:C:\Users\travis\AppData\Local\Temp\fabric8-analytics-license-analysis382286974\tests231702624 FileType:1 ModificationType:create}]
        watch_test.go:845: error in WatchAndPush error watching filesystem for changes: Windows system assumed buffer larger than it is, events have likely been missed.
    watch_test.go:734: Running test:  Case 5: Valid watch with list of files to be ignored with a folder delete event
    watch_test.go:734: Running test:  (Experimental mode on) Case 5: Valid watch with list of files to be ignored with a folder delete event
FAIL
FAIL	github.com/openshift/odo/pkg/watch	23.667s
FAIL
The command "make test" exited with 2.
Skipping the after_success step, as specified in the configuration.
Done. Your build exited with 1.
make: *** [Makefile:157: test] Error 1
```

**Comment by girishramnani** [comment] 2020-08-24 14:23
lets verify this locally on windows

**Comment by prietyc123** [comment] 2020-08-27 10:54
I ran it more than 20 times on windows but none of the time I was able to reproduce this issue locally.

```
> make test
go test  -race github.com/openshift/odo github.com/openshift/odo/cmd/cli-doc github.com/openshift/odo/cmd/odo github.com/openshift/odo/pkg/application github.com/openshift/odo/pkg/application/labels github.com/openshift/odo/pkg/auth github.com/openshift/odo/pkg/catalog github.com/openshift/odo/pkg/component github.com/openshift/odo/pkg/component/labels github.com/openshift/odo/pkg/config github.com/openshift/odo/pkg/debug github.com/openshift/odo/pkg/devfile github.com/openshift/odo/pkg/devfile/adapters github.com/openshift/odo/pkg/devfile/adapters/common github.com/openshift/odo/pkg/devfile/adapters/docker github.com/openshift/odo/pkg/devfile/adapters/docker/component github.com/openshift/odo/pkg/devfile/adapters/docker/storage github.com/openshift/odo/pkg/devfile/adapters/docker/utils github.com/openshift/odo/pkg/devfile/adapters/kubernetes github.com/openshift/odo/pkg/devfile/adapters/kubernetes/component github.com/openshift/odo/pkg/devfile/adapters/kubernetes/storage github.com/openshift/odo/pkg/devfile/adapters/kubernetes/utils github.com/openshift/odo/pkg/devfile/parser github.com/openshift/odo/pkg/devfile/parser/context github.com/openshift/odo/pkg/devfile/parser/data github.com/openshift/odo/pkg/devfile/parser/data/1.0.0 github.com/openshift/odo/pkg/devfile/parser/data/2.0.0 github.com/openshift/odo/pkg/devfile/parser/data/common github.com/openshift/odo/pkg/devfile/validate github.com/openshift/odo/pkg/envinfo github.com/openshift/odo/pkg/kclient github.com/openshift/odo/pkg/kclient/fake github.com/openshift/odo/pkg/lclient github.com/openshift/odo/pkg/log github.com/openshift/odo/pkg/log/fidget github.com/openshift/odo/pkg/machineoutput github.com/openshift/odo/pkg/notify github.com/openshift/odo/pkg/occlient github.com/openshift/odo/pkg/odo/cli github.com/openshift/odo/pkg/odo/cli/application github.com/openshift/odo/pkg/odo/cli/catalog github.com/openshift/odo/pkg/odo/cli/catalog/describe github.com/openshift/odo/pkg/odo/cli/catalog/list github.com/openshift/odo/pkg/odo/cli/catalog/search github.com/openshift/odo/pkg/odo/cli/catalog/util github.com/openshift/odo/pkg/odo/cli/component github.com/openshift/odo/pkg/odo/cli/component/ui github.com/openshift/odo/pkg/odo/cli/config github.com/openshift/odo/pkg/odo/cli/debug github.com/openshift/odo/pkg/odo/cli/env github.com/openshift/odo/pkg/odo/cli/login github.com/openshift/odo/pkg/odo/cli/logout github.com/openshift/odo/pkg/odo/cli/plugins github.com/openshift/odo/pkg/odo/cli/preference github.com/openshift/odo/pkg/odo/cli/project github.com/openshift/odo/pkg/odo/cli/registry github.com/openshift/odo/pkg/odo/cli/registry/util github.com/openshift/odo/pkg/odo/cli/service github.com/openshift/odo/pkg/odo/cli/service/ui github.com/openshift/odo/pkg/odo/cli/storage github.com/openshift/odo/pkg/odo/cli/ui github.com/openshift/odo/pkg/odo/cli/url github.com/openshift/odo/pkg/odo/cli/utils github.com/openshift/odo/pkg/odo/cli/version github.com/openshift/odo/pkg/odo/genericclioptions github.com/openshift/odo/pkg/odo/util github.com/openshift/odo/pkg/odo/util/completion github.com/openshift/odo/pkg/odo/util/experimental github.com/openshift/odo/pkg/odo/util/pushtarget github.com/openshift/odo/pkg/odo/util/validation github.com/openshift/odo/pkg/preference github.com/openshift/odo/pkg/project github.com/openshift/odo/pkg/secret github.com/openshift/odo/pkg/service github.com/openshift/odo/pkg/storage github.com/openshift/odo/pkg/storage/labels github.com/openshift/odo/pkg/sync github.com/openshift/odo/pkg/testingutil github.com/openshift/odo/pkg/testingutil/filesystem github.com/openshift/odo/pkg/url github.com/openshift/odo/pkg/url/labels github.com/openshift/odo/pkg/util github.com/openshift/odo/pkg/version github.com/openshift/odo/pkg/watch
?   	github.com/openshift/odo	[no test files]
?   	github.com/openshift/odo/cmd/cli-doc	[no test files]
?   	github.com/openshift/odo/cmd/odo	[no test files]
ok  	github.com/openshift/odo/pkg/application	(cached)
ok  	github.com/openshift/odo/pkg/application/labels	(cached)
?   	github.com/openshift/odo/pkg/auth	[no test files]
ok  	github.com/openshift/odo/pkg/catalog	(cached)
ok  	github.com/openshift/odo/pkg/component	(cached)
ok  	github.com/openshift/odo/pkg/component/labels	(cached)
ok  	github.com/openshift/odo/pkg/config	(cached)
ok  	github.com/openshift/odo/pkg/debug	(cached)
?   	github.com/openshift/odo/pkg/devfile	[no test files]
ok  	github.com/openshift/odo/pkg/devfile/adapters	(cached)
ok  	github.com/openshift/odo/pkg/devfile/adapters/common	(cached)
?   	github.com/openshift/odo/pkg/devfile/adapters/docker	[no test files]
ok  	github.com/openshift/odo/pkg/devfile/adapters/docker/component	(cached)
ok  	github.com/openshift/odo/pkg/devfile/adapters/docker/storage	(cached)
ok  	github.com/openshift/odo/pkg/devfile/adapters/docker/utils	(cached)
?   	github.com/openshift/odo/pkg/devfile/adapters/kubernetes	[no test files]
ok  	github.com/openshift/odo/pkg/devfile/adapters/kubernetes/component	(cached)
ok  	github.com/openshift/odo/pkg/devfile/adapters/kubernetes/storage	(cached)
ok  	github.com/openshift/odo/pkg/devfile/adapters/kubernetes/utils	(cached)
ok  	github.com/openshift/odo/pkg/devfile/parser	(cached)
ok  	github.com/openshift/odo/pkg/devfile/parser/context	(cached)
ok  	github.com/openshift/odo/pkg/devfile/parser/data	(cached)
?   	github.com/openshift/odo/pkg/devfile/parser/data/1.0.0	[no test files]
ok  	github.com/openshift/odo/pkg/devfile/parser/data/2.0.0	(cached)
ok  	github.com/openshift/odo/pkg/devfile/parser/data/common	(cached)
ok  	github.com/openshift/odo/pkg/devfile/validate	(cached)
ok  	github.com/openshift/odo/pkg/envinfo	(cached)
ok  	github.com/openshift/odo/pkg/kclient	(cached)
?   	github.com/openshift/odo/pkg/kclient/fake	[no test files]
ok  	github.com/openshift/odo/pkg/lclient	(cached)
?   	github.com/openshift/odo/pkg/log	[no test files]
?   	github.com/openshift/odo/pkg/log/fidget	[no test files]
?   	github.com/openshift/odo/pkg/machineoutput	[no test files]
ok  	github.com/openshift/odo/pkg/notify	(cached) [no tests to run]
ok  	github.com/openshift/odo/pkg/occlient	(cached)
?   	github.com/openshift/odo/pkg/odo/cli	[no test files]
?   	github.com/openshift/odo/pkg/odo/cli/application	[no test files]
?   	github.com/openshift/odo/pkg/odo/cli/catalog	[no test files]
?   	github.com/openshift/odo/pkg/odo/cli/catalog/describe	[no test files]
?   	github.com/openshift/odo/pkg/odo/cli/catalog/list	[no test files]
?   	github.com/openshift/odo/pkg/odo/cli/catalog/search	[no test files]
ok  	github.com/openshift/odo/pkg/odo/cli/catalog/util	(cached)
?   	github.com/openshift/odo/pkg/odo/cli/component	[no test files]
?   	github.com/openshift/odo/pkg/odo/cli/component/ui	[no test files]
?   	github.com/openshift/odo/pkg/odo/cli/config	[no test files]
?   	github.com/openshift/odo/pkg/odo/cli/debug	[no test files]
ok  	github.com/openshift/odo/pkg/odo/cli/env	(cached)
?   	github.com/openshift/odo/pkg/odo/cli/login	[no test files]
?   	github.com/openshift/odo/pkg/odo/cli/logout	[no test files]
?   	github.com/openshift/odo/pkg/odo/cli/plugins	[no test files]
?   	github.com/openshift/odo/pkg/odo/cli/preference	[no test files]
?   	github.com/openshift/odo/pkg/odo/cli/project	[no test files]
?   	github.com/openshift/odo/pkg/odo/cli/registry	[no test files]
ok  	github.com/openshift/odo/pkg/odo/cli/registry/util	(cached)
ok  	github.com/openshift/odo/pkg/odo/cli/service	(cached)
ok  	github.com/openshift/odo/pkg/odo/cli/service/ui	(cached)
ok  	github.com/openshift/odo/pkg/odo/cli/storage	(cached)
?   	github.com/openshift/odo/pkg/odo/cli/ui	[no test files]
?   	github.com/openshift/odo/pkg/odo/cli/url	[no test files]
ok  	github.com/openshift/odo/pkg/odo/cli/utils	(cached)
?   	github.com/openshift/odo/pkg/odo/cli/version	[no test files]
?   	github.com/openshift/odo/pkg/odo/genericclioptions	[no test files]
ok  	github.com/openshift/odo/pkg/odo/util	(cached)
ok  	github.com/openshift/odo/pkg/odo/util/completion	(cached)
ok  	github.com/openshift/odo/pkg/odo/util/experimental	(cached)
ok  	github.com/openshift/odo/pkg/odo/util/pushtarget	(cached)
ok  	github.com/openshift/odo/pkg/odo/util/validation	(cached)
ok  	github.com/openshift/odo/pkg/preference	(cached)
ok  	github.com/openshift/odo/pkg/project	(cached)
ok  	github.com/openshift/odo/pkg/secret	(cached)
ok  	github.com/openshift/odo/pkg/service	(cached)
ok  	github.com/openshift/odo/pkg/storage	(cached)
ok  	github.com/openshift/odo/pkg/storage/labels	(cached)
ok  	github.com/openshift/odo/pkg/sync	(cached)
ok  	github.com/openshift/odo/pkg/testingutil	(cached)
?   	github.com/openshift/odo/pkg/testingutil/filesystem	[no test files]
ok  	github.com/openshift/odo/pkg/url	(cached)
ok  	github.com/openshift/odo/pkg/url/labels	(cached)
ok  	github.com/openshift/odo/pkg/util	(cached)
?   	github.com/openshift/odo/pkg/version	[no test files]
ok  	github.com/openshift/odo/pkg/watch	(cached)
```

**Comment by mik-dass** [comment] 2020-08-27 13:17
> ok  	github.com/openshift/odo/pkg/watch	(cached)

It seems to be using the cached version. You need to use `-count=1` for the watch test.

**Comment by prietyc123** [comment] 2020-11-03 08:56
@mik-dass It seems we are hitting the same issue here - https://travis-ci.com/github/openshift/odo/jobs/423956022#L697-L761

**Comment by mik-dass** [comment] 2020-11-03 09:03
> @mik-dass It seems we are hitting the same issue here - https://travis-ci.com/github/openshift/odo/jobs/423956022#L697-L761
 
Please check if you can reproduce this locally using the steps mentioned here https://github.com/openshift/odo/issues/3227#issuecomment-681943059

**Comment by mik-dass** [comment] 2021-02-01 19:27
@prietyc123 Since we no longer test on Travis CI, I think we can close this.

**Closed** 2021-04-03 00:03 UTC
Labels: area/Windows, area/testing, kind/flake, lifecycle/rotten, priority/Medium
