### ISSUE TITLE
[Devfile] `odo url list` doesn't list routes created by odo

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#3064] opened 2020-05-01 18:57 UTC
/kind bug

When odo creates routes on OpenShift clusters for devfile components, those URLs do not show up when `odo url list` is ran. But on a generic Kube cluster, those ingress resources do show up.

```
Johns-MacBook-Pro-3:nodejs johncollier$ odo url create
 ✓  URL nodejs-3000 created for component: nodejs

To apply the URL configuration changes, please use `odo push`
Johns-MacBook-Pro-3:nodejs johncollier$ odo push

Validation
 ✓  Validating the devfile [72145ns]

Creating Kubernetes resources for component nodejs
 ✓  Waiting for component to start [118ms]

Applying URL changes
 ✓  URL nodejs-3000: http://nodejs-3000-kabanero.apps.codewind.os.fyre.ibm.com created

Syncing to component nodejs
 ✓  Checking file changes for pushing [1ms]
 ✓  No file changes detected, skipping build. Use the '-f' flag to force the build.

Pushing devfile component nodejs
 ✓  Changes successfully pushed to component
Johns-MacBook-Pro-3:nodejs johncollier$ odo url list
 ✗  no URLs found for component nodejs
```

**Comment by mik-dass** [comment] 2020-05-04 14:39
duplicate of https://github.com/openshift/odo/issues/2985
/close

**Closed** 2020-05-04 14:40 UTC
Labels: area/devfile, area/url, kind/bug, priority/High
