### ISSUE TITLE
Consecutive service link/unlink doesn't work properly on CI

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#3834] opened 2020-08-26 07:32 UTC
/kind bug

## What versions of software are you using?

**Operating System:**
CI setup

**Output of `odo version`:**
master

## How did you run odo exactly?

Steps https://github.com/openshift/odo/blob/master/tests/integration/operatorhub/cmd_service_test.go#L410-L451 .
It is blocking our periodic job https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/?type=periodic&job=periodic-*odo* to execute the further steps.

## Actual behavior

```
Running oc with args [oc get pods -n jpixazxsbf]
[oc] NAME                      READY   STATUS     RESTARTS   AGE
[oc] example-twl2jnlppr        0/1     Init:0/1   0          1s
[oc] fdyvbw-67d8796b84-tklqd   1/1     Running    0          17s
Running oc with args [oc get pods example-twl2jnlppr -o template="{{.status.phase}}" -n jpixazxsbf]
[...]
[oc] "Pending"Running oc with args [oc get pods example-twl2jnlppr -o template="{{.status.phase}}" -n jpixazxsbf]

[oc] "Running"Running odo with args [odo link EtcdCluster/example]
[...]
[odo] I0826 02:50:11.625555    1736 preference.go:209] The path for preference file is /tmp/artifacts/.odo/preference.yaml
[odo]  ✓  Successfully created link between component "fdyvbw" and service "EtcdCluster/example"
[odo] 
[odo] To apply the link, please use `odo push`
[odo] I0826 02:50:11.711230    1736 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)

Running odo with args [odo link EtcdCluster/example]
[...]
[odo] I0826 02:50:12.716273    1755 preference.go:209] The path for preference file is /tmp/artifacts/.odo/preference.yaml
[odo]  ✗  component "fdyvbw" is already linked with the service "EtcdCluster/example"
[odo] 

Running odo with args [odo unlink EtcdCluster/example]
[...]
[odo] I0826 02:50:13.815048    1777 preference.go:209] The path for preference file is /tmp/artifacts/.odo/preference.yaml
[odo] I0826 02:50:13.815261    1777 operators.go:26] Fetching list of operators installed in cluster
[odo]  ✓  Successfully unlinked component "fdyvbw" from service "EtcdCluster/example"
[odo] 
[odo] To apply the changes, please use `odo push`
[odo] I0826 02:50:13.978482    1777 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)

Running odo with args [odo unlink EtcdCluster/example]
[...]
[odo] I0826 02:50:14.747007    1799 service.go:454] Getting instances of: etcdclusters.etcd.database.coreos.com
[odo]  ✗  failed to unlink the service "EtcdCluster/example" since it's not linked with the component "fdyvbw"

Running odo with args [odo link EtcdCluster/example]
[...]
[odo] I0826 02:50:15.807856    1819 preference.go:209] The path for preference file is /tmp/artifacts/.odo/preference.yaml
[odo]  ✗  component "fdyvbw" is already linked with the service "EtcdCluster/example"
[odo] 

Deleting project: jpixazxsbf
Running odo with args [odo project delete jpixazxsbf -f]
[odo] I0826 02:50:15.981741    1841 util.go:734] HTTPGetRequest: https://raw.githubusercontent.com/openshift/odo/master/build/VERSION
[odo] I0826 02:50:15.982020    1841 util.go:755] Response will be cached in /tmp/odohttpcache for 1h0m0s
[odo] I0826 02:50:15.984168    1841 util.go:768] Cached response used.
[odo]  ⚠  Warning! Projects are deleted from the cluster asynchronously. Odo does its best to delete the project. Due to multi-tenant clusters, the project may still exist on a different node.
[odo] I0826 02:50:16.609738    1841 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)
[odo]  ✓  Deleted project : jpixazxsbf
Setting current dir to: /go/src/github.com/openshift/odo/tests/integration/operatorhub
Deleting dir: /tmp/171882053
------------------------------
• Failure [109.251 seconds]
odo service command tests for OperatorHub
/go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:17
  When linking devfile component with Operator backed service
  /go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:360
    should successfully connect and disconnect a component with an existing service [It]
    /go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:410
    No future change is possible.  Bailing out early after 1.060s.
      
    Running odo with args [odo link EtcdCluster/example]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
```

## Expected behavior

I suspect the services link and unlink status are not handled properly.

## Any logs, error output, etc?

detailed logs: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-odo-master-v4.2-integration-e2e-periodic/1298409952288706560#1:build-log.txt%3A1119

**Comment by prietyc123** [comment] 2020-08-26 07:33
ping @dharmit

**Comment by amitkrout** [comment] 2020-08-26 07:35
Tried locally three times and none of the times i am able to reproduce it. May be in the CI link and unlink works bit slow causing such race condition.

**Comment by dharmit** [comment] 2020-08-26 09:09
Unlink was added in #3561. Since the PR got merged only after clearing the CI checks, I'm sceptical about this being an issue with the code.

> May be in the CI link and unlink works bit slow causing such race condition.

This sounds more plausible. Since `odo link` and `odo unlink` require `odo push` for the underlying deployment to actually take effect, I'm adding `helper.CmdShouldPass("odo", "push")` in the test. This should provide more than enough time between the calls.

**Comment by dharmit** [comment] 2020-08-26 09:21
From the conversation so far, I don't think this issue is a bug in the code. Removing the label.

**Comment by prietyc123** [comment] 2020-08-26 09:46
> Since odo link and odo unlink require odo push for the underlying deployment to actually take effect, I'm adding helper.CmdShouldPass("odo", "push") in the test. This should provide more than enough time between the calls.

TBH I got confused with the statement. There are two contradictory statement
- We are doing `odo push` for changes to reflect
or
- Providing time interval between the calls
@dharmit Can you please clarify these two points.

**Comment by dharmit** [comment] 2020-08-26 09:52
> 
> TBH I got confused with the statement. There are two contradictory statement
> 
>   * We are doing `odo push` for changes to reflect
>       or
> 
>   * Providing time interval between the calls

For the sake of testing, we don't actually need to do `odo push` for the underlying component's "Deployment" on OCP to reflect the true state. This is because we're relying on odo's behaviour based on `.odo/env/env.yaml` for things being tested. However, since we're facing the problem you've mentioned in the issue, adding some timeout between the calls should help.

**Closed** 2020-08-28 00:18 UTC
Labels: priority/High
