### ISSUE TITLE
First push of long-running build fails to start the Java program in the pod

### ISSUE THREAD

**Issue by apupier** [openshift/odo#1430] opened 2019-03-06 09:39 UTC
[kind/bug]

## What versions of software are you using?
- Operating System: Windows 10
- Output of `odo version`:
odo v0.0.20 (bd3e74a4)
Server: https://172.18.93.45:8443
Kubernetes: v1.11.0+d4cacc0

## How did you run odo exactly?
using VS Code OpenShift connector

## Actual behavior

using VS Code OpenShift connector extension.
- create project https://github.com/jboss-fuse/fuse-rest-http-booster/tree/v7.2.0-redhat-01
- create a component with "java" component type and using the local workspace folder
- wait that the build is finished
- go to pod log and notice that there is no SpringBoot application started

if we try to do another push, the application is well started

## Expected behavior

when build is finished, the jar is found in /deployments and the application is available

## Any logs, error output, etc?

the pod logs is showing several errors of not finding any jars in /deployments. Before the build has finished, there is no more logs that are incoming. Looks alike it doesn't try to start the jar anymore.

**Comment by kadel** [comment] 2019-03-20 08:58
I've tried to reproduce this, but so far no luck :-(

**Comment by apupier** [comment] 2019-03-21 08:34
I tried again and reproduced.
You can see it in the first 3' of this video

**Comment by kadel** [comment] 2019-04-03 08:08
It looks like the issue here is that vscode creates a component and right after it is created it does push. 
There is nothing wrong with this behavior. 

Problem is that when you have a slow cluster, it can take a while to start a Pod, especially when the cluster has to download s2i image and initContainer image.

odo 0.0.20 waits 2 minutes for the Pod to be ready. In the master, this has been changed to 4 minutes.

We should make this configurable so users can adjust it according to their needs.

**Comment by amitkrout** [comment] 2019-04-03 11:56
> I tried again and reproduced.
> You can see it in the first 3' of this video https://drive.google.com/open?id=1v_-0kKtKbdYczrOmaaJx2q-uv1emX1DF

I am able to reproduce it on windows

**Comment by kadel** [comment] 2019-05-20 11:54
We need to make [`waitForPodTimeOut `](https://github.com/openshift/odo/blob/ffcde3baa0512cab0004e8ef2ea7a994e7d08150/pkg/occlient/occlient.go#L103:2) configureable using `odo preferences`.

**Comment by dharmit** [comment] 2019-06-06 10:33
I'm trying to reproduce this using the video uploaded earlier. However, I'm facing a few issues:
- I'm being forced to install `odo v0.0.20` by vscode-openshift-tools in spite of having `odo v1.0.0-beta2` in `~/bin/` which is included in `$PATH`.
- There are more options for `fuse` than those in the video so I chose `fuse redhat720` based on the project tree mentioned in issue https://github.com/jboss-fuse/fuse-rest-http-booster/tree/v7.2.0-redhat-01
- When I try to create a new component in `myproject`, I can't find a component type `java` as shown in the video. This makes sense as the list is same as the output of `odo catalog list components`

I'm a bit lost as to how to proceed further with reproducing this. Based on https://github.com/openshift/odo/issues/1430#issuecomment-493954859, we need to make `waitForPodTimeout` configurable. Looking through the comments, pod timeout seems to be the root cause for the issue.

Should I not spend time reproducing this and instead work on making this parameter configurable?

What do you suggest @kadel @girishramnani ?

**Comment by kadel** [comment] 2019-06-07 12:36
> I'm a bit lost as to how to proceed further with reproducing this. Based on [#1430 (comment)](https://github.com/openshift/odo/issues/1430#issuecomment-493954859), we need to make `waitForPodTimeout` configurable. Looking through the comments, pod timeout seems to be the root cause for the issue.

the best way to reproduce this might be to actually try to lower that timeout and see if you can get the same error

**Comment by dharmit** [comment] 2019-06-13 10:57
And now, following the video uploaded above, things fail with:
```bash
$ odo push comp --app fuse --project myproject --local /home/dshah/src/fuse-rest-http-booster
Error: unknown flag: --app
Usage:
  odo push [component name] [flags]

Examples:
  # Push source code to the current component
  odo push
  
  # Push data to the current component from the original source.
  odo push
  
  # Push source code in ~/mycode to component called my-component
  odo push my-component --context ~/mycode

Flags:
      --config               Use config flag to only apply config on to cluster
      --context string       Use given context directory as a source for component settings
  -h, --help                 Help for push
      --ignore stringSlice   Files or folders to be ignored via glob expressions.
      --show-log             If enabled, logs will be shown when built
      --source               Use source flag to only push latest source on to cluster

Global Flags:
      --skip-connection-check   Skip cluster check
  -v, --v Level                 Log level for V logs. Level varies from 0 to 9 (default 0).
      --vmodule moduleSpec      Comma-separated list of pattern=N settings for file-filtered logging

 ✗  unknown flag: --app
```
I don't get why the VS Code extension forces me to use `odo v0.20.0`:
```bash
$ ~/.vs-openshift/odo version
odo v0.0.20 (bd3e74a4)

Server: https://192.168.42.121:8443
Kubernetes: v1.11.0+d4cacc0
---
A newer version of odo (version: v1.0.0-beta2) is available.
Update using your package manager, or run
curl https://raw.githubusercontent.com/redhat-developer/odo/master/scripts/install.sh | sh
to update manually, or visit https://github.com/redhat-developer/odo/releases
---
If you wish to disable the update notifications, you can disable it by running
'odo utils config set UpdateNotification false'
````
in spite of having `odo` built from master residing in `~/bin`.

**Comment by dharmit** [comment] 2019-06-13 10:59
I'll manually do an `odo push` to check this instead of using the extension. But would that be good enough to attempt reproducing this issue? @kadel

**Comment by mohitsuman** [comment] 2019-06-14 11:01
@dharmit The OpenShift Connector currently uses `odo 0.0.20` and will remain so for the latest release as well. As migrating to odo beta requires breaking changes and workflow change too, that work is still in progress. So the install will always prompt to use the functionality of `odo 0.0.20`.

**Comment by dharmit** [comment] 2019-06-14 11:18
@mohitsuman Yep, I understand that. It's just that for the sake of this case, I'm not able to reproduce the problem @apupier has mentioned. At least not through the CLI.

**Comment by dharmit** [comment] 2019-06-14 11:23
@apupier can you please try to follow below steps on CLI and see if the issue is reproducible?

```bash
$ oc login -u developer    # if you're using a minishift instance
$ oc import-image java --from=registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift --confirm
$ oc annotate istag/java:latest tags=builder

$ git clone https://github.com/jboss-fuse/fuse-rest-http-booster/
$ cd  fuse-rest-http-booster
$ git checkout v7.2.0-redhat-01

$ odo login -u developer
$ odo create java
$ odo url create --port 8080
$ odo push
```

After `odo push`, you'll see the error about missing `jar` in `/deployments` in the pods logs. And since `supervisord` keeps restarting the failing process, you'll see them multiple times. But after a couple of minutes, once the image build is over, URL should show the code in the repo.

**Comment by dharmit** [comment] 2019-07-09 09:28
@apupier I'm reproducing this issue on Windows environment and getting below error when I create a component:
```
[INFO] Downloaded: https://maven.repository.redhat.com/ga/io/fabric8/fabric8-maven-watcher-standard/3.5.33.fuse-720026-redhat-00001/fabric8-maven-watcher-standard-3.5.33.fuse-720026-redhat-00001.jar (20 kB at 6.3 kB/s)
[INFO] Downloading: https://maven.repository.redhat.com/ga/io/fabric8/fabric8-project-utils/3.0.11.fuse-720027-redhat-00001/fabric8-project-utils-3.0.11.fuse-720027-redhat-00001.jar
[INFO] Downloaded: https://maven.repository.redhat.com/ga/javax/validation/validation-api/1.1.0.Final-redhat-1/validation-api-1.1.0.Final-redhat-1.jar (65 kB at 20 kB/s)
[INFO] Downloading: https://maven.repository.redhat.com/ga/io/fabric8/gitrepo-api/3.0.11.fuse-720027-redhat-00001/gitrepo-api-3.0.11.fuse-720027-redhat-00001.jar
[INFO] Downloaded: https://maven.repository.redhat.com/ga/io/fabric8/kubernetes-api/3.0.11.fuse-720027-redhat-00001/kubernetes-api-3.0.11.fuse-720027-redhat-00001.jar (123 kB at 37 kB/s)
[INFO] Downloading: https://maven.repository.redhat.com/ga/io/fabric8/cxf-utils/3.0.11.fuse-720027-redhat-00001/cxf-utils-3.0.11.fuse-720027-redhat-00001.jar
[INFO] Downloaded: https://maven.repository.redhat.com/ga/io/fabric8/gitrepo-api/3.0.11.fuse-720027-redhat-00001/gitrepo-api-3.0.11.fuse-720027-redhat-00001.jar (40 kB at 11 kB/s)
[INFO] Downloading: https://maven.repository.redhat.com/ga/io/fabric8/jaxrs-utils/3.0.11.fuse-720027-redhat-00001/jaxrs-utils-3.0.11.fuse-720027-redhat-00001.jar
[INFO] Downloaded: https://maven.repository.redhat.com/ga/io/fabric8/fabric8-project-utils/3.0.11.fuse-720027-redhat-00001/fabric8-project-utils-3.0.11.fuse-720027-redhat-00001.jar (23 kB at 6.5 kB/s)
[INFO] Downloading: https://maven.repository.redhat.com/ga/javax/ws/rs/javax.ws.rs-api/2.0.1.redhat-1/javax.ws.rs-api-2.0.1.redhat-1.jar
[INFO] Downloaded: https://maven.repository.redhat.com/ga/io/fabric8/cxf-utils/3.0.11.fuse-720027-redhat-00001/cxf-utils-3.0.11.fuse-720027-redhat-00001.jar (11 kB at 2.9 kB/s)
[INFO] Downloading: https://maven.repository.redhat.com/ga/org/apache/cxf/cxf-rt-rs-client/3.1.11.fuse-720057-redhat-00001/cxf-rt-rs-client-3.1.11.fuse-720057-redhat-00001.jar
[INFO] Downloaded: https://maven.repository.redhat.com/ga/io/fabric8/jaxrs-utils/3.0.11.fuse-720027-redhat-00001/jaxrs-utils-3.0.11.fuse-720027-redhat-00001.jar (5.7 kB at 1.5 kB/s)
[INFO] Downloading: https://maven.repository.redhat.com/ga/org/apache/cxf/cxf-rt-transports-http/3.1.11.fuse-720057-redhat-00001/cxf-rt-transports-http-3.1.11.fuse-720057-redhat-00001.jar
[INFO] Downloaded: https://maven.repository.redhat.com/ga/io/fabric8/fabric8-utils/3.0.11.fuse-720027-redhat-00001/fabric8-utils-3.0.11.fuse-720027-redhat-00001.jar (143 kB at 36 kB/s)
[INFO] Downloading: https://maven.repository.redhat.com/ga/org/apache/cxf/cxf-core/3.1.11.fuse-720057-redhat-00001/cxf-core-3.1.11.fuse-720057-redhat-00001.jar
[INFO] Downloaded: https://maven.repository.redhat.com/ga/org/apache/cxf/cxf-rt-rs-client/3.1.11.fuse-720057-redhat-00001/cxf-rt-rs-client-3.1.11.fuse-720057-redhat-00001.jar (171
kB at 42 kB/s)
[INFO] Downloading: https://maven.repository.redhat.com/ga/org/apache/ws/xmlschema/xmlschema-core/2.2.1.redhat-2/xmlschema-core-2.2.1.redhat-2.jar
[INFO] Downloaded: https://maven.repository.redhat.com/ga/javax/ws/rs/javax.ws.rs-api/2.0.1.redhat-1/javax.ws.rs-api-2.0.1.redhat-1.jar (116 kB at 28 kB/s)
[INFO] Downloading: https://maven.repository.redhat.com/ga/org/apache/cxf/cxf-rt-frontend-jaxrs/3.1.11.fuse-720057-redhat-00001/cxf-rt-frontend-jaxrs-3.1.11.fuse-720057-redhat-00001.jar
[INFO] Downloaded: https://maven.repository.redhat.com/ga/org/apache/cxf/cxf-rt-transports-http/3.1.11.fuse-720057-redhat-00001/cxf-rt-transports-http-3.1.11.fuse-720057-redhat-00001.jar (353 kB at 84 kB/s)
[INFO] Downloaded: https://maven.repository.redhat.com/ga/org/javassist/javassist/3.20.0.GA-redhat-3/javassist-3.20.0.GA-redhat-3.jar (752 kB at 173 kB/s)
[INFO] Downloaded: https://maven.repository.redhat.com/ga/org/apache/ws/xmlschema/xmlschema-core/2.2.1.redhat-2/xmlschema-core-2.2.1.redhat-2.jar (173 kB at 39 kB/s)
[INFO] Downloaded: https://maven.repository.redhat.com/ga/org/apache/cxf/cxf-rt-frontend-jaxrs/3.1.11.fuse-720057-redhat-00001/cxf-rt-frontend-jaxrs-3.1.11.fuse-720057-redhat-00001.jar (634 kB at 105 kB/s)
[INFO] Downloaded: https://maven.repository.redhat.com/ga/org/apache/cxf/cxf-core/3.1.11.fuse-720057-redhat-00001/cxf-core-3.1.11.fuse-720057-redhat-00001.jar (1.4 MB at 155 kB/s)
[INFO] Downloading: https://maven.repository.redhat.com/earlyaccess/all/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
[INFO] Downloading: https://maven.repository.redhat.com/earlyaccess/all/org/bouncycastle/bcpkix-jdk15on/1.57/bcpkix-jdk15on-1.57.jar
[INFO] Downloading: https://maven.repository.redhat.com/techpreview/all/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
[INFO] Downloading: https://maven.repository.redhat.com/techpreview/all/org/bouncycastle/bcpkix-jdk15on/1.57/bcpkix-jdk15on-1.57.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15:11 min
[INFO] Finished at: 2019-07-09T09:15:37Z
[INFO] Final Memory: 36M/56M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jboss.redhat-fuse:fabric8-maven-plugin:7.2.0.fuse-720020-redhat-00001:resource (default) on project fuse-rest-http-booster: Execution default of
goal org.jboss.redhat-fuse:fabric8-maven-plugin:7.2.0.fuse-720020-redhat-00001:resource failed: Plugin org.jboss.redhat-fuse:fabric8-maven-plugin:7.2.0.fuse-720020-redhat-00001 or
one of its dependencies could not be resolved: The following artifacts could not be resolved: commons-codec:commons-codec:jar:1.9, org.bouncycastle:bcpkix-jdk15on:jar:1.57: Could not transfer artifact commons-codec:commons-codec:jar:1.9 from/to central (https://repo1.maven.org/maven2): Connect to repo1.maven.org:443 [repo1.maven.org/151.101.24.209] failed: Connection timed out (Connection timed out) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jboss.redhat-fuse:fabric8-maven-plugin:7.2.0.fuse-720020-redhat-00001:resource (default) on project fuse-rest-http-booster: Execution default of goal org.jboss.redhat-fuse:fabric8-maven-plugin:7.2.0.fuse-720020-redhat-00001:resource failed: Plugin org.jboss.redhat-fuse:fabric8-maven-plugin:7.2.0.fuse-720020-redhat-00001 or one of its dependencies could not be resolved: The following artifacts could not be resolved: commons-codec:commons-codec:jar:1.9, org.bouncycastle:bcpkix-jdk15on:jar:1.57: Could not transfer artifact commons-codec:commons-codec:jar:1.9 from/to central (https://repo1.maven.org/maven2): Connect to repo1.maven.org:443 [repo1.maven.org/151.101.24.209] failed: Connection timed out (Connection timed out)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.jboss.redhat-fuse:fabric8-maven-plugin:7.2.0.fuse-720020-redhat-00001:resource failed: Plugin org.jboss.redhat-fuse:fabric8-maven-plugin:7.2.0.fuse-720020-redhat-00001 or one of its dependencies could not be resolved: The following artifacts could not be resolved: commons-codec:commons-codec:jar:1.9, org.bouncycastle:bcpkix-jdk15on:jar:1.57: Could not transfer artifact commons-codec:commons-codec:jar:1.9 from/to central (https://repo1.maven.org/maven2): Connect to repo1.maven.org:443 [repo1.maven.org/151.101.24.209] failed: Connection timed out (Connection timed out)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin org.jboss.redhat-fuse:fabric8-maven-plugin:7.2.0.fuse-720020-redhat-00001 or one of its dependencies could not
be resolved: The following artifacts could not be resolved: commons-codec:commons-codec:jar:1.9, org.bouncycastle:bcpkix-jdk15on:jar:1.57: Could not transfer artifact commons-codec:commons-codec:jar:1.9 from/to central (https://repo1.maven.org/maven2): Connect to repo1.maven.org:443 [repo1.maven.org/151.101.24.209] failed: Connection timed out (Connection ti ◐  Building componentt)
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:218)
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:149)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm(DefaultMavenPluginManager.java:403)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:374)
        at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:231)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:102)
        ... 21 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: commons-codec:commons-codec:jar:1.9, org.bouncycastle:bcpkix-jdk15on:jar:1.57: Could not transfer artifact commons-codec:commons-codec:jar:1.9 from/to central (https://repo1.maven.org/maven2): Connect to repo1.maven.org:443 [repo1.maven.org/151.101.24.209] failed: Connection timed out (Connection timed out)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:453)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:255)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:376)
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:210)
        ... 26 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact commons-codec:commons-codec:jar:1.9 from/to central (https://repo1.maven.org/maven2):
Connect to repo1.maven.org:443 [repo1.maven.org/151.101.24.209] failed: Connection timed out (Connection timed out)
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.maven.wagon.TransferFailedException: Connect to repo1.maven.org:443
[repo1.maven.org/151.101.24.209] failed: Connection timed out (Connection timed out)
        at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1066)
        at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:960)
        at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
        at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
        at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
        at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:569)
        at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:436)
        at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:413)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:456)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:359)
        ... 4 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to repo1.maven.org:443 [repo1.maven.org/151.101.24.209] failed: Connection timed out (Connection timed out)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.jav




a:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:832)
        at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:983)
        ... 13 more
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        ... 23 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

 ?[31m✗?[0m  Building component
 ?[31m✗?[0m  command terminated with exit code 1
```
I believe this is a step before we expect any binary to show up under `/deployments`. This failure is indicating an issue with building the binary, I believe.

Pardon my java knowledge and correct me if I'm wrong.

**Comment by apupier** [comment] 2019-07-09 09:37
it looks alike another type of error. Here the build is failing retrieving a dependency commons-codec.
In initially reported case there was no error in the Maven build, it was "only" taking too much time.

(and sorry but still didn't had time to prepare an environment to test that)

**Comment by kadel** [comment] 2019-07-09 09:46
@dharmit  This looks like some network issue.

`one of its dependencies could not be resolved: The following artifacts could not be resolved: commons-codec:commons-codec:jar:1.9, org.bouncycastle:bcpkix-jdk15on:jar:1.57: Could not transfer artifact commons-codec:commons-codec:jar:1.9 from/to central (https://repo1.maven.org/maven2): Connect to repo1.maven.org:443 [repo1.maven.org/151.101.24.209] failed: Connection timed out (Connection timed out) -> [Help 1]`

**Comment by dharmit** [comment] 2019-07-10 11:54
So today I was reproducing this on a Fedora box using the VS Code Connector available from Marketplace and odo v0.0.20 that it downloads by default. I did face the issue at 02:00 in the video and couldn't get past beyond that!

But then I tried to reproduce the same on latest VS Code Connector bits from *odo-1.0.0-integration* branch of https://github.com/redhat-developer/vscode-openshift-tools/ which again downloads odo v0.0.20 but I replaced `~/.vs-openshift/odo` with the binary built from master branch of odo.

When using latest bits of VS Code Connector and odo, component creation fails with this message:
```sh
Failed to create Component with error 'Error: Command failed: "/home/dshah/.vs-openshift/odo" create java:latest fuse --local /home/dshah/src/fuse-rest-http-booster --app app --project myproject
Error: unknown flag: --local
```
Replacing `--local` with `--context` through CLI works but then that's being done through CLI and not through the plugin.

**Comment by dharmit** [comment] 2019-07-12 07:17
With the help of @mohitsuman in providing us with latest VS Code extension that works with `odo` beta, we (thanks @girishramnani) tried to reproduce this issue on Fedora as well as Windows systems. However, first push works just fine unlike the way it breaks at 02:00 in the video and also `odo watch` works just fine.

@apupier since you're not working on this at the moment, I suggest you try this with the newer bits of VS Code extension that uses `odo` beta version instead of v0.0.20 whenever you get a chance.

I think it's safe to close this @kadel.

**Comment by kadel** [comment] 2019-07-12 07:46
/close

feel free to reopen if someone reproduces this with vscode extension that uses odo beta (I believe that it was not released yet, but it should be soon)

**Closed by kadel** 2019-07-12 07:46 UTC
Labels: kind/bug, points/1, priority/Medium, state/Ready
