### ISSUE TITLE
Stability of our e2e tests

### ISSUE THREAD

**Issue by kadel** [openshift/odo#1470] opened 2019-03-18 07:35 UTC
I'm seeing a lot of failed tests even on the PRs that are not changing anything in the source code. 

We need to make sure that we can count on our e2e tests.

Some examples:
 - https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/redhat-developer_odo/1467/pull-ci-redhat-developer-odo-master-e2e-core/116
- https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/redhat-developer_odo/1462/pull-ci-redhat-developer-odo-master-e2e-core/110

**Comment by cdrage** [comment] 2019-03-19 13:07
Another issue from PR: https://github.com/redhat-developer/odo/pull/1275

Looks to be a timeout to the cluster: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/redhat-developer_odo/1275/pull-ci-redhat-developer-odo-master-e2e-core/160

**Comment by amitkrout** [comment] 2019-03-19 13:26
Some suspicious clusterup/timeout failure in prow - https://coreos.slack.com/archives/CEKNRGF25/p1553001003940200 asked by @mohammedzee1000

**Comment by amitkrout** [comment] 2019-03-20 06:23
openshift-install times out creating infrastructure resources - https://bugzilla.redhat.com/show_bug.cgi?id=1690069

**Comment by amitkrout** [comment] 2019-03-20 10:28
Unless verbose is enabled for each test on prow It's hard to root cause the failure. I have observed in recent time these failure are more often consistent. Some failures are from CI side and some test failure, could be the side effect of unstable prow setup which causes the odo test failures. 

So I would recommend enable the test verbose to crack down the odo test failure on prow setup as on aws the chance of reproduce the same failure is less. It also helps on aws too if any test failure is introduced. Issue from OpenShift CI side @mohammedzee1000 is taking care anyway.

**Comment by amitkrout** [comment] 2019-03-21 14:13
```
Running command: odo create odo-1553168711/nodejs push-odoignore-flag-example --local /var/folders/c9/fb55pf_568dfd1fzj9w1v4n00000gn/T/odo880818179/nodejs-ex
 •  Checking component  ...
 ✓  Checking component
 •  Checking component version  ...
 ✓  Checking component version
 ✓  Initializing 'push-odoignore-flag-example' component
 •  Creating component push-odoignore-flag-example  ...
 ✓  Creating component push-odoignore-flag-example
 ✓  Component 'push-odoignore-flag-example' was created and port 8080/TCP was opened
 ✓  Component 'push-odoignore-flag-example' is now set as active component
To push source code to the component run 'odo push'
This may take a few moments to be ready
Running command: odo push --ignore tests/,README.md
 ✗  Please log in to the cluster
• Failure [12.005 seconds]
odoe2e creating a component when application exists [It] should create a component and push using the --ignore flag 
/Users/amit/go/src/github.com/redhat-developer/odo/tests/e2e/e2e_test.go:418

  Expected
      <int>: 1
  to equal
      <int>: 0

  /Users/amit/go/src/github.com/redhat-developer/odo/tests/e2e/e2e.go:45
```

Push fails due to OpenShift issue - https://bugzilla.redhat.com/show_bug.cgi?id=1684547

**Comment by amitkrout** [comment] 2019-03-25 04:45
One more flake observed multiple times in prow

```
[1553433935] odo test suite - 6/67 specs Running command: oc project -q
error: you do not have rights to view project "json-test".

------------------------------
Failure [0.256 seconds]
[BeforeSuite] BeforeSuite 
/go/src/github.com/openshift/odo/tests/e2e/e2e_test.go:47

  Expected
      <int>: 1
  to equal
      <int>: 0

  /go/src/github.com/openshift/odo/tests/e2e/e2e.go:42
```

Issue #1513 created for tracking purpose

**Comment by amitkrout** [comment] 2019-03-27 18:23
#1517

**Comment by amitkrout** [comment] 2019-04-01 04:54
Pr #1517 will fix test instability caused by odo test source code.

**Comment by amitkrout** [comment] 2019-04-02 07:11
Issue summary - As part of e2e test instability is concern, fixes are merged into master. However there are two open bugzilla [1] and [2] on OpenShift 4 and can be tracked there.

**Closed by amitkrout** 2019-04-02 07:11 UTC
Labels: kind/testing, priority/High, state/In Analysis
