### ISSUE TITLE
Conflicts in odo and Devfile terminology 

### ISSUE THREAD

**Issue by kadel** [openshift/odo#3076] opened 2020-05-05 08:21 UTC
With moving everything towards Devfiles some of the odo terminology clashes with Devfile terminology.

One of the biggest clashes is the use of the term **component**.
 -  in odo "component" is part of the application (for example one microservice that is part of a bigger application) 
 - in Devfile "component" is part of the workspace (for example a build container or an IDE plugin)

This should be resolved before we release odo v2 with stable Devfile support. 

We have two options:
 1) Change on odo side. This will include big changes in most of the odo commands, making it backward incompatible.
2) Rename components in devfile spec to something else

/kind discussion
/kind epic
/priority high

**Comment by dharmit** [comment] 2020-05-05 10:30
> in odo "component" is part of the application (for example one microservice that is part of a bigger application)

IMO, if possible, we could use this opportunity to change it on odo side. Personally, in my head, even though I have an idea about what a component (DC+pods+service+url) means in odo, reading its definition still leaves me confused. :confused: 

Plus, application means yet another thing in OpenShift (a label that can be assigned to different objects, IIUC) and here in the definition you mention, it means something else.

**Comment by kadel** [comment] 2020-05-05 12:11
This might be a good opportunity to even more match odo terminology with OpenShift web console.
One big downside is that this will make odo v2 completely incompatible with the previous version. Which will make it more complicated to adopt odo v2 for IDE plugins

**Comment by dharmit** [comment] 2020-05-05 12:49
By matching the terminology with OpenShift web console, we don't mean to use the lingo of OpenShift, right? I think a major goal of odo is to abstract k8s/OpenShift for the users so that they don't have to understand those. So, using the web console terminology is fine as long as we don't make things confusing for users.

I think this is a great topic for odo contributor's call.

**Comment by kadel** [comment] 2020-05-05 12:57
> By matching the terminology with OpenShift web console, we don't mean to use the lingo of OpenShift, right? I think a major goal of odo is to abstract k8s/OpenShift for the users so that they don't have to understand those. So, using the web console terminology is fine as long as we don't make things confusing for users.
> 
> I think this is a great topic for odo contributor's call.

Sorry, I should have been more specific. I meant one specific part of the OpenSHift web console - Topology view in Developer console

**Comment by gorkem** [comment] 2020-05-05 15:39
I think, the above odo definition of component is a subset of devfile definition and `odo component` command is not able to create everything in the the full definition on the devfile. I do not think `odo component` command should actually be used to create builders and side-car tools that are useful for development time only either. I am OK if it only deals with a subset of devfile and we let "experts" to modify additional components in devfile only

**Comment by kadel** [comment] 2020-05-06 11:44
> I think, the above odo definition of component is a subset of devfile definition and `odo component` command is not able to create everything in the the full definition on the devfile. I do not think `odo component` command should actually be used to create builders and side-car tools that are useful for development time only either. I am OK if it only deals with a subset of devfile and we let "experts" to modify additional components in devfile only

@gorkem, In other words, you are saying that `odo component create` still makes sense as it creates devfile components (or a subset of it)?

**Comment by gorkem** [comment] 2020-07-02 03:11
Logically yes, `odo component create` can be used to create a subset of devfile components. However the issue is we do not plan to have a catalog of devfile components but complete devfiles so this would not work. Perhaps your original suggestion of synchronizing with the topology view is the implementable option.

**Comment by dharmit** [comment] 2020-11-25 14:12
Is this relevant any more @kadel? I think we're going to avoid exposing devfile terminology to odo users by using `odo config` for making changes to devfile. So it shouldn't be a problem, no? But I could be wrong.

**Closed** 2020-12-25 17:01 UTC
Labels: kind/discussion, kind/epic, lifecycle/rotten, priority/High
