### ISSUE TITLE
jUnit reports misleading test success status

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4279] opened 2020-12-03 07:26 UTC
/area testing

## What versions of software are you using?

**Operating System:**
all supported

**Output of `odo version`:**
master

## How did you run odo exactly?

Tests are running on CI.

## Actual behavior

Even though CI fails on platform issue jUnit shows up 99% success test case. Details: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/4177/pull-ci-openshift-odo-master-v4.5-integration-e2e/1331271564972265472

## Expected behavior

jUnit should show up the exact reports on test execution.

## Any logs, error output, etc?

CI log: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/4177/pull-ci-openshift-odo-master-v4.5-integration-e2e/1331271564972265472

jUnit report: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_odo/4177/pull-ci-openshift-odo-master-v4.5-integration-e2e/1331271564972265472/artifacts/integration-e2e/integration-e2e-steps/reports/

**Comment by dharmit** [comment] 2020-12-10 14:06
Can we also make sure to figure out what will be required/changing as move the integration tests to PSI instead of its current state?

**Comment by anandrkskd** [comment] 2020-12-24 11:38
The above failure for the test was occurred due to taste was not able to complete under 4 hours, test platform team confirmed it was not a problem from there side and the test result where probably of the test that were able to pass before the test hit time-out.

**Comment by dharmit** [comment] 2020-12-28 06:44
> The above failure for the test was occurred due to taste was not able to complete under 4 hours

Tests running for 4 hours is a problem. How can we reduce this run time?

**Comment by anandrkskd** [comment] 2020-12-28 07:01
AFAIR @prietyc123 worked on a [PR](https://github.com/openshift/odo/pull/4047) few sprints back to re-factor and remove any duplication of codes, I am not sure if the intent of the PR was to reduce the runtime or not, and I guess the movement of reducing integration test and adding more unit test was also going to be helpful.

**Comment by dharmit** [comment] 2020-12-28 07:25
> I am not sure if the intent of the PR was to reduce the runtime or not,

Nope, that's something the devs should be doing. @prietyc123 just showed the way.



> I guess the movement of reducing integration test and adding more unit test was also going to be helpful.

:+1:

**Comment by dharmit** [comment] 2020-12-28 07:26
So is there anything pending on this issue? Or should we close it? How can we accurately figure out in future (till the tasks you pointed out in https://github.com/openshift/odo/issues/4279#issuecomment-751605483 get addressed) that misleading success status is actually due to the tests taking too long to complete?

**Comment by anandrkskd** [comment] 2020-12-28 09:35
As  much as I understand, the success status are for test which were able to complete before the time-out occurred, and we miss understood this situation as misleading success status.

Or in simple words we can say CI failed due to time-out, but was able to post the result of test that were able execute.

**Closed** 2021-01-21 06:05 UTC
Labels: area/testing
