### ISSUE TITLE
Latest images on 3.11 cluster reflects as unsupported on init repo

### ISSUE THREAD

**Issue by prietyc123** [openshift/odo#4220] opened 2020-11-15 12:47 UTC
/kind bug
/kind failing-test

## What versions of software are you using?

**Operating System:**
linux

**Output of `odo version`:**
master

## How did you run odo exactly?

Running tests on 3.11 cluster travis CI. This is particularly failing on odo-init repo. Details of the issue: https://github.com/openshift/odo-init-image/issues/76

## Any logs, error output, etc?

Failure details - https://travis-ci.com/github/openshift/odo-init-image/jobs/432346337

**Comment by rnapoles-rh** [comment] 2020-12-09 00:56
@dharmit what do we use https://github.com/openshift/odo-init-image for ?

**Comment by dharmit** [comment] 2020-12-09 07:57
> @dharmit what do we use https://github.com/openshift/odo-init-image for ?

I was hoping no one would ever ask me this question because I _probably_ don't completely understand it. But let me take a stab at it.

odo spins up init containers to set up the environment before starting the actual component. And it's the odo init image that's used to do this set up job. We have more info about the tasks in the [docs here](https://odo.dev/docs/odo-architecture/#init-containers).

@kadel can you correct me if I am wrong? TBH, I used to dread that someone might ask me this question some day and I would make a fool of myself. :disappointed:

**Comment by kadel** [comment] 2020-12-09 17:00
We don't know if this is failing just on odo-init-image because travis tests are not running on odo repo for over a month due to a quota change on Travis side :-(

**Comment by dharmit** [comment] 2020-12-10 14:39
https://github.com/openshift/odo-init-image/blob/master/.travis.yml#L34

**Comment by prietyc123** [comment] 2020-12-11 11:34
> We don't know if this is failing just on odo-init-image because travis tests are not running on odo repo for over a month due to a quota change on Travis side

@kadel I think this is only on odo-init-image because we merged image bumping pr https://github.com/openshift/odo-init-image/pull/71 on 30th July and till that time this was the consistence failure on odo-init-image. However travis tests are not running on odo repo from almost one month. Earlier to that tests were running fine on odo repo. So, this is clearly an issue from odo-init-repo and I have described all my points in the issue https://github.com/openshift/odo-init-image/issues/76

**Comment by rnapoles-rh** [comment] 2021-01-05 18:05
I ran corresponding test suite locally against 3.11 (minishift) and it fails. Then ran it agains 4.5.2 in PSI and it passes. @prietyc123 I guess that means it is an actual bug on 3.11, not only on odo-init-image, correct?
This are the results on 3.11 for

**Comment by kadel** [comment] 2021-01-06 10:58
The problem is actually in the test setup. 
The tests were failing only on odo-init-image repo and not on odo repo because travis.yaml in  odo-init-image repo was missing `make configure-supported-311-is` which adds the newer supported image to 3.11 clusters.


This PR is fixing it https://github.com/openshift/odo-init-image/pull/77

**Comment by rnapoles-rh** [comment] 2021-01-06 14:13
@kadel then I will close this one once openshift/odo-init-image#77 is closed

**Closed** 2021-01-14 12:32 UTC
Labels: kind/bug, kind/failing-test, priority/High

**Comment by rnapoles-rh** [comment] 2021-01-14 12:34
closing as https://github.com/openshift/odo-init-image/pull/77 fixes it
