### ISSUE TITLE
odo delete --app --project does not work for devfile components

### ISSUE THREAD

**Issue by jeffmaury** [openshift/odo#4259] opened 2020-11-25 18:13 UTC
/kind bug

## What versions of software are you using?

**Operating System:**
Win10Pro

**Output of `odo version`:**
```
odo v2.0.0 (6fbb9d9bf)           
                                 
Server: https://172.16.0.10:8443 
Kubernetes: v1.11.0+d4cacc0      
```
## How did you run odo exactly?
`odo delete --app app --project test-project launcher-vertx`

## Actual behavior

` X  Component launcher-vertx does not exist on the cluster`

## Expected behavior

Component should be found and deleted on the cluster

## Any logs, error output, etc?

With verbose mode on:

```
I1125 19:05:54.614950   34164 util.go:425] path devfile.yaml doesn't exist, skipping it                                                                                                        
I1125 19:05:54.654579   34164 loader.go:375] Config loaded from file:  C:\Users\JeffMAURY/.kube/config                                                                                         
I1125 19:05:54.665292   34164 loader.go:375] Config loaded from file:  C:\Users\JeffMAURY/.kube/config                                                                                         
I1125 19:05:54.668304   34164 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: odo/v0.0.0 (windows/amd64) kubernetes/$Format" -H "Authorization: Bea
rer replaced" 'https://172.16.0.10:8443/apis/project.openshift.io/v1/projects/test-project'                                                                 
I1125 19:05:54.683302   34164 round_trippers.go:443] GET https://172.16.0.10:8443/apis/project.openshift.io/v1/projects/test-project 200 OK in 13 milliseconds                                 
I1125 19:05:54.683302   34164 round_trippers.go:449] Response Headers:                                                                                                                         
I1125 19:05:54.684302   34164 round_trippers.go:452]     Cache-Control: no-store                                                                                                               
I1125 19:05:54.684302   34164 round_trippers.go:452]     Cache-Control: no-store                                                                                                               
I1125 19:05:54.685302   34164 round_trippers.go:452]     Content-Type: application/json                                                                                                        
I1125 19:05:54.685302   34164 round_trippers.go:452]     Date: Wed, 25 Nov 2020 18:05:54 GMT                                                                                                   
I1125 19:05:54.686302   34164 round_trippers.go:452]     Content-Length: 603                                                                                                                   
I1125 19:05:54.692303   34164 request.go:1017] Response Body: {"kind":"Project","apiVersion":"project.openshift.io/v1","metadata":{"name":"test-project","selfLink":"/apis/project.openshift.io
/v1/projects/test-project","uid":"4a4ea1c9-2d9b-11eb-b2c1-00155d002891","resourceVersion":"5011382","creationTimestamp":"2020-11-23T14:50:55Z","annotations":{"openshift.io/description":"","op
enshift.io/display-name":"","openshift.io/requester":"developer","openshift.io/sa.scc.mcs":"s0:c14,c9","openshift.io/sa.scc.supplemental-groups":"1000200000/10000","openshift.io/sa.scc.uid-ra
nge":"1000200000/10000"}},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}                                                                                                    
I1125 19:05:54.697302   34164 util.go:425] path devfile.yaml doesn't exist, skipping it                                                                                                        
I1125 19:05:54.702303   34164 loader.go:375] Config loaded from file:  C:\Users\JeffMAURY/.kube/config                                                                                         
I1125 19:05:54.710303   34164 loader.go:375] Config loaded from file:  C:\Users\JeffMAURY/.kube/config                                                                                         
I1125 19:05:54.714304   34164 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: odo/v0.0.0 (windows/amd64) kubernetes/$Format" -H "Authorization: Bea
rer replaced" 'https://172.16.0.10:8443/apis/project.openshift.io/v1/projects/test-project'                                                                 
I1125 19:05:54.724318   34164 round_trippers.go:443] GET https://172.16.0.10:8443/apis/project.openshift.io/v1/projects/test-project 200 OK in 9 milliseconds                                  
I1125 19:05:54.724318   34164 round_trippers.go:449] Response Headers:                                                                                                                         
I1125 19:05:54.726304   34164 round_trippers.go:452]     Cache-Control: no-store                                                                                                               
I1125 19:05:54.727313   34164 round_trippers.go:452]     Cache-Control: no-store                                                                                                               
I1125 19:05:54.728307   34164 round_trippers.go:452]     Content-Type: application/json                                                                                                        
I1125 19:05:54.728307   34164 round_trippers.go:452]     Date: Wed, 25 Nov 2020 18:05:54 GMT                                                                                                   
I1125 19:05:54.729306   34164 round_trippers.go:452]     Content-Length: 603                                                                                                                   
I1125 19:05:54.730307   34164 request.go:1017] Response Body: {"kind":"Project","apiVersion":"project.openshift.io/v1","metadata":{"name":"test-project","selfLink":"/apis/project.openshift.io
/v1/projects/test-project","uid":"4a4ea1c9-2d9b-11eb-b2c1-00155d002891","resourceVersion":"5011382","creationTimestamp":"2020-11-23T14:50:55Z","annotations":{"openshift.io/description":"","op
enshift.io/display-name":"","openshift.io/requester":"developer","openshift.io/sa.scc.mcs":"s0:c14,c9","openshift.io/sa.scc.supplemental-groups":"1000200000/10000","openshift.io/sa.scc.uid-ra
nge":"1000200000/10000"}},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}                                                                                                    
I1125 19:05:54.732730   34164 util.go:425] path devfile.yaml doesn't exist, skipping it                                                                                                        
I1125 19:05:54.733307   34164 occlient.go:2781] Getting DeploymentConfig: launcher-vertx-app                                                                                                   
I1125 19:05:54.733307   34164 round_trippers.go:423] curl -k -v -XGET  -H "User-Agent: odo/v0.0.0 (windows/amd64) kubernetes/$Format" -H "Authorization: Bearer 1xxse-vJhV3AMRwpQiGKTxQmW7iD1Sl
rN149wsLOQmM" -H "Accept: application/json, */*" 'https://172.16.0.10:8443/apis/apps.openshift.io/v1/namespaces/test-project/deploymentconfigs/launcher-vertx-app'                             
I1125 19:05:54.747306   34164 round_trippers.go:443] GET https://172.16.0.10:8443/apis/apps.openshift.io/v1/namespaces/test-project/deploymentconfigs/launcher-vertx-app 404 Not Found in 13 mi
lliseconds                                                                                                                                                                                     
I1125 19:05:54.748305   34164 round_trippers.go:449] Response Headers:                                                                                                                         
I1125 19:05:54.748305   34164 round_trippers.go:452]     Cache-Control: no-store                                                                                                               
I1125 19:05:54.749304   34164 round_trippers.go:452]     Cache-Control: no-store                                                                                                               
I1125 19:05:54.756307   34164 round_trippers.go:452]     Content-Type: application/json                                                                                                        
I1125 19:05:54.758310   34164 round_trippers.go:452]     Date: Wed, 25 Nov 2020 18:05:54 GMT                                                                                                   
I1125 19:05:54.759312   34164 round_trippers.go:452]     Content-Length: 276                                                                                                                   
I1125 19:05:54.760324   34164 request.go:1017] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"deploymentconfigs.apps.openshift.io \"launcher-ver
tx-app\" not found","reason":"NotFound","details":{"name":"launcher-vertx-app","group":"apps.openshift.io","kind":"deploymentconfigs"},"code":404}                                             
 X  Component launcher-vertx does not exist on the cluster                                                                                                                                     
```

**Comment by mik-dass** [comment] 2020-11-27 07:13
This seems to be a duplicate of https://github.com/openshift/odo/issues/4135

**Closed** 2020-11-27 07:23 UTC
Labels: kind/bug
