### ISSUE TITLE
fix windows installation instructions

### ISSUE THREAD

**Issue by kadel** [openshift/odo#4077] opened 2020-10-05 08:50 UTC
Install instructions for windows are confusing
https://odo.dev/docs/installing-odo/

The current documentation mentions `GOPATH/bin` and `C:\go-bin` users not familiar with Go might not know that this is.
The documentation needs to be more generic so even users without any Go knowledge can understand it.

/kind documentation
/priority high
/area windows

**Comment by deboer-tim** [comment] 2020-10-05 12:45
FWIW, I assumed it must have been a typo and meant 'path', Windows install seemed to work fine this way. I have a Windows box, can help verify the changes.

**Comment by girishramnani** [comment] 2020-10-05 12:52
seems to be duplicate of https://github.com/openshift/odo/issues/4062 @kadel

**Closed by girishramnani** 2020-10-05 12:52 UTC
Labels: area/Windows, kind/documentation, priority/High
