### ISSUE TITLE
Able to create multiple URL's with devfile with the same name

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#2980] opened 2020-04-23 19:28 UTC
/kind bug

## What versions of software are you using?

**Operating System:** Linux

**Output of `odo version`:** Master

## How did you run odo exactly?

```
~/openshift/springboot  master ✗                                                                                                                                            98d ⚑ ◒  
▶ odo url create --host e8ca.engint.REDACTED.com
 ✓  URL myspring-8080.e8ca.engint.REDACTED.com created for component: myspring

To apply the URL configuration changes, please use `odo push`

~/openshift/springboot  master ✗                                                                                                                                            98d ⚑ ◒  
▶ odo url create --host e8ca.engint.REDACTED.com
 ✓  URL myspring-8080.e8ca.engint.REDACTED.com created for component: myspring

To apply the URL configuration changes, please use `odo push`

~/openshift/springboot  master ✗                                                                                                                                            98d ⚑ ◒  
▶ odo url list
Found the following URLs for component myspring
NAME              URL                                               PORT     SECURE
myspring-8080     http://myspring-8080.api.engint.REDACTED.com     8080     false
myspring-8080     http://myspring-8080.api.engint.REDACTED.com     8080     false
myspring-8080     http://myspring-8080.api.engint.REDACTED.com     8080     false

~/openshift/springboot  master ✗                                                                                                                                            98d ⚑ ◒  
▶ odo url delete myspring-8080
? Are you sure you want to delete the url myspring-8080 Yes
panic: runtime error: slice bounds out of range [3:1]

goroutine 1 [running]:
github.com/openshift/odo/pkg/envinfo.(*EnvSpecificInfo).DeleteURL(0xc000b7fe50, 0x7ffd4c13d092, 0xd, 0x0, 0x0)                                                                       
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/pkg/envinfo/envinfo.go:225 +0x4fc                                                                            
github.com/openshift/odo/pkg/odo/cli/url.(*URLDeleteOptions).Run(0xc000739b00, 0x0, 0x0)
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/pkg/odo/cli/url/delete.go:113 +0x73                                                                          
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x20aa900, 0xc000739b00, 0xc0006ce480, 0xc0007e3880, 0x1, 0x1)                                                         
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:31 +0x13c                                                              
github.com/openshift/odo/pkg/odo/cli/url.NewCmdURLDelete.func1(0xc0006ce480, 0xc0007e3880, 0x1, 0x1)                                                                                 
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/pkg/odo/cli/url/delete.go:149 +0x5e                                                                          
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc0006ce480, 0xc0007e3860, 0x1, 0x1, 0xc0006ce480, 0xc0007e3860)                                          
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702 +0x285                                                          
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00076ed80, 0x1e94f70, 0xc00004af60, 0x0)                                                               
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783 +0x2c9                                                          
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736                                                                 
main.main()
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/cmd/odo/odo.go:75 +0x460                                                                                     


```

## Actual behavior

Error out when deleting the URL as well as being able to push a URL even though there is already one with the same name.

## Expected behavior

Being able to delete the URL as well as an error happening when trying to create a URL that has the same name.

**Comment by deboer-tim** [comment] 2020-04-30 17:47
FWIW, I hit this too.

**Comment by johnmcollier** [comment] 2020-04-30 17:53
When reviewing https://github.com/openshift/odo/pull/3054 - I couldn't reproduce this, so this issue may be fixed by this PR

**Comment by mik-dass** [comment] 2020-04-30 18:00
@cdrage @johnmcollier Yes #3054 will fix this too

**Closed** 2020-05-08 10:36 UTC
Labels: area/devfile, area/url, kind/bug
