### ISSUE TITLE
Travis CI is not working due to change from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#1761] opened 2019-05-22 13:04 UTC
[kind/bug]

## What versions of software are you using?
- Operating System:
- Output of `odo version`:

**Comment by mohammedzee1000** [comment] 2019-05-22 16:59
Tests currently blocked due to required Travis ci
https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by girishramnani** [comment] 2019-05-24 06:19
we have removed travis CI and instead running the integration tests on openshift CI

**Comment by amitkrout** [comment] 2019-05-24 07:51
@girishramnani Why you closed this ?

The issue is not resolved i guess

**Comment by cdrage** [comment] 2019-05-24 18:16
Reopening the issue :+1: we need to have this fixed.

**Comment by kadel** [comment] 2019-05-27 06:55
This is ultra ultra ultra hight prio and needs  to be fixed ASAP

**Comment by kadel** [comment] 2019-05-27 07:21
What do we need to do to fix travis?

**Comment by mohammedzee1000** [comment] 2019-05-27 07:31
Travis will need to be authorized again to fix the tests themselves,
 But for now atleast, we still cant make it blocking for tide merge.

**Comment by mohammedzee1000** [comment] 2019-05-27 08:37
This is no longer critical as no longer blocks prs and integration tests work fine on prow and are now enabled as blocking for merge.

But yes, considering we are going to use travis for non linux testing, we should really get the feedback working again as soon as possible
/remove-priority critical-urgent
/priority high

**Comment by amitkrout** [comment] 2019-05-27 10:36
@mohammedzee1000 @kadel Travis job started reflecting in odo pr #1759

**Comment by amitkrout** [comment] 2019-05-30 10:33
Now Travis CI works fine. I am closing it for now

**Closed by amitkrout** 2019-05-30 10:33 UTC
Labels: kind/bug, priority/High
