### ISSUE TITLE
.gitignore is ignored when using a subDir

### ISSUE THREAD

**Issue by ehsavoie** [openshift/odo#4367] opened 2021-01-15 17:42 UTC
/kind bug

## What versions of software are you using?

**Operating System:**
Fedora 33

**Output of `odo version`:**
odo v2.0.3 (9ae754023)

Server: https://api.sandbox.x8i5.p1.openshiftapps.com:6443
Kubernetes: v1.19.0+7070803

## How did you run odo exactly?
odo create java-wildfly --starter=microprofile-config
Configuration of starter project 

  - name: microprofile-config
    description: WildFly Eclipse Microprofile Config Quickstart
    git:
      checkoutFrom:
        remote: wildfly-quickstart
        revision: 22.0.0.Final
      remotes:
        wildfly-quickstart: https://github.com/wildfly/quickstart.git
    subDir: microprofile-config

## Actual behavior
project gets properly created except that the .gitignore file which is at the root of the git repository isn't there in the resulting project. Because of this the results of a maven build are no longer ignored and get pushed on the server. 

## Expected behavior
Use the .gitignore file from the repository to apply it in the resulting project.

## Any logs, error output, etc?

No error per se, except it tries to upload a lot of files.

**Comment by scottkurz** [comment] 2021-01-26 02:13
This seems like it could get complicated, unless there is a library function somewhere that odo could use to implement this logic.

The odo tool would have to "merge" the containing directories' .gitignore(s) with the .gitignore in the **subDir** and then write out the resulting merged value.  

E.g. if the parent **.gitignore** contained:  `a/b/c`  it would have to merge an entry:  `b/c` with the .gitignore in **subDir**, and handle wildcards, etc.

Unless it has already been decided odo and devfile-based tools should do this kind of thing, it seems like perhaps it should be the repo owner's responsibility to have a "self-contained" .gitignore at the level of the starter project **subDir**.

**Comment by dharmit** [comment] 2021-06-30 04:54
/reopen

@kadel can you help set the priority on this?

**Comment by kadel** [comment] 2021-06-30 08:19
> Unless it has already been decided odo and devfile-based tools should do this kind of thing, it seems like perhaps it should be the repo owner's responsibility to have a "self-contained" .gitignore at the level of the starter project **subDir**.

+1

If the starteProject is in a subdirectory I think that it should have its own `.gitignore` in that subdir.

The problem is when odo tries to do something smart like merging all `.gitignores` on the way up to the repository root it will also have to rewrite some of the paths. Because what was in an original repository a subdirectory now becomes a root of a new project. It will get quite messy quickly.

The best and safest approach here is to have `.gitignore` in a directory with a  starter project.

/close

**Closed** 2021-06-30 08:20 UTC
Labels: kind/bug, lifecycle/rotten
