### ISSUE TITLE
[Devfile] Panic when running url unit tests with experimental mode on

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#2908] opened 2020-04-16 16:36 UTC
/kind bug
/area devfile
/kind test

When I run the unit tests for odo on macOS with `experimental` set to true in the preferences, the url unit tests fail with a panic:
```
Johns-MacBook-Pro-3:odo johncollier$ odo preference set experimental true
Global preference was successfully updated
Johns-MacBook-Pro-3:odo johncollier$ go test -race github.com/openshift/odo/pkg/url
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x2461632]

goroutine 10 [running]:
testing.tRunner.func1(0xc000496900)
	/usr/local/go/src/testing/testing.go:830 +0x69d
panic(0x2da4420, 0x4624ec0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/openshift/odo/pkg/kclient.(*Client).GetDeploymentByName(0xc000313f10, 0x2f7e570, 0x6, 0x2, 0x2, 0xc00048c1f8)
	/Users/johncollier/go/src/github.com/openshift/odo/pkg/kclient/deployments.go:28 +0x62
github.com/openshift/odo/pkg/url.Create(0xc00028c0a0, 0xc000313f10, 0x2f7e570, 0x6, 0x1f90, 0x0, 0x2f7e570, 0x6, 0x2f7cd91, 0x3, ...)
	/Users/johncollier/go/src/github.com/openshift/odo/pkg/url/url.go:122 +0x476
github.com/openshift/odo/pkg/url.TestCreate.func1(0xc000496900)
	/Users/johncollier/go/src/github.com/openshift/odo/pkg/url/url_test.go:166 +0x7f3
testing.tRunner(0xc000496900, 0xc0003cdb10)
	/usr/local/go/src/testing/testing.go:865 +0x164
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x65b
FAIL	github.com/openshift/odo/pkg/url	0.283s
```

And with experimental mode off, it's fine:
```
Johns-MacBook-Pro-3:odo johncollier$ odo preference unset experimental
? Do you want to unset experimental in the preference Yes
Global preference was successfully updated
Johns-MacBook-Pro-3:odo johncollier$ go test -race github.com/openshift/odo/pkg/url
ok  	github.com/openshift/odo/pkg/url	1.262s
```

It's hard to tell if this could be encountered outside of a test scenario since we haven't seen it or in the integration tests, but given the panic is occurring outside of a test file (in `github.com/openshift/odo/pkg/url/url.go:122`), it could be possible.

**Comment by mik-dass** [comment] 2020-04-17 03:30
duplicate of https://github.com/openshift/odo/issues/2816

/close

**Closed** 2020-04-17 03:30 UTC
Labels: area/devfile, kind/bug, kind/test
