### ISSUE TITLE
odo create --devfile ./devfile.yaml deletes current devfile

### ISSUE THREAD

**Issue by kadel** [openshift/odo#3542] opened 2020-07-10 12:32 UTC
If I run `odo create` with  `--devfile` flag that points to the devfile in current directory odo just replaces it with empty file :-( Which is pretty ugly, as it just destroyed my work :-(

The reason I would like to be able to run with `--devfile devfile.yaml` is that I want for odo to use my already existing devfile and also be able to provide custom odo component name.

```
▶ odo create frontend --devfile devfile.yaml
Experimental mode is enabled, use at your own risk

Validation
 ✓  Creating a devfile component from devfile path: /Users/tkral/tmp/odo-examples/demo-frontend/devfile.yaml [90653ns]
 ✓  Validating devfile component [134579ns]

Please use `odo push` command to create the component with source deployed

▶ cat devfile.yaml
```

Correct behavior should be to just keep my current devfile.yaml untouched.

/kind bug
/area devfile
/area component
/priority high

**Comment by GeekArthur** [comment] 2020-07-13 13:03
Duplicate of https://github.com/openshift/odo/issues/3452.

Temporary workaround:
You can run `odo create` in the current directory directly without using `--devfile` flag then odo can pick up the existing devfile in the current directory.

Permanent fix:
To fix this, we can just add validation code at the beginning of the file copy function https://github.com/openshift/odo/blob/master/pkg/util/util.go#L1081 to return the function directly if source and destination paths are the same.

I believe the problem is that since we don't catch this edge case in the file copy function, then `os.Create()` and `os.Open()` conflicts with each other so that generating an empty devfile.

**Comment by adisky** [comment] 2020-07-15 10:07
since #3452 and this one similar we should close one.

**Closed** 2020-07-17 05:27 UTC
Labels: area/devfile, kind/bug, priority/High
