### ISSUE TITLE
Add table for compability support / hot reloading / what we support

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#2084] opened 2019-09-04 13:29 UTC
[kind/Documentation]

## What did you find missing in the documentation?

We should have a table that shows what versions of OpenShift we support as well as what languages support hot reloading.

For example, if the user has Python 2.7, does it work with the latest image?

If they use 3.0, do you use the latest, what image do you use?

## What is the relevance of it?

Needed for new users.

**Comment by girishramnani** [comment] 2019-12-26 08:37
seems like a duplicate of https://github.com/openshift/odo/issues/2093

**Comment by girishramnani** [comment] 2019-12-26 08:37
closing

**Closed by girishramnani** 2019-12-26 08:37 UTC
Labels: kind/documentation
