### ISSUE TITLE
Recurring failure of "create with now flag should pass" tests

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#3250] opened 2020-05-27 09:23 UTC
The "create with now flag" tests are failing recurrently. It's also ranked 2 on the test statistics dashboard. Here's the log from one of the failures:
```
 [odo] I0527 08:04:29.128749    9537 utils.go:141] Updating container runtime env with run command
[odo] I0527 08:04:29.128756    9537 utils.go:150] Updating container runtime env with run command's workdir
[odo] I0527 08:04:29.128777    9537 utils.go:102] Found component "dockerimage" with alias "runtime"
[odo] I0527 08:04:29.128810    9537 adapter.go:224] Creating deployment xgegme
[odo] I0527 08:04:29.128827    9537 adapter.go:225] The component name is xgegme
[odo]  ✗  Failed to start component with name xgegme.
[odo] Error: Failed to create the component: unable to create or update component: unable to create Deployment xgegme: deployments.apps "xgegme" is forbidden: unable to create new content in namespace uqlvomcmsa because it is being terminated
Deleting project: wzmyhsfrka
Running odo with args [odo project delete wzmyhsfrka -f]
[odo] I0527 08:04:29.703908    9561 application.go:49] Unable to list Service Catalog instances: unable to list ServiceInstances: serviceinstances.servicecatalog.k8s.io is forbidden: User "developer" cannot list resource "serviceinstances" in API group "servicecatalog.k8s.io" in the namespace "wzmyhsfrka"
[odo]  ✓  Deleted project : wzmyhsfrka
[odo]  ⚠  Warning! Projects are deleted from the cluster asynchronously. Odo does its best to delete the project. Due to multi-tenant clusters, the project may still exist on a different node.
[odo] I0527 08:04:29.764376    9561 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)
Setting current dir to: /go/src/github.com/openshift/odo/tests/integration/devfile
Deleting dir: /tmp/811695040
• Failure [4.731 seconds]
odo devfile url command tests
/go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_url_test.go:16
  Creating urls
  /go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_url_test.go:105
    create with now flag should pass [It]
    /go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_url_test.go:129
    No future change is possible.  Bailing out early after 0.509s.
      
    Running odo with args [odo url create iqvrn --port 3000 --host gbxko.com --now --ingress --devfile devfile.yaml]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
    /go/src/github.com/openshift/odo/tests/helper/helper_run.go:34 
```

More logs can be found by referring to the [odo test statistics dashboard](https://gist.github.com/jgwest/5b28687514970ae6baa5942ee82d5755).

/priority high
/kind failing-test
/area testing

**Comment by dharmit** [comment] 2020-05-27 09:23
@mohammedzee1000 can you PTAL?

**Comment by amitkrout** [comment] 2020-05-27 10:14
This is duplicate of #3122

Please refer the original issue for details.

**Closed** 2020-05-27 10:14 UTC
Labels: area/testing, kind/failing-test, priority/High

**Comment by dharmit** [comment] 2020-05-29 07:28
@amitkrout The issue you've mentioned is about namespace deletion happening before the URL could get created. But I'm seeing following log for failure in PR #3252:
```
 [odo] Creating Kubernetes resources for component hohnkv
[odo] I0529 04:24:07.925272    2752 adapter.go:269] Successfully created component hohnkv
[odo] I0529 04:24:07.976385    2752 adapter.go:278] Successfully created Service for component hohnkv
[odo] I0529 04:24:07.976416    2752 deployments.go:47] Waiting for hohnkv deployment rollout
[odo]  •  Waiting for component to start  ...
[odo] I0529 04:24:07.996731    2752 deployments.go:81] Waiting for deployment "hohnkv" rollout to finish: 0 of 1 updated replicas are available...
[odo] I0529 04:24:07.996758    2752 deployments.go:88] Waiting for deployment spec update to be observed...
[odo] I0529 04:24:38.674941    2752 deployments.go:81] Waiting for deployment "hohnkv" rollout to finish: 0 of 1 updated replicas are available...
[odo] I0529 04:24:38.674973    2752 deployments.go:88] Waiting for deployment spec update to be observed...
[odo]  ✗  Waiting for component to start [5m]
[odo]  ✗  Failed to start component with name hohnkv.
[odo] Error: Failed to create the component: error while waiting for deployment rollout: timeout while waiting for hohnkv deployment roll out
Deleting project: ptumssntcg
Running odo with args [odo project delete ptumssntcg -f]
[odo] I0529 04:29:08.335923    4989 application.go:49] Unable to list Service Catalog instances: unable to list ServiceInstances: serviceinstances.servicecatalog.k8s.io is forbidden: User "developer" cannot list resource "serviceinstances" in API group "servicecatalog.k8s.io" in the namespace "ptumssntcg"
[odo]  ⚠  Warning! Projects are deleted from the cluster asynchronously. Odo does its best to delete the project. Due to multi-tenant clusters, the project may still exist on a different node.
[odo] I0529 04:29:08.370493    4989 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)
[odo]  ✓  Deleted project : ptumssntcg
Setting current dir to: /go/src/github.com/openshift/odo/tests/integration/devfile
Deleting dir: /tmp/221082326
• Failure [307.575 seconds]
odo devfile url command tests
/go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_url_test.go:16
  Creating urls
  /go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_url_test.go:105
    create with now flag should pass [It]
[Fail] odo devfile url command tests Creating urls [It] create with now flag should pass 
/go/src/github.com/openshift/odo/tests/helper/helper_run.go:34
Ran 59 of 59 Specs in 597.385 seconds
FAIL! -- 58 Passed | 1 Failed | 0 Pending | 0 Skipped 
```
From these logs it doesn't look like namespace is getting deleted beforehand. There's a timeout happening:
```
[odo]  ✗  Waiting for component to start [5m]
[odo]  ✗  Failed to start component with name hohnkv.
[odo] Error: Failed to create the component: error while waiting for deployment rollout: timeout while waiting for hohnkv deployment roll out
```
[Link to the logs](https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/3252/pull-ci-openshift-odo-master-v4.3-integration-e2e/753).
