### ISSUE TITLE
odo list -o json should return json with empty list if no component present

### ISSUE THREAD

**Issue by mohitsuman** [openshift/odo#1521] opened 2019-03-26 22:33 UTC
[kind/bug]

## What versions of software are you using?
- Operating System: macOS
- Output of `odo version`:

```
odo v0.0.20 (bd3e74a4)
Server: https://192.168.64.13:8443
Kubernetes: v1.11.0+d4cacc0
```

## How did you run odo exactly?
`odo list --app <app> --project <proj> -o json`

## Actual behaviour
Currently it prints the text as mentioned below:
`✗  There are no components deployed.`

## Expected behaviour
If there are no components `odo list --app <app> --project <proj> -o json` should return an empty list.
`
{
  "kind": "List",
  "apiVersion": "odo.openshift.io/v1alpha1",
  "metadata": {},
  "items": []
}
`

**Comment by girishramnani** [comment] 2019-03-27 18:16
I am not able to reproduce this @mohitsuman 
```
[gramnani@girish openshift]$ odo list --app e2e-zful --project myproject -o json
{"kind":"List","apiVersion":"odo.openshift.io/v1alpha1","metadata":{},"items":[]}
[gramnani@girish openshift]$ odo version
odo v0.0.20 (a288bb99)

Server: https://192.168.42.139:8443
Kubernetes: v1.11.0+d4cacc0

```
can you share your steps to reproduce this?

**Comment by mohitsuman** [comment] 2019-03-27 19:18
@girishramnani Below is the mentioned steps with screenshot.
1. Create application from vscode UI.
2. Run odo command from vsode terminal
- `odo list --app throne --project myproject -o json`
3. The output is string instead of json.

**I can see that the odo version output for 0.0.20 has a different commit hash for me**.

<img width="660" alt="Screenshot 2019-03-28 at 12 46 41 AM" src="https://user-images.githubusercontent.com/3133356/55105678-1ae4fb80-50f3-11e9-8b29-8682d1fdf6c9.png">

**Comment by dgolovin** [comment] 2019-03-27 21:00
This is duplicate and was fixed in master https://github.com/openshift/odo/issues/1326.

**Comment by mohitsuman** [comment] 2019-03-29 11:21
@girishramnani Did you try this on macOS build ? It works on windows one for some reason.

**Comment by surajnarwade** [comment] 2019-04-02 14:02
@mohitsuman , can you test it against master again ?

**Comment by surajnarwade** [comment] 2019-05-15 11:00
Closing this since issue is resolved

```
$ odo list -o json
{"kind":"List","apiVersion":"odo.openshift.io/v1alpha1","metadata":{},"items":[]}
```

**Closed by surajnarwade** 2019-05-15 11:00 UTC
Labels: kind/bug, priority/Medium
